:PROPERTIES:
:ID:       8aa88129-b937-4320-88ab-da40e1feebaf
:END:
#+title: Matinée habilitation Auragen
#+date: 2024-05-14
#+filetags: habilitation auragen

* Présentation
** Personnes
- Christine Vinciguerra : directrice Auragen
- Julien Fauré : biochimie, post-ana Auragen
- Anne Mc Leer Sandrine Boyault : responsable opérationnelle pré-ana
- Virginie : bioinfo
- Jérémie Mortreaux : futur interprétateur

** Plan france médecine génomique
CAD = collecteur analyseur de données = centre national de calcul
intensif
Prévision 2016: 235K génome /an 20k patients maladies rares 50k cancer réfracteaire
Seqoia vs Auragen, posiiton divisée en 2

** Structure
Géré par consortium
-  GCS : clermontferrnand, grenoble, lyon,
saint-etienne + lyon. Administrateru : Anne Kittler, responsable
scientifique : Pr Jean-Yves Blay
-  partenaire :
-  infrastructure : wet = HCL, calcul = grenobe

Site:
-  séquencage : HEH, HCL (lyon))
-  bioinfo onco = CLB (lyon),
maladies rares (grenoble)

Structure: responsable 
-  responable labo : Christine Vinciguerra

Préana : sandrine boyault
-  Analytique: Anne Thomas (Virgine Bernard)

post-ana : Julien fauré (Anne mcLeer)
-  qualité : anne-christine waymel

** Technique
Objectif: 18k génome/an
- > quasiment rempli
  Analyses :
-  maladies rares:
génome 30x en trio de préférence
-  cancer:
-  somatique: génome 60x,
exome 200x, RNAseq
-  germinal: génome 30x Janvier 2020: foetopath

Séquenceur: 4 novaseq6000, 1 novaseqX plus Hébergement HDS-RGPD
Accréditation COFRAC (01/05/2024)

ADN extrait : à éviter, on préfère

** Biologiste
Convention pour bio en dehors GCS 144 (22 cancer, 111 maladies rares) 35
praticien en formation (non habilité) avec tuteur 15 cours
d'habilitation

Objectif : formation par auragen en échange de la participation aux
activités

** Processus
20% non conf (membre manquant, documents...) Circuit rapide (juillet
2023) : mineurs en réa avec génome pouvant modifier prise en charge ->
accepté après discussion biologiste

** Réunions
- Mensuel des bio : 2e jeudi du mois (visio). Format libre. Julien Fauré
- bio-info et bio (visio)
- journée annuelle des bio maladies rares : 5 juillet 2024
- coordonnateur pré-indic

Qui peut être tuteur ? Biologiste habilité (et doit pouvoir exercer la
biologie médicale) Maintient habilitation: 1 dossier tous les 6 mois
Pour se ré-habiliter, refaire la formation

** Formation qualité
Hygen = prescription, compte-rendu au prescripteur Attention: bioinfo
somatique = lyon (CLB) Lyon nous transfère les fichiers .BCL

À lire en priorité - référentiel accréditation (15189, REF-02 et
08...) - documentation: manuel qualité, validation, controle qulatié,
non conf, prestatino, réclamations, risques, formation
** Pré-analytique
Tutorials pour prescriptino/envoi sur www.auragen.fr
Transporteur TSP (portail.ts-medical.net/colibri)
Échantillion
-  maladie rare/ocon : sang total EDTA ++ (sion ADN extrait/tissu foetal/culot cellulaire)
-  cancer
:  tissu toral et sang total congeé (tumeur solides (FFPE pour 4
pré-indic)
-  sang/moelle/culot cellulaire pour leucémie adulte (ou ADN
extrait)
-  ADN/ARN extrait leucémie enfant

** Hygen Création compte
hygen
-  via formulaire en ligne (prescription/conseilleur) pour maladie
rare onco
-  bio : habilitation auragen + formation

Données cliniques obligatoires =
-  Maladies rares:
-  indication

symptômes HPO
-  généalogie cas index + apparenté + satuts maladies
examens 1ere/2e intention option: gènes supposé, commentaires, symptômes
apparentés
-  onco
-  Phénotypes tumoreaux extrême isolé: ???
-  Histoire
familiale sévère évoquant prédisposition : obligatoire = indication,
génétique déjà fait, nb cancer famille, nb cancer index, généaolige
index+ apparentes, satuts maladise apparentés
-  cancer : indication,
attente, génétique déjà fate, histilogie, description prélèvement, %
cellules tumorale

si non conforme
-  bloquant : prélèvement conservé congelé jusque levé
(ex: pas de consentement ou de feuille de transfert, tubes endommagé/mal
identifiés, erreur d'étiquettage)
-  non bloquant: traité mais doit être
levé avant interprétation (ex: erreur température d'envoi, > 7 jours
avant reception)

** Post-analytique
Dry
- > mise à disposition des dossier
- > répartition
- > analyse
(LBMMS/RVI )
- > résultat
- > CR +/- RCP d'avant
- > CR rendu prescriptieur
Résultat (MR)
-  concluant : variant associé à la patho. Peut expliquer
partiellement le phénotype mais à discusser au cas-par-cas
-  non
concluant : en l'état des connaissance, on ne peut pas l'impliquer.
supplémentaire
- > réunion d'interprétetation clinico-biologique
-  non
conclusif

[[id:4b189666-2c75-4a9b-b95a-00343cb223d0][Aurapport]]
[[id:5d2f248a-52c0-42e8-af45-c6af87b3de1f][Auraweb]]

** Hygen
Émission CR
- status: concluant, non conclusif, non réalisable/non exploitable
- 2 signataires

** Bioinfo
100 nouveaux dossier par semaine
