#+title: Reunion_bio_20240613

- Introduire la notion bluegreen
- IGV avec le CI en 1ère position pour tout dossier: il y a eu des couacs, réglé pour tous les dossiers si mail bioinfo. Rapidement.
- Gestion des arbres pour les dossiers bluegreen & les réanalyses. Contexte : il n'y avait pas les arbres pour les réanalyses
Affichage des samplot / STR pour tous les dossiers non "classiques" comme les -r ou -t. Idem. Message clé "tout doit fonctionner"

- Si 1 dossié est poussé vers Hygen, blocage des 2 dossiers blue & green : Message clé : rassurer les bio (on n'écrase pas les dossiers)
  ex: MR-2304917

***

TOUTES VERSIONS
- Rappel des informations "structure familiale" via le "+" en bas de page à gauche pour toutes les pages de variants
-> projection avoir les HPO

- Ajout lien gnomAD même si 0 occ annoncée (MM) : déployée mercredi 10
- Ajout lien vers pubmed pour les gènes non OMIM pour tout dossier: on pointait vers clingen avant
- Affichage d'un lien direct MobiDetails
- Lien Decipher fonctionnel ciblé sur le gène (contexte : il y avait un bug)
 > projection vers ta proposition

VERSIONS 7.0 et +
- Mise à disposition de la qualité des CNV manta (contexte : variant manqué donc on relâche un peu les filtres)
- Mise à disposition des pLI > 0.9 pour les CNV & SV - si < 0.9 rien n'est affiché: démo


VERSIONS 8.0 et +

Mise à jour des transcrits MANE & affichage si non dispo
MANE / LRG / longest (gencode 32?)

à voir avec Maelle = les sans MANE gris
