#+title: Nix
* Nixos
Installer nix. Par exemple, sous WSL:
https://github.com/nix-community/NixOS-WSL

Puis modifier /etc/nixos/configuration.nix.

** 1. Emacs nativecomp + flakes + WSL
Il faut rajouter un overlay. Cela va compiler emacs
#+begin_src sh
{ lib, pkgs, config, modulesPath, ... }:

with lib;
let
  nixos-wsl = import ./nixos-wsl;
in
{
  imports = [
    "${modulesPath}/profiles/minimal.nix"

    nixos-wsl.nixosModules.wsl
  ];

  wsl = {
    enable = true;
    automountPath = "/mnt";
    defaultUser = "nixos";
    startMenuLaunchers = true;

    # Enable integration with Docker Desktop (needs to be installed)
    # docker.enable = true;
  };

  # Enable nix flakes
  nix.package = pkgs.nixFlakes;
  nix.extraOptions = ''
    experimental-features = nix-command flakes
  '';

  # Emacs28 with nativecomp
  services.emacs.package = pkgs.emacsNativeComp;

  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
    }))
  ];

  environment.systemPackages = with pkgs; [
          emacsNativeComp
  ];
}
#+end_src
Puis installer avec
#+begin_src
nixos-rebuild switch
#+end_src
** 2. Ajouter des logiciels au niveau global
il sufit de modifier
#+begin_src
  environment.systemPackages
#+end_src
et de lancer ensuite
#+begin_src sh
nix-os rebuild switch
#+end_src
NB: il manque man par défaut !.
Doc officielle : https://nixos.org/manual/nixos/stable/
** Suive avancement des branches (unrstable, stable...)
Plusieurs possibilités
1. https://nixpk.gs/pr-tracker.html?pr=188777
2. https://status.nixos.org/
3. Simply clicking on a commit on GitHub shows branches and tags containing that commit.

* Nix
Activer les flakes (experimental) ! Meilleure expérience utilisateur
** WSL2: changer /nix/store
Pour accéder à un lecteur US:, rajouter dans /etc/fstabl
#+begin_src sh
 E: /mnt/e drvfs defaults,uid=1000,gid=1000,metadata 0 0
#+end_src
`metadata` est important car cela nous permet de changer les permissions !
Puis
#+begin_src sh
mount --bind /mnt/e/nix /nix
#+end_src
** Recherche
`nix-env` est lent. `nix search` avec les flakes ne fonctionne pas bien pour certains packages (récursif mais certains paquets désactivent l’évalution)
Meilleures solution :
- search.nixos.org
- `nix-index`  : installer puis `nix-indx` puis chercher par nom de ficher. Ex: `nix-locate bin/R`
** Développer un package
*** Hash
#+begin_src
nix-prefetch-url --unpack https://...tar.gz
#+end_src
Ou bien, ne pas mettre de hash et copier le résultat de l’erreur !
*** Pour débugger une derivation, on utilise un shell en appelant le package :
Sans Flakes
#+begin_src nix
nix-shell -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
[nix-shell]$ eval ${unpackPhase:-unpackPhase}
[nix-shell]$ cd source
[nix-shell]$ eval ${configurePhase:-configurePhase}
[nix-shell]$ eval ${buildPhase:-buildPhase}
#+end_src
** Pour installer une seule dérivation
#+begin_src
nix-shell -p 'with import <nixpkgs>{}; callPackage pkgs/GenomeRef.nix {}'
#+end_src
Ne pas oublier {}
** Python
Instructions simples ici : https://nixos.wiki/wiki/Python#Package_and_development_shell_for_a_python_project

Il faut donc setup.py:
#+begin_src python
#!/usr/bin/env python

from setuptools import setup, find_packages

setup(name='demo-flask-vuejs-rest',
      version='1.0',
      # Modules to import from other scripts:
      packages=find_packages(),
      # Executables
      scripts=["web_interface.py"],
     )
#+end_src
Et 2 fichiers .nix, le premier pour les dépendances
#+begin_src sh
{ lib, python3Packages }:
with python3Packages;
buildPythonApplication {
  pname = "demo-flask-vuejs-rest";
  version = "1.0";

  propagatedBuildInputs = [ flask ];

  src = ./.;
}
#+end_src
et le défaut
#+begin_src
{ pkgs ? import <nixpkgs> {} }:
pkgs.callPackage ./derivation.nix {}
#+end_src
Il ne reste plus qu’à le construire
#+begin_src
nix-build
result/bin/lol.py
#+end_src
** Upgrade
Après avoir ajouté un channel:

nix.package = (import <nixos-unstable-small> {}).nix

** Patcher
#+begin_src
    nixpkgs.overlays = [
      # Patch to avoid out-of-memory errors in nix
      (final: prev: {
        nix = prev.nix.overrideAttrs (old: {
          patches = (old.patches or []) ++ [./0001-don-t-read-outputs-into-memory-for-output-rewriting.patch ];
        });
      })
      ] ;
#+end_src
** Nix profile
(Il faut choisir entre nix profile et nix-env !)
Cherche un programme, l’installer
Installer un programme
#+begin_src sh
nix profile search nixpkgs#zoxide
nix profile install nixpkgs#zoxide
#+end_src
Tout supprmier
#+begin_src sh
nix profile remove '.*'
#+end_src
* Nixpkgs
** Ajoutr un nouveau paquet
https://nixos.wiki/wiki/Nixpkgs/Contributing
* Avertissements
Ne jamais modifier les fichiers dans /nix/store
