* <2018-07-18 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout
  :END:

#+BEGIN_EXAMPLE
  Frog Stand 3x5s Wall HeSPU 3x1 Muscle Up négatives 3x3 (1/3 de la
  descente) Advanced back lever 7+8+15s Advanced tuck Front lever
  12+13+14s
#+END_EXAMPLE

* <2018-07-22 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-1
  :END:

#+BEGIN_EXAMPLE
  Jul 22 11:19:47 CEST 2018 Frog Stand : plus la force Wall HeSPU
  0 Muscle Up négatives 3+2+2 (1/3 de la descente) Advanced back lever
  10x3 Advanced tuck Front lever 10x3
#+END_EXAMPLE

* <2018-07-25 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-2
  :END:

Jul 25 10:00:13 CEST 2018 Frog Stand 3x2s Wall HeSPU 2 Muscle Up
négatives 3x3 (1/2 de la descente) Advanced back lever 3x5s Advanced
Front lever 3x5s

* <2018-08-13 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-3
  :END:

#+BEGIN_EXAMPLE
  Aug 13 14:24:09 CEST 2018 Short-term goals (5 sets of 6-8s for
  static, 5 sets of 9-12 repeats):

  -   Free Handstand 10s (ATM: 3x3s max)
  -   L-sits 6s (ATM: 3x4s)
  -   Negative muscle-up (ATM: 0)
  -   Straddle planche (ATM : advanced tuck planche 3x3s)
  -   Back lever advanced tuck (ATM: tuck)
  -   Front lever advanced tuck (ATM: tuck/advanced tuck)
  -   Pull-over (ATM : weak L-pull-ups, 3x3)

  Programme : (Negative muscle-up x1 - 2.5min - L-sit x1 - 2.5min)x 3
  (planche x1 - 2.5min - front lever x1 - 2.5min)x 3 Negative
  muscle-up : 3x5 but failed L-sit 3x6s SA frog stand : 6-5-4s back
  lever : 3x5s
#+END_EXAMPLE

* <2018-08-23 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-4
  :END:

#+BEGIN_EXAMPLE
  Aug 23 19:39:30 CEST 2018 Negative muscle-up : 3x3, knee at 100
  degree Lsit 6-7-7-7-6s Advanced tuck back lever : 4-3-1 s but bad
  form, go back on tuck Wall HeSPU : during breaks (1). 2 at once Tuck
  planche : 8-7-8s Advanced tuck front lever : 6-8-9-5
#+END_EXAMPLE

* <2018-08-29 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-5
  :END:

Aug 29 20:15:55 CEST 2018 Negative muscle-up : 4 avec genou à 90 degré,
4 à 45 degré, 3 avec anneaux au niveau triceps mais besoin des pieds
L-sit 8-7-7-7-5 Wall HeSPU 5x1 + 1x2 Tuck back lever 15s Advanced tuck
back lever 2x6s (work on form) Tuck planche 9-8-8

* <2018-09-02 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-6
  :END:

#+BEGIN_EXAMPLE
  Sep 2 22:14:06 CEST 2018 Negative muscle-up : 3-4-4 avec
  aideavec genou à 90 degré, 4 à 45 degré, 3 avec anneaux au Lsit :
  8-8-8 Wall HeSPU 6x1 Advanced tuck back lever : 3-7-7 (90) Front
  lever : 8-8-7
#+END_EXAMPLE

* <2018-09-07 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-7
  :END:

#+BEGIN_EXAMPLE
  Sep 7 19:45:50 CEST 2018 Negative muscle-up : 3-7-5-5 en partant
  accroupi + aidee jambes Lsit : 9-8-8-7 Wall HeSPU 6x1. 1x2 Advanced
  tuck back lever : 7-7-6 Advanced front lever : 7-9-8 Advanced tuck
  Planche 8-7-6
#+END_EXAMPLE

* <2018-09-10 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-8
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 3 simple-3x3 montée+descente en partant
  accroupi, anneaux aux épules (cf FitnessFAQ) aidee jambes Lsit :
  10-8-7 Wall HeSPU 5x1 Advanced tuck back lever : 2x6 (un peu plus
  propre) Advanced front lever : 8-10-10 Advanced tuck Planche : 9-8-9
#+END_EXAMPLE

* <2018-09-13 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-9
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 3x5 Lsit : 10-10-10 Wall HeSPU 5x1 Advanced
  tuck back lever : 10
#+END_EXAMPLE

* <2018-09-18 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-10
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 3x5 (avec l\'aide de al pointe des pieds) Lsit
  : 10-9-9 Wall HeSPU : 6x1 Advanced tuck back lever : 3x10 Advanced
  tuck planche : 3x7
#+END_EXAMPLE

* <2018-09-19 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-11
  :END:

#+BEGIN_EXAMPLE
  Stretch : splits
#+END_EXAMPLE

* <2018-09-20 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-12
  :END:

#+BEGIN_EXAMPLE
  Stretch : splits Negative muscle-up : 5-4-3-2 Lsit : 10-10-9 Wall
#+END_EXAMPLE

HeSPU 6x1 Advanced tuck back lever : 11-10 Advanced tuck planche : 9-5

* <2018-09-24 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-13
  :END:

#+BEGIN_EXAMPLE
  2x10s pancake split 1x10s toe touch Shoulder
#+END_EXAMPLE

* <2018-09-25 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-14
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 3x5 Lsit : 11-9-6 Wall HeSPU : 7x1 Advanced
  tuck back lever : 7-8-8 Advanced tuck planche : 9-7-6 Advanced tuck
  front lever : 8 Shoulder 3 (cf reddit) 10s each 1x90s pancake split
#+END_EXAMPLE

* <2018-09-27 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-15
  :END:

#+BEGIN_EXAMPLE
  Pancake split 60s Split routine 1x10s each Toe-touching
#+END_EXAMPLE

* <2018-09-28 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-16
  :END:

#+BEGIN_EXAMPLE
  Pancake split 90s
#+END_EXAMPLE

* <2018-09-30 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-17
  :END:

#+BEGIN_EXAMPLE
  Équilibre x5
#+END_EXAMPLE

* <2018-09-30 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-18
  :END:

#+BEGIN_EXAMPLE
  Pancake 80-55-40 Assis doit droit avec radiateur Splits : avec des
  tabourets pour avoir le dos droit. 15s de chaque : 2xhip flexor et
  split (cf routine d\'Antranik) Negative muscle-up : 5-2-4-83 Lsit :
  9-9-8 Wall HeSPU 7x1 Advanced tuck back lever : 8-7-7 Advanced tuck
  planche : 9-8-9
#+END_EXAMPLE

* <2018-10-01 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-19
  :END:

#+BEGIN_EXAMPLE
  Pancake : 60
#+END_EXAMPLE

* <2018-10-03 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-20
  :END:

#+BEGIN_EXAMPLE
  Pancake : 80-60 Split : 20s pour 3 échauffement et 40s de splits de
  chaque côté
#+END_EXAMPLE

* <2018-10-04 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-21
  :END:

#+BEGIN_EXAMPLE
  Équilibre
#+END_EXAMPLE

* <2018-10-05 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-22
  :END:

#+BEGIN_EXAMPLE
  Équilibre Pancake : douleur au dos assis au sol en tiran sur le
  radiateur. Progression de Tom Maverick à la place. 2x70 sur une
  chaise (ok) puis 65 sur une marche (seuil actuel). Pas de douleurs
#+END_EXAMPLE

* <2018-10-06 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-23
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 4.5-4.5-3-3 Lsit : 3x9 Wall HeSPU 6x1 (plus
  exigeant sur la forme !) Tuck back lever : 3x7 (dos rond...)
  Advanced tuck planche : 3x9 Pancake : 90 sur une chaise, 2x60 sur
  une marche
#+END_EXAMPLE

* <2018-10-07 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-24
  :END:

#+BEGIN_EXAMPLE
  ****Objectifs**** étirement à 2 semaines : handstand 10s, pancake
  assis au sol 30s, split 60
#+END_EXAMPLE

* <2018-10-08 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-25
  :END:

#+BEGIN_EXAMPLE
  Splits : 30s (3 échauffement et split) Pancake 60s chaise 60s marche
#+END_EXAMPLE

* <2018-10-09 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-26
  :END:

Handstand : max = 8s Toe-touching x1

* <2018-10-11 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-27
  :END:

Handstand : 11s une fois ! Pancake : 1x chaise, 1x marche, non chrono

* <2018-10-12 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-28
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 4-5-3 Lsit : 3x9 Wall HeSPU 11x1 + 2 Tuck back
  lever : 2x7-8 Advanced tuck planche : 9-9-7
#+END_EXAMPLE

* <2018-10-24 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-29
  :END:

#+BEGIN_EXAMPLE
  Pushup planche 6-3 Negative muscle-up : 4-4-3 Lsit : 8-6-7 (jambe
  quasi tendu) Handstand pushup lvl 2 : 3-4-3 (new progression, see
  <https://www.youtube.com/watch?v=h0HjqYRlXYg>) Advanced tuck back
  lever : 5-5 Planche : 6x1 passages (rapide) tuck - genou écartés -
  tuck (<http://gmb.io/planche/> \"straddle open tuck hold\").
#+END_EXAMPLE

* <2018-11-12 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-30
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 5-4-4 L-sit 6-6-6 Handstand pushup lvl 2 :
  4-4-4 Tuck back : 4-5-4
#+END_EXAMPLE

* <2018-11-19 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-31
  :END:

#+BEGIN_EXAMPLE
  Negative muscle-up : 4-3-3 Lsit : 5-5 (jambes tendues) Handstand
  pushup lvl 2 : 4-4 Advanced tuck back lever : 5-4 (dos droits, jambe
  90 ?) Planche : 4x1 passages (rapide)
#+END_EXAMPLE

* <2018-11-26 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-32
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 4-2 (réussi ???)-0 Lsit : 7-5-5 (jambes tendues)
  Advanced tuck back lever : 5 (fesse hautes)-5 (dos droit !)-5
#+END_EXAMPLE

Handstand pushup lvl 2 : 4-4-5 (dernier quasi sans appuis) Planche : 1x2
passages (rapide)

* <2018-11-30 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-33
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 1.5-2-1 (assis, bras tendus) Lsit : 7-6-5 Wall HeSPU :
  4-4 Advanced tuck back lever : 5-6-5 Tucked planche (outside-inside)
  2-3-3
#+END_EXAMPLE

* <2018-12-02 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-34
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 2-1-1 (L-sit sans toucher le sol !) Lsit : 6-6-6 Wall
#+END_EXAMPLE

HeSPU : 4-4-4 Advanced tuck back lever : 6-6-5 Tucked planche
(outside-inside) 3-3-4

* <2018-12-07 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-35
  :END:

#+BEGIN_EXAMPLE
  Muscle-up (L-sit) : 0 (6 tentatives)-2-1 Lsit : 7-5-6 Wall HeSPU :
  5-4-4 Advanced tuck back lever : 8-8-7 Tucked planche
  (outside-inside) 5-4-2
#+END_EXAMPLE

* <2018-12-11 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-36
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : (3 tentatives)-1-1 Lsit : 7-7-7 Wall HeSPU : 5-4-4
  Advanced tuck back lever : 7-7-7 Tuck - one-leg : 3x1s
#+END_EXAMPLE

* <2018-12-15 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-37
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 1-2-2 Lsit : 9-5-6 Wall HeSPU 4-4-4 (les pieds
  \"sautent\") Advanced tuck back lever : 8-5-6 Tuck - one-leg :
  3x0.5s (2 pieds l\'un après l\'autre)
#+END_EXAMPLE

* <2018-12-20 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-38
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 2-0-1 Lsit : 9-9-8 Wall HeSPU 4-3-2 Advanced tuck back
  lever : 4-6-4 Tuck - one-leg : 2x1s
#+END_EXAMPLE

* <2018-12-30 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-39
  :END:

#+BEGIN_EXAMPLE
  Muscle-up : 0-1.5-1:5 Lsit : 10-9-7 Advanced tuck back lever : 4-6-6
  Tuck - one-leg : 11
#+END_EXAMPLE

* <2018-10-19 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand
  :END:

* <2018-10-20 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-1
  :END:

* <2018-10-21 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-2
  :END:

* <2018-10-24 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-3
  :END:

#+BEGIN_EXAMPLE
  Un peu de travail de changement position (\"banane\"-\"droit\").
  Super dur
#+END_EXAMPLE

* <2018-10-25 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-4
  :END:

* <2018-10-28 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-5
  :END:

* <2018-10-29 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-6
  :END:

* <2018-10-30 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-7
  :END:

* <2018-11-01 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-8
  :END:

* <2018-11-02 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-9
  :END:

* <2018-11-03 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-10
  :END:

* <2018-11-05 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-11
  :END:

* <2018-11-09 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-12
  :END:

* <2018-11-11 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-13
  :END:

* <2018-11-12 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-14
  :END:

* <2018-11-13 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-15
  :END:

* <2019-01-02 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-40
  :END:

Wall straddle press eccentrics : moitié du mouvement Straddle L-sit (
[[https://www.youtube.com/watch?v=FAkSQE9cLDM]] ) seated : 2x10 (jambes
mi-pliées...) Muscle-up : 0-2x0.5-1.5 PLanche pull-up : 5-4-4 L-sit
(rings, jambes pliées) : 3x3 Advanced tuck back lever : 7-6-6

* <2019-01-04 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-41
  :END:

Wall straddle press eccentrics : 2x4 (demi en remontée) Straddle L-sit
seated : 2x10 (jambes mi-pliées...) Muscle-up : 1.5-2-2 L-sit (rings,
jambes tendues à 80%) : 2x3 Advanced tuck back lever : 6-6-5 Handstand
push-up : 3x3 Tuck - one-leg : 4x1s (2 jambes à la fois, extension
complète !)

* <2019-01-07 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-42
  :END:

Wall straddle press eccentrics : 2x2 (demi en remontée) Straddle L-sit
seated : 2x10 (jambes mi-pliées...) Muscle-up : 3x2 :) Advanced tuck
back lever : 6-6-6 Handstand push-up : 2 (sans "sauter" avec les pieds)
Tuck - one-leg : 3x1s

* <2019-01-10 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-43
  :END:

Wall straddle press eccentrics : 4-2 Straddle L-sit seated : 3x10
Muscle-up : 2-1.5-(0.5x2) L-sit (rings, jambes tendues à 80%) : 4-4
Advanced tuck back lever : 7-6(jambe 45° !)-5 Handstand push-up : 3x3
Tuck - one-leg : 3x1

* <2019-01-12 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-44
  :END:

Wall straddle press eccentrics : 3x4 Straddle L-sit seated : 3x10
Muscle-up : 3x2 (bras tendu ! et false grip) L-sit (rings, jambes non
parallèles au sol) : 3x3s Advanced tuck back lever : 3x6s Handstand
push-up : 3x3 Tuck - one-leg : 4x1s

* <2019-01-19 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-45
  :END:

Wall straddle press eccentrics : 4-1 Straddle L-sit seated : 3x10
Muscle-up : 4x3 (que du négatif, impossible d'en refaire normalement
ajourd'hui) L-sit (rings, jambes non parallèles au sol) : 2x3 Advanced
tuck back lever : 5-4-3 Handstand push-up : 3x4 Tuck - one-leg : 3x1

* <2019-01-23 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-46
  :END:

Wall straddle press eccentrics : 3-3-2 Straddle L-sit seated : 3x10
Muscle-up : 3 (négatif) - 3 avec appui - 3 (appui) L-sit (rings, jambes
non parallèles au sol) : 3x1s Advanced tuck back lever : 3x3s Handstand
push-up : 3-3-2.5 (plus en avant) Tuck - one-leg : 3x1

* <2019-01-25 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-47
  :END:

Wall straddle press eccentrics : 3-5-5 Straddle L-sit seated : 3x10
Muscle-up : 4x3 (avec pied pour travailler technique) L-sit : 3-2-2
Advanced tuck back lever : 5-6-4 (dernier = jambe mi pliées) Handstand
push-up : 1.5-3 Tuck : 8-6 -4-4(retour dos droit en statique, 30° avec
le sol, 2 derniers avec jambes pliées)

* <2019-01-30 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-48
  :END:

Wall straddle press eccentrics : 5-4-4 Straddle L-sit seated : 3x10
Muscle-up : 4-3-3 (appui) L-sit : 5-3-4 (au sol) Advanced tuck back
lever : 5-5-5 Handstand push-up : 4-3-2 Tuck : 4-4-2s

* <2019-02-03 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-49
  :END:

#+BEGIN_EXAMPLE
  all straddle press eccentrics : 4-5-4 Straddle L-sit seated : 3x10
  Muscle-up : 6x3 (test, pour l\'instant anneau niveaau épaule) L-sit
  : 6-5-3 (au sol) Advanced tuck back lever : 3x3 Handstand puss-up :
  4-1-3 Tuck : 4-s
#+END_EXAMPLE

* <2019-02-07 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-50
  :END:

Wall straddle press eccentrics : 4-4 Straddle L-sit seated : 3x10
Muscle-up : 3x3 L-sit : 4-4-4 Advanced tuck back lever : 4-4-4 Handstand
puss-up : 3-3-1 Tuck : 3x4

* <2019-02-12 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-51
  :END:

Wall straddle press eccentrics : 4-3-5 Straddle L-sit seated : 3x10
Muscle-up : 3 debout épaule, 3 debout tiers nuque, 3 machoire, 3 oreille
L-sit : 4-4-4 Advanced tuck back lever : 6-6-6 Handstand push-up : 3-3-3
Tuck : 5-5-5

* <2019-02-17 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-52
  :END:

Wall straddle press eccentrics : 4-3-3 Straddle L-sit seated : 3x10
Muscle-up : 3 (machoire, accroupi) 2x3 (milieu cou, idéal pour ne pas
s'aider des pieds) L-sit : 4-4-4 Advanced tuck back lever : 7-7-5
(jambes sous thorax encore) Handstand push-up : 3x3 Tuck : 6-5-5

* <2019-02-20 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-53
  :END:

Wall straddle press eccentrics : 4 Straddle L-sit seated : 3x10
Muscle-up : 3-3-2-2-1 (mi cou) L-sit : 6-6-5 Advanced tuck back lever :
7-7-5 Handstand push-up :3-2-3 (plus dur si plus en vanat) Tuck : 6-6-5

* <2019-02-22 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-54
  :END:

Wall straddle press eccentrics : 3-4-6 Straddle L-sit seated : 3x10
Muscle-up : 3-3-2-2 (base cou pour technique) L-sit : 6-3-4-5 Advanced
tuck back lever : 7-7-6 Handstand push-up : 3-3-3 Tuck : 6-4-5

* <2019-02-27 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-55
  :END:

Wall straddle press eccentrics : 3x10 Straddle L-sit seated : 3x3
Muscle-up : 3-3 L-sit : 4-5-4 Advanced tuck back lever : 7-7-7 Handstand
push-up : 3-3-2 Tuck : 6-5-4

* <2019-02-02 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-16
  :END:

* <2019-02-03 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-17
  :END:

#+BEGIN_EXAMPLE
  Travail de changement de position. Difficile mais semble super utile
#+END_EXAMPLE

* <2019-02-07 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-18
  :END:

#+BEGIN_EXAMPLE
  Pieds joints en changeant de position
#+END_EXAMPLE

* <2019-03-02 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-56
  :END:

Wall straddle press eccentrics : 2-2-7 Straddle L-sit seated : Muscle-up
: 3-3-2-2 L-sit : 4-4-4 (jambes bien droite mais un peu bas) Advanced
tuck back lever : 6-6-5 (plus à angle droit) Handstand push-up : 3-2-2
(peut-être plus droit) Tuck : 3x5

* <2019-03-10 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-57
  :END:

Wall straddle press eccentrics : 3x10 Straddle L-sit seated : 6-6-5
Muscle-up : 3-3-3 L-sit : 4-5-4 Advanced tuck back lever : 6-6-5
Handstand push-up : 3-2-3 Tuck : 5-5-5

* <2019-03-13 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-58
  :END:

Wall straddle press eccentrics : 6-3-3 Straddle L-sit seated : 3x10s
Muscle-up : 3-3-3 (niveau épaule pour technique) L-sit : 4-4-5 Advanced
tuck back lever : 6-6 Handstand push-up : 3-3-2 Tuck : 6

* <2019-03-25 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-59
  :END:

Wall straddle press eccentrics : 4-4-2 Straddle L-sit seated : 3x3
Muscle-up : 3-3-3 L-sit : 4-4-5 Advanced tuck back lever :6-7-6
Handstand push-up : 2.5-2-2 Tuck : 6-5-5

* <2019-03-29 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-60
  :END:

Wall straddle press eccentrics : 6-6-5 Straddle L-sit seated : 3x10
Muscle-up : 3-2-2-2 L-sit : 5-5-4

* <2019-04-01 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-61
  :END:

Wall straddle press eccentrics : 6-5-5 Straddle L-sit seated : 3x10
Muscle-up : 3-3-2 L-sit : 3x4 Advanced tuck back lever : 7-7-6 Handstand
push-up : 3-2-3 Tuck : 5-4-4

* <2019-04-03 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-62
  :END:

Wall straddle press eccentrics : 3x5 Straddle L-sit seated : 3x10
Muscle-up : 3-3-3 L-sit : 5-4-5 Advanced tuck back lever : 6-6 Handstand
push-up : 3-3-3

* <2019-04-09 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-63
  :END:

Wall straddle press eccentrics : 3x4 Straddle L-sit seated : 3x10
Muscle-up : 3x3 L-sit : 3x4 Advanced tuck back lever : 3x6 Handstand
push-up : 3-3 Tuck : 4-4-4

* <2019-04-11 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-64
  :END:

#+BEGIN_EXAMPLE
  Floor to hEADstand : 1-2-2 Straddle L-sit seated (lent) : 5-5
  Muscle-up : 3-2-3 Tucked planche (retour aux bases) : 10s-10
#+END_EXAMPLE

* <2019-04-17 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-65
  :END:

Wall straddle press eccentrics : 5-5-3 Straddle L-sit seated : 3x5
(lent) Muscle-up : 3x3 (rings au niveau des épaules, usage de la pointe
des pieds encore) L-sit : 5-5-4 Advanced tuck back lever : 6s-6
Handstand push-up : 3-3-2 Straddle Open Tuck Hold: 1-2s

* <2019-04-24 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-66
  :END:

Wall straddle press eccentrics : 3-3-4 Straddle L-sit seated : 2x5
Muscle-up : 3-3-2 L-sit : 4 (crampe...)-2-3 Advanced tuck back lever :
6-6-6 Handstand push-up : 3-3-2 Straddle Open Tuck Hold: 1-2-2s

* <2019-04-27 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-67
  :END:

Wall straddle press eccentrics : 5-6-7 Straddle L-sit seated : 6-6-6
Muscle-up : 3-3-3 L-sit : 5-4-5 Tuck back lever : 6-7 Handstand push-up
: 3-3-3 Tuck : 0-1

* <2019-04-23 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-19
  :END:

2. Handstand

* <2019-04-24 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-20
  :END:

* <2019-05-01 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-68
  :END:

#+BEGIN_EXAMPLE
  Straddle L-sit seated : 5-5-5 Muscle-up : 3-2-2-1 L-sit : 4-4 Tuck
  back lever : 4-5 Tuck : 2-1-3
#+END_EXAMPLE

* <2019-05-09 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-69
  :END:

Wall straddle press eccentrics : 4-5-3 (3 quasi complets)7 Straddle
L-sit seated : 5-5-5 Muscle-up : 3-3-3 L-sit : 5-4-4 Handstand push-up :
3-3-3 Tuck : 2-2

* <2019-05-17 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-70
  :END:

Wall straddle press eccentrics : 1 (entier, négatif)-2-2 Straddle L-sit
seated : 3x3 Muscle-up : 3x3 L-sit : 5 Advanced tuck back lever : 7-6
Handstand push-up : 3x3 Tuck : 3-4

* <2019-05-23 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-71
  :END:

Wall straddle press eccentrics : 2-3-3 (negative) Straddle L-sit seated
: 3x5 Muscle-up : 3x3 L-sit : 5-5-4 Tuck back lever : 6-5-5 Handstand
push-up : 3x3 (travailler forme) Tuck to single leg (each leg) :
0.5(sic)x3

* <2019-05-29 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-72
  :END:

Wall straddle press eccentrics : 3x3 Straddle L-sit seated : 3x5
Muscle-up : 3x3

* <2019-05-01 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-21
  :END:

* <2019-05-07 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-22
  :END:

* <2019-05-08 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-23
  :END:

* <2019-05-09 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-24
  :END:

* <2019-05-10 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-25
  :END:

* <2019-05-15 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-26
  :END:

* <2019-05-16 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-27
  :END:

* <2019-05-17 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-28
  :END:

* <2019-05-20 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-29
  :END:

* <2019-05-21 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-30
  :END:

* <2019-05-23 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-31
  :END:

* <2019-05-24 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-32
  :END:

* <2019-05-25 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-33
  :END:

* <2019-05-26 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-34
  :END:

* <2019-05-27 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-35
  :END:

* <2019-05-28 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-36
  :END:

* <2019-05-29 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-37
  :END:

* <2019-05-30 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-38
  :END:

* <2019-05-31 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-39
  :END:

* <2019-06-02 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-73
  :END:

#+BEGIN_EXAMPLE
  Straddle L-sit seated : 3x5 Muscle-up : 3-3-2 (2 complet !!!) L-sit
  : 5-5-5 Advanced tuck back lever : 5-5-3 Handstand push-up : 3x3
  Tuck (un peu tendu): 2-2
#+END_EXAMPLE

* Revisiting goals (2019-06) Workoutgoals:
  :PROPERTIES:
  :CUSTOM_ID: revisiting-goals-2019-06-workoutgoals
  :END:

Pushing vs pulling

2. Workout

   Muscle-up : vertical pushing, extension Back lever : horizontal
   pulling, extension Planche : horizontal pushing, flexion V-sit :
   pulling, extension

   Handstand pushup : vertical pushing, flexion Front lever : horizontal
   pulling, flexion

   Next levels

3. Workout

   Advance if : 6s for static or 3 clean repetitions for dynamics

   Goals

4. Workout

   Note :

   - handstand + manna are mandataroy fo S. Low and very interesting to
     combine
   - straitght arm press handstand is mandatory and useful for planche

   | Exercice          | Current level |
   |-------------------+---------------|
   | andstand          |               |
   | L-sit/V-sit/manna |               |
   | Press handstand   |               |
   | Back lever        |               |
   | Planche           |               |
   | Muscle-up         |               |

   Routine

5. Workout

   3x5-8 4-5x9-12s (Muscle-up, rest 2.5min, Back lever, rest 2.5min) x3
   (Planche, rest 2.5min, V-sit, rest 2.5min) x3

Warmup : static hold on rings 2. Skill work : L-sit, handstand,
tumbling, core compression 3. Power/eccentrics/isometrics 4. Flexibility

* <2019-06-09 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-74
  :END:

#+BEGIN_EXAMPLE
  NB: pairs with resting 2.5min L-sit: 5-4-4 Compression: 1-5-3s (1cm
  ...) Straddle L-sit: fail Muscle-up: 1tentative avec appui-1
  réussi-2 avec appui Tuck planche: 3x7
#+END_EXAMPLE

* <2019-06-13 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-75
  :END:

#+BEGIN_EXAMPLE
  NB: pairs with resting 2.5min L-sit: 3x1s Compression: 5-8
  Straight-arm rings: 10-17-10 Straddle L-sit: fail Muscle-up: 3-3-2
  (avec pieds. Frayeur car barre de traction tombée...) Tuck planche:
  3-5
#+END_EXAMPLE

* <2019-06-16 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-76
  :END:

#+BEGIN_EXAMPLE
  Straight arms rings : 20-17-15 Pull-up 3-2 Compression 3x8
  Muscle-up + L-sit : 3x3 (2\'30 de repos, L-sit entre 3s et 1s (à la
  fin)) Plank on rings + back lever + front lever: 1-1-1 (\~3s chaque,
  mais mauvaise position)
#+END_EXAMPLE

* <2019-06-20 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-77
  :END:

#+BEGIN_EXAMPLE
  Compression 8-6-6 Muscle-up + L-sit : 3.5#3s-2.5#2s-2#2s Tuck
  planche on rings + tuck front lever + tuck back lever:
  3s#3s#5s-5s#11s#7s-6s#12s#6s
#+END_EXAMPLE

* Setting goals (2019-06-22)
  :PROPERTIES:
  :CUSTOM_ID: setting-goals-2019-06-22
  :END:

Workoutgoals:

#+BEGIN_EXAMPLE
    Now                           Date        Goal
    ----------------------------- ----------- ---------------------
    Muscle-up with feet           +3 months   Strict muscle-up
    Tuck back lever 7s            +1 year     Full back lever 1s
    Avanced tuck front lever 1s   +1 year     Full front lever 1s
    Semi-straddle planche 1s      +3 months   Straddle planche 5s
   Handstand 3s                  +6 months   Handstand 30s
    L-sit 7s                      +6 months   Straddle L-sit 3s
#+END_EXAMPLE

* <2019-06-22 Sat> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour
  :END:

#+BEGIN_EXAMPLE
  Essai des exercices pour le wall climb :
  -   position chat x3
  -   \"pull-up\" en position chat
  -   knee raises (à droite)
  -   extension de la jambe en position chat (x2, jambe non
      complètement tendue)
#+END_EXAMPLE

* <2019-06-23 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-78
  :END:

#+BEGIN_EXAMPLE
  Compression 8-6-6 Straigth arms RTO : 19-20-13 Extension
  (lower-back) : 10-9-10 L-sit (ground) : 3-4-4-2 Muscle-up + tuck
  planche : 4#2s-3#2s tuck front lever + tuck back lever:
  12#12-10#10-12#12-10#6 \*2019-06-29 Compression 8-6-6 Straigth
  arms RTO : 20-19-19 Extension (lower-back) : 20-20 L-sit (ground) :
  6-5-4 Muscle-up + tuck planche : 5#1s-5#1-5#1 tuck front lever +
  tuck back lever: 6#58+7#6+7#6
#+END_EXAMPLE

* <2019-06-09 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-40
  :END:

* <2019-06-10 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-41
  :END:

* <2019-06-11 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-42
  :END:

* <2019-06-15 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-43
  :END:

* <2019-06-16 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-44
  :END:

* <2019-06-17 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-45
  :END:

* <2019-06-18 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-46
  :END:

* <2019-06-20 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-47
  :END:

* <2019-06-21 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-48
  :END:

* <2019-06-22 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-49
  :END:

* <2019-06-24 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-50
  :END:

* <2019-06-25 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-51
  :END:

* <2019-06-26 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-52
  :END:

* <2019-06-28 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-53
  :END:

* <2019-06-30 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-54
  :END:

* <2019-07-01 Mon> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-1
  :END:

#+BEGIN_EXAMPLE
  Rambarde trop glissante...
#+END_EXAMPLE

2. Parkour

   Toujours des difficultés pour le wall-climb : est-ce de la force
   brute pour les bras ? Impossible de pousser avec les jambes et
   envoyer vers le haut...

3. Parkour

4. Handstand

* <2019-07-02 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-55
  :END:

* <2019-07-03 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-79
  :END:

#+BEGIN_EXAMPLE
  Compression 3x8 Planch (sol + bras bien tendus cette fois !!) : 3x8
  Straigth arms RTO : 17-15-12-10 Extension (lower-back) : 15
  Muscle-up + L-sit : 3#1s-3#1-4#1-4#1 (jabmes presques horizontales)
  advanced tuck front lever + advanced tuck back lever: 10#5 (dos
  courbé en back)-6#5 (fesse trop basses, dos droit)-6#5s (bonne
  position, maintenant arriver à avoir jambes à 90°)-6#5-3#3
#+END_EXAMPLE

2. Handstand

* <2019-07-04 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-56
  :END:

* <2019-07-07 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-57
  :END:

* <2019-07-08 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-80
  :END:

#+BEGIN_EXAMPLE
  Compression 8-8-7 Planch (sol + bras bien tendus cette fois !!) :
  4-4-3 Straigth arms RTO : 20-20-17-8 Extension (lower-back) : 3x22
  Muscle-up + L-sit : 3x3#1-2#1 (mais jambes à 90° quasi tendues, bras
  tendus au début) advanced tuck front lever + advanced tuck back
  lever: 4x4#4 (dos toujours courbé sur le back... mais front ok sur
  la forme)
#+END_EXAMPLE

2. Handstand

* <2019-07-09 Tue> Tue
  :PROPERTIES:
  :CUSTOM_ID: tue
  :END:

Passe-muraille :

- cat hang leg press 3x2
- cat hang pull-up 3x2
- cat hang shimmy 3x1
- top out
- 2 négatifs !!! Le problème est le placement des mains (que l'on ne
  travaille

pas en courant...) Handstand

* <2019-07-11 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-81
  :END:

#+BEGIN_EXAMPLE
  Burpee : 5-5 Skin the cat : 3-2 Compression 8-8-8 Straigth arms RTO
  : 21-20-16 Planch (sol + bras bien tendus cette fois !!) : 5-3-4
  Extension (lower-back) : 21-21-15 Muscle-up + L-sit :
  4#1-4#1-3#1-4#1 (dernière répétition pas terrible en forme) advanced
  tuck front lever + advanced tuck back lever: 5#5-6#3 (dos droit pour
  back lever)
#+END_EXAMPLE

* <2019-07-12 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-58
  :END:

2. Parkour

   Passe-muraille :

   - cat hang leg press 3x3
   - cat hang pull-up 3-3-2
   - cat hang shimmy 3x1
   - top out
   - 4 négatifs

* <2019-07-13 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-59
  :END:

2. Running

   20min à allure moyenne. 3x10 burpee pour "couper la course", à la
   Spartan race

* <2019-07-14 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-60
  :END:

2. Workout

   Compression 8-7-8 Straigth arms RTO : 22-20-17 Planch (sol + bras
   bien tendus cette fois !!) : 3x4 Extension (lower-back) : 3x22
   Muscle-up + L-sit : 4#1-4#1-4#1-3#1 (15! mais forme un peu limite)
   advanced tuck front lever + advanced tuck back lever: 4x6#5

* <2019-08-07 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-61
  :END:

2. Parkour

   Passe-muraille :

   - cat hang leg press 3x3
   - cat hang pull-up 3-3-2
   - cat hang shimmy 3x1
   - top out

3. Parkour

   - 3 négatifs

4. Parkour

* <2019-08-06 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-62
  :END:

* <2019-08-08 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-82
  :END:

#+BEGIN_EXAMPLE
  Compression 3x8 Straigth arms RTO : 17-17-17-10 Planche tucked
  (sol + bras bien tendus cette fois !!) : 2x7s et 3 tentatives sur
  anneaux Extension (lower-back) : 3x22 Muscle-up + L-sit :
  4#1-3#1-3#1-2#1 advanced tuck front lever + advanced tuck back
  lever: 6#6-8#8
#+END_EXAMPLE

* <2019-08-09 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-63
  :END:

2. Parkour

   Passe-muraille :

   - cat hang leg press 3x2
   - cat hang pull-up 3-3
   - cat hang shimmy 3x1
   - top out
   - 7 négatifs (!) dont 2 combiné à des top out

* <2019-08-12 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-83
  :END:

#+BEGIN_EXAMPLE
  Extension (lower-back) : 3x22 Muscle-up + L-sit : 3x3#1 advanced
  tuck front lever + advanced tuck back lever:
#+END_EXAMPLE

* <2019-08-14 Wed> Wed
  :PROPERTIES:
  :CUSTOM_ID: wed
  :END:

1. Running

   rythme constant, essayer d'accéler. 30s marche, 15s trot

* <2019-08-15 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-64
  :END:

2. Parkour

   Petite session technique avec Yvain 5 négatifs. Essayer en marchant
   avec changement de main

* <2019-08-16 Fri> Fri
  :PROPERTIES:
  :CUSTOM_ID: fri
  :END:

1. Running

* <2019-08-17 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-65
  :END:

* <2019-08-18 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-66
  :END:

2. Workout

   Compression : 3x8 Straigth arms RTO : 20-20-17 Planche tucked : 1-1-1
   (anneau) Extension (lower-back) : 3x22 Muscle-up + L-sit :
   3#1-3#2-3#2-3#2 (jambes pliées) Advanced tuck front lever + advanced
   tuck back lever: 10#8-10#8-11#9

* <2019-08-19 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-67
  :END:

* <2019-08-21 Wed> Wed
  :PROPERTIES:
  :CUSTOM_ID: wed-1
  :END:

1. Running

   Marche

* <2019-08-22 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-2
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang leg press 3-2-2
  -   cat hang shimmy 3x1
  -   top out
  -   3 négatifs
  -   knee-raises : 9 => presque !!
#+END_EXAMPLE

* <2019-08-23 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-84
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Straigth arms RTO : 22-22-20 Planche tucked : 4x1
  (commence à venir) Extension (lower-back) : 24-23-21 Muscle-up +
  L-sit : 4x3#3 Advanced tuck front lever + advanced tuck back lever:
  7#7-5#5-10#5 (dos courbé....)
#+END_EXAMPLE

* <2019-08-24 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-68
  :END:

2. Running

   Rythme moyen sans pauses (objectif = 20min)

* <2019-08-25 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-3
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang leg press 3x3
  -   cat hang pull-up 3x3
  -   cat hang shimmy 3x1
  -   top out 3
  -   5 négatifs
  -   knee raises : 5. On pose maintenant les mains à plat, mais pas
      encore le ventre...
#+END_EXAMPLE

* <2019-08-30 Fri> Fri
  :PROPERTIES:
  :CUSTOM_ID: fri-1
  :END:

1. Running

   rythme moyen sans pauses (objectif = 20min)

* <2019-09-01 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-69
  :END:

* <2019-09-02 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-85
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Straigth arms RTO : 3x20 Planche tucked : 3x1
  Extension (lower-back) : 3x22 Muscle-up + L-sit : 3x4#3 Advanced
  tuck front lever + advanced tuck back lever: 3x7#3
#+END_EXAMPLE

* <2019-09-03 Tue> Tue
  :PROPERTIES:
  :CUSTOM_ID: tue-1
  :END:

1. Running

   Tentative d'augmenter la fréquence

* <2019-09-05 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-4
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang leg press 3-2-2
  -   cat hang pull-up 3x3
  -   cat hang shimmy 3x1
  -   top out 3
  -   3 négatifs
  -   knee raises 8
#+END_EXAMPLE

* <2019-09-11 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-86
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat : 3 Planche tucked : 3x1 Extension
  (lower-back) : 3x20 Muscle-up + L-sit : 3x4#3 Advanced tuck front
  lever + advanced tuck back lever: 5#5-7#5-8#5 (attention au dos)
#+END_EXAMPLE

* <2019-09-15 Sun> Sun
  :PROPERTIES:
  :CUSTOM_ID: sun
  :END:

1. Running

   Medium

* <2019-09-22 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-87
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 German : 3-2 Active hang : 2min30 avec repos (max
  = 10s) Passive hang : 1min Extension (lower-back) : 3x22 Muscle-up +
  L-sit : 4#3-4#3-4#1 Advanced tuck front lever + advanced tuck back
  lever: 7#4-7#5-7#3 (dos rond....)
#+END_EXAMPLE

* <2019-09-25 Wed> Wed
  :PROPERTIES:
  :CUSTOM_ID: wed-2
  :END:

1. Running

   Medium

* <2019-09-30 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-88
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Straigth arms RTO : 2 Planche tucked : 3x1
  Extension (lower-back) : 3x22 Muscle-up + L-sit : 3x4#3 (sauf
  dernier, 1seconde en L-sit) Advanced tuck front lever + advanced
  tuck back lever: 7#5 5#5 5#5 (attention dos rond...)
#+END_EXAMPLE

* <2019-10-01 Tue> Tue
  :PROPERTIES:
  :CUSTOM_ID: tue-2
  :END:

1. Running

* <2019-10-03 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-5
  :END:

#+BEGIN_EXAMPLE
  Douleur IPP 4 donc brève séance : travail flux
#+END_EXAMPLE

* <2019-10-04 Fri> Fri
  :PROPERTIES:
  :CUSTOM_ID: fri-2
  :END:

1. Running

   Moyenne : 9min30 + 2min30

* <2019-10-07 Mon> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-6
  :END:

#+BEGIN_EXAMPLE
  Entorse au doigts toujours. Échauffement, equilibre et side vault du
  côté gauche OK.
#+END_EXAMPLE

2. Handstand

* <2019-10-08 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-89
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 German hang : 2-2-2 Planche tucked : 3x4 (au sol,
  jambes pliées, bras tendus) Extension (lower-back) : 3x23
  Muscle-up + L-sit : 4#3-2x4#{3-2-1} Advanced tuck front lever +
  advanced tuck back lever: 5#2 (dos rond :/)
#+END_EXAMPLE

* <2019-10-13 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-7
  :END:

#+BEGIN_EXAMPLE
  Underbar, equilibre
#+END_EXAMPLE

* <2019-10-14 Mon> Mon
  :PROPERTIES:
  :CUSTOM_ID: mon
  :END:

1. Running

   Medium

* <2019-10-15 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-70
  :END:

2. Workout

   Compression : 3x8 Skin the cat x3 Planche tucked : 4-3-3 au sol
   Extension (lower-back) : 3x22 Muscle-up + L-sit : 4#3-4#3-2
   (fixationo cassée...) Advanced tuck front lever + advanced tuck back
   lever: Front sur une branche d'arbre : 4s max sur 10 essais

* <2019-10-16 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-71
  :END:

* <2019-10-17 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-72
  :END:

2. Running

* <2019-10-18 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-8
  :END:

#+BEGIN_EXAMPLE
  Travail de l\'enchaînement
#+END_EXAMPLE

* <2019-10-19 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-90
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Straigth arms RTO : Planche tucked : 3x5 (sol,
  jambes pliées) Extension (lower-back) : 3x22 Muscle-up + L-sit :
  5#3-4#3-4#3 Advanced tuck front lever + advanced tuck back lever:
  5#3-4#3
#+END_EXAMPLE

* <2019-10-25 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-91
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat: 3-2-2 Planche tucked : 3x5 Extension
  (lower-back) : 3x22 Muscle-up + L-sit : 3x{4#3} Advanced tuck front
  lever + advanced tuck back lever: 5#5-5#5-5#4
#+END_EXAMPLE

* <2019-10-26 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-73
  :END:

* <2019-10-27 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-74
  :END:

* <2019-10-28 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-75
  :END:

2. Parkour

   Passe-muraille :

   - cat hang 3x10s
   - top out 3
   - cat hang pull-up 3x3
   - knee raises 3x2

* <2019-10-29 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-92
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat : 3x1 Planche tucked : 3x5 Extension
  (lower-back) : 3x22 Muscle-up + L-sit : 3x{4#3} Advanced tuck front
  lever + advanced tuck back lever: 3x{5#3} (dos toujours rond)
#+END_EXAMPLE

* <2019-10-07 Mon>
  :PROPERTIES:
  :CUSTOM_ID: section
  :END:

* <2019-11-11 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-76
  :END:

2. Workout

   Compression : 3x8 Skin the cat : 3-2-2 Planche tucked : 3x4 Extension
   (lower-back) : 3x22 Muscle-up + L-sit : 4#3-4#3-4#1 Advanced tuck
   front lever + advanced tuck back lever: 6#4-6#5-6#5 (travail dos
   droit... mais à confirmer)

* <2019-11-16 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-93
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat : 3x2 Planche tucked : 3x4 Extension
  (lower-back) : 3x22 Muscle-up + L-sit : 4#3-4#2-4#2 Advanced tuck
  front lever + advanced tuck back lever: 6#5 - 6#5-6#5 (dos droit si
  jambes pliées)
#+END_EXAMPLE

* <2019-11-18 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-94
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat : 0 Planche tucked : 3x6 Extension
  (lower-back) : 3x22 Muscle-up + L-sit : 6#3-6#3-3#2 (anneau mi
  pectoral => à travailler comme ça) Advanced tuck front lever +
  advanced tuck back lever: 3x7#5
#+END_EXAMPLE

* Weekly-routine goals
  :PROPERTIES:
  :CUSTOM_ID: weekly-routine
  :END:

1. Goals Workout

   #+BEGIN_EXAMPLE
     -   Long term : 5 muscle up, 2s levers complets
     -   Short-term : 1 muscle-up reussi avec anneau mi-pectoral, 10s
         front lever (jambes 90°) et 10s back (jambes pliées)
   #+END_EXAMPLE

   2. Running

      - Long term : 12km
      - Short-term : 1h de course

      [[https://www.reddit.com/r/running/comments/3bckeh/base_training_a_guide_to_your_foundation_to/]]

   3. Trampoline

      - Short-term : Front-flip propre, backflip

   4. Parkour

      - Long-term : wall-climb, 10 enchaînements
      - Short-term : wall-climb, 5 echaînements faciles, lazy vault sans
        pause

2. Routine routine

   Tous les jours : trampoline, handstand Lundi : sprints (10min
   échauffement, 6x sprints de 100m à 95% avec 2min de pauses) Mardi :
   parkour (technique, endurance) Mercredi : muscu haut du cours Jeudi :
   squats, course 30min tranquille Vendredi : parkour (muscu, technique)
   Samedi : muscu Dimanche : squats, course 1h

* <2019-11-21 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-77
  :END:

2. Parkour

   Lazy vault : continue travail Climb-up : toujours travail à l'arrêt
   mais avec élan sur un pied. Pas de négatifs réussis.

* <2019-11-22 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-78
  :END:

2. Running

* <2019-11-23 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-79
  :END:

#+BEGIN_EXAMPLE
  3x3s, 2x4s, 1x5s
#+END_EXAMPLE

* <2019-11-24 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-80
  :END:

2. Parkour

   Nouveau circuit : 2x2 cat hang shimmy, 2x3 pull-up, 3xnegatif, 2x2
   knee raises, 2xtop out en jumpant Aujourd'hui : 2 circuit + 0.2

* <2019-11-25 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-81
  :END:

#+BEGIN_EXAMPLE
  3x3 23x3
#+END_EXAMPLE

* <2019-11-26 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-82
  :END:

2. Running

* <2019-11-27 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-83
  :END:

#+BEGIN_EXAMPLE
  2-4-5-6-8
#+END_EXAMPLE

2. Workout

   Compression : 8-8-7 Skin the cat : 0 Planche tucked : 3x6 Extension
   (lower-back) : 3x22 Muscle-up + L-sit : 5#5-4#5-4#3 Advanced tuck
   front lever + advanced tuck back lever: 10#4 - 10#4 - 11#5 (2eme =
   dos droit mais bien surveiller)

* <2019-11-28 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-84
  :END:

#+BEGIN_EXAMPLE
  2-3x3-3x4-5
#+END_EXAMPLE

2. Parkour

   Musculation, surtout jambes : pull-up : 5x3 sur poteaux blancs
   (épais...) knee-shoulder : 3x4 Kipping : 3 tentatives Precision jump
   : 0 Stair jump : 1x10, 4 marches Squat : 2x25 Rail squat : 2 lunge :
   4x6+1 Step up : 3x10 (de chaque côté) Box jamp : 3x5 Rail plank : 3
   Rail push-up: 2 de chaque côté

* <2019-11-29 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-9
  :END:

#+BEGIN_EXAMPLE
  3 endurance (courts) 2 circuits passe-muraille :

  -   cat hang shimmy 2x2
  -   cat hang pull-up 4x2
  -   knee raises 3x2
#+END_EXAMPLE

* <2019-11-30 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-85
  :END:

#+BEGIN_EXAMPLE
  2+3x3-4-4-5
#+END_EXAMPLE

2. Handstand

* <2019-12-01 Sun> Sun
  :PROPERTIES:
  :CUSTOM_ID: sun-1
  :END:

1. Running

* <2019-12-02 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-86
  :END:

#+BEGIN_EXAMPLE
  3-2x4-2x5-8-10
#+END_EXAMPLE

* <2019-12-05 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-10
  :END:

#+BEGIN_EXAMPLE
  2x26 squats 2x10 burpee Tentative de circuits passe-muraille mais
  fatigue ++:

  -   cat hang shimmy 0
  -   cat hang pull-up 2x{2x2}
  -   knee raises 2x2
  -   négatifs 0
  -   assistance avec jambe : 6 essais
#+END_EXAMPLE

* <2019-12-06 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-87
  :END:

#+BEGIN_EXAMPLE
  2x2-2x3-5-2x8
#+END_EXAMPLE

2. Parkour

   2 circuits : 2 shimmy - 2 pull up - 3 leg press Négatifs avec le pied
   gauche en appui Pseudo climb-up en appui sur le sol. Même sur petits
   obstacles, non validé...

* <2019-12-07 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-88
  :END:

#+BEGIN_EXAMPLE
  2x2-2x3-2x4-5-11
#+END_EXAMPLE

2. Parkour

   30 squat 15 burpee Technique : 5 répétitions de simple, saut de chat,
   side vault (G + D, grosse difficultés à gauche, travail de 0) 3x3
   pull up, travail muscle-up avec balancé

* <2019-12-08 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-89
  :END:

#+BEGIN_EXAMPLE
  3x2-3-4-2x5
#+END_EXAMPLE

2. Running

* <2019-12-09 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-95
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Burpee : 10 Skin the cat : 3-2 Planche tucked :
  5-5-3 Extension (lower-back) : 3x22 Muscle-up + L-sit : 5#5 -
  4#4.8 - 4#5 - 4#4 - 3#4 Advanced tuck front lever + advanced tuck
  back lever: 10#5-10#5-10#5
#+END_EXAMPLE

* <2019-12-10 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-90
  :END:

#+BEGIN_EXAMPLE
  2x2-3-5-6-10
#+END_EXAMPLE

2. Parkour

   15 burpees 30 side squat 2 circuits où 1 circuit =

   - cat hang shimmy x2
   - top out x3 (sauf 2eme ciruit)
   - négatifs 3 avec 1 pied au sol
   - cat hang pull-up 2x3
   - knee raises 2x3
   - climb-up avec appui au sol Bilan : hauteur ok, maintenant poser le
     ventre (ou plutôt tenir la position)

3. L-sit

   3x2-3-3

* <2019-12-11 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-91
  :END:

#+BEGIN_EXAMPLE
  2-3-4-5-6-2x8
#+END_EXAMPLE

* <2019-12-10 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-92
  :END:

#+BEGIN_EXAMPLE
  2x2-3-5-6-10
#+END_EXAMPLE

2. Running

* <2019-12-12 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-93
  :END:

#+BEGIN_EXAMPLE
  3-4-2x5
#+END_EXAMPLE

2. L-sit

   4x4-2

* <2019-12-13 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-96
  :END:

#+BEGIN_EXAMPLE
  Compression : 3x8 Skin the cat : Tentative de forward roll = échec
  Planche tucked : 6-6-5 Extension (lower-back) : 3x23 Muscle-up +
  L-sit : 5#5-4#3-4#2-3#1 Advanced tuck front lever + advanced tuck
  back lever : 10#6 - 10#6 - 5#3
#+END_EXAMPLE

* <2019-12-14 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-94
  :END:

* <2019-12-14 Sat> Running
  :PROPERTIES:
  :CUSTOM_ID: running
  :END:

* <2019-12-14 Sat> L-sit
  :PROPERTIES:
  :CUSTOM_ID: l-sit
  :END:

* <2019-12-15 Sun>
  :PROPERTIES:
  :CUSTOM_ID: section-1
  :END:

1. Goals

   Motivation :

   - Not enough progress on the muscle-up => remove L-sit.
   - Isometrics : steven low recommadns dynamic moves for parkour =>
     stop back lever.

   Categories

   - Vertical pushing : handstand
   - Vertical pulling : muscle-up
   - Horizontal pushing : planche push-up
   - Horizontal pulling
   - Core : L-sit

2. Goals (short-term)

   5 tuck planche push-up (with good form) L-sit 30s (many sets as
   needed) 3x15 Tuck FL pull-ups

3. Routine (workout only)

   Pairs :

   - Planche (dynamic) : 3x5 pseudo planche push-up, 3x5 tuck L-sit
     push-up 3x5 Tuck Front-lever pull-up
   - 3x5 Muscle-up (with eccentrics !!!) 3x5 Pistols
   - L-sit

   Compression 3x10s

* <2019-12-15 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-11
  :END:

#+BEGIN_EXAMPLE
  2 circuits :

  -   cat hang hold 2x10
  -   négatifs 3
  -   cat hang pull-up 2x3 (sauf 2eme passage, 1x3)
  -   knee raises 2x3
  -   leg assisted : 2x3 (sauf 2eme passage, 1x3) Bilan : peu de
      progressif, fatigue
#+END_EXAMPLE

* <2019-12-16 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-95
  :END:

#+BEGIN_EXAMPLE
  3x2-4x3-4-5
#+END_EXAMPLE

2. Workout

   Muscle-up : 5-4 (dont 3 vrais !!) - 4 (dont 3 vrais) Pistols (each
   side): 5 (Léger appui 1 main, 75% de la descente) - 2x5 (95% mais
   plus difficile jambe gauche) Push-up tucked planche : 3x2 (bras a
   priori tendu) Pull-up front lever tucked 3x3 (attention position du
   bassin !!) L-sit 0 Compression :0 Extension (lower-back) :0

* <2019-12-18 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-96
  :END:

#+BEGIN_EXAMPLE
  5-5-7
#+END_EXAMPLE

2. Parkour

   2 circuits :

   - cat hang hold 2x10
   - négatifs 4
   - cat hang pull-up 2x3
   - knee raises 2x3
   - leg assisted : 2x3 Bilan : fatiguee

* <2019-12-19 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-97
  :END:

#+BEGIN_EXAMPLE
  2x2-2x3-2x5-6
#+END_EXAMPLE

2. Workout

   Muscle-up : 3 vrais, 2 aidés - 3 vrais, 2 aidés - 3 vrais, 2 aidés
   Pistols (each side): 5 (sans appui , 80% amplitude) - 5 avec appui -
   5 avec appui à 100% Push-up tucked planche : 2x3(avec pauses) - 2.5
   Pull-up front lever tucked : 3x3 L-sit 3x4 Compression : 3x9
   Extension (lower-back) : 3x22

3. Running

* <2020-01-02 Thu> Thu
  :PROPERTIES:
  :CUSTOM_ID: thu
  :END:

1. Running

2. L-sit

   4-3 (mains vers le côté)-2-2-2

3. Handstand

   3x2-4x3-4-5

* <2020-01-03 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-98
  :END:

#+BEGIN_EXAMPLE
  2x2-3-2x4-7-8
#+END_EXAMPLE

2. Workout

   Lazy vault à gauche en progression Wall turn ok à gauche ! Wall climb
   : knee-up x3 de chaque côté x2. Essai de diminuer la difficulté :

   - jumping OK mais négatif à travailler
   - aide d'une jambe : échec, à retravailler.

* <2020-01-07 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-99
  :END:

#+BEGIN_EXAMPLE
  StW 45-40-35 BtW 3x2-3x3-4
#+END_EXAMPLE

2. Running

* <2020-01-08 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-100
  :END:

#+BEGIN_EXAMPLE
  StW 40-39 BtW 3-4-5-6-11
#+END_EXAMPLE

2. Workout

   Warm-up : 5 burpee Muscle-up : 3 faux, 4 vrais avec 3 pauses - 5
   vrais avec 1 pause (anneaux plus haut : 2cm au-dessus du mamelon)-4
   vrais Pistols (assisted) : 3x5 Front-lever row (tucked) : 3x4 Planche
   tucked push-up: 4 avec pauses - 4 (dont 2 consécutifs) - 4 (dont 2
   consécutifs) Extension (lower-back) : 3x22 Compression : 3x10 L-sit
   (jambes presque tendues) : 6-6-5

* <2020-01-09 Thu>
  :PROPERTIES:
  :CUSTOM_ID: section-2
  :END:

1. L-sit

   2x10

2. Handstand

   StW 45-25-30 BtW 3x3-5-22 (!!!)

3. L-sit

   3x10

4. Running

   (nouveau record de vitesse mais 2 pauses aux feux)

* <2020-01-11 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-101
  :END:

#+BEGIN_EXAMPLE
  StW 42-35-35 BtW 2-3x3-4-5-6
#+END_EXAMPLE

2. L-sit

   2x10

* <2020-01-13 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-102
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-25
#+END_EXAMPLE

2. Workout

   Demi-session Muscle-up : 7-6-3 (vrais ! et anneau mi-épaule !)
   Pistols (assisted) : 3x5

* <2020-01-18 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-103
  :END:

#+BEGIN_EXAMPLE
  StW 40-37-32 BtW 2-3-4-7-8
#+END_EXAMPLE

2. Workout

   Warm-up : Muscle-up : 5-3-3 (vrais, 1cm au dessus de l'épaule)
   Pistols (assisted) : 3x5 Front-lever row (tucked) : 3x3 Planche
   tucked push-up: 2+1+1 - 2-2 - 1 Extension (lower-back) : 3x22
   Compression : 3x10 L-sit: 3x3

* <2020-01-19 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-104
  :END:

#+BEGIN_EXAMPLE
  StW 40-40-30 BtW 2x2-3-2x4-5-13
#+END_EXAMPLE

* <2020-01-20 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-105
  :END:

#+BEGIN_EXAMPLE
  StW 33-28-28 BtW 2-3x4-5
#+END_EXAMPLE

2. Parkour

   Échauffement + circuit

* <2020-01-21 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-106
  :END:

#+BEGIN_EXAMPLE
  StW 35-32-25
#+END_EXAMPLE

2. Workout

   Warm-up : 5 burpee Muscle-up : 3-4-3 (anneau mi-cou) Pistols
   (assisted) : 3x5 Front-lever row (tucked) : »x3 Planche tucked
   push-up: 2+2-2+2-2+# Extension (lower-back) : 3x22 Compression :
   10-9-10

* <2020-01-30 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-107
  :END:

#+BEGIN_EXAMPLE
  StW 30-30-25
#+END_EXAMPLE

2. Workout

   Warm-up : 5 burpee Muscle-up : 4-3-3 (anneau milieu coup) Pistols
   (assisted) : 3x5 Front-lever row (tucked) : 3x3 Planche tucked
   push-up: 3+2 - 1-2-2 + 3-1 Extension (lower-back) : 3x22 Compression
   : 3x10 L-sit : 3s

* <2020-01-31 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-12
  :END:

Workout :

#+BEGIN_EXAMPLE
  -   crawl (front + back) x2
  -   knee-raises : 3x15 (each side)
  -   lunges : 3x10
  -   pull-up: 5+3 - 3+3 - 3+2
  -   dips : 3x6
#+END_EXAMPLE

* <2020-02-01 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-108
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-30 BtW 2x2-3-4-5-8
#+END_EXAMPLE

2. Running

* <2020-02-02 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-109
  :END:

#+BEGIN_EXAMPLE
  StW 35-30-35 BtW 4-5-6
#+END_EXAMPLE

2. Workout

   - Muscle-up : 3-3-2 Pistols (assisted) : 3x5 Front-lever row
     (tucked) :: 3x3 Planche tucked push-up: 3+2 - 3+1 - 3+1 Extension
     (lower-back)
     3x22 Compression : 3x10 L-sit: 3x2

* <2020-02-15 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-110
  :END:

#+BEGIN_EXAMPLE
  StW 45-32-33 BtW 3x2-2x4-2x5
#+END_EXAMPLE

* <2020-02-16 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-111
  :END:

#+BEGIN_EXAMPLE
  StW 48-38-40 BtW 2x2-2x3-4-3x5
#+END_EXAMPLE

2. Workout

   Warm-up : 3-2 skin the cat Muscle-up : 0-2-3 Pistols (assisted) : 3x5
   Front-lever row (tucked) : 3x3 Planche tucked push-up: 3+2 - 3+2 -
   1+1+1 Extension (lower-back) : 3x22 Compression : 3x10 L-sit : 2-2-1

* <2020-02-17 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-112
  :END:

#+BEGIN_EXAMPLE
  StW 50 (scissors) -30 (close to wall)-35 BtW 2-3-4-2x5-10
#+END_EXAMPLE

2. Running

* <2020-02-18 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-113
  :END:

#+BEGIN_EXAMPLE
  StW 43-40-25-25 BtW 2x2 - 3x3 - 4-5
#+END_EXAMPLE

* <2020-02-20 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-114
  :END:

#+BEGIN_EXAMPLE
  StW 47-32-32 BtW 4x3-4-2x5-6
#+END_EXAMPLE

2. Workout

   Warm-up : 2 skin the cat Muscle-up : 0-2-4 (milieu du cou à
   travailler...) Pistols (assisted) : 3x5 Front-lever row (tucked) :
   3+2 - 3+2 -2+1 Planche tucked push-up: 3x3 Extension (lower-back) :
   22 Compression : L-sit : 2

* <2020-02-21 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-115
  :END:

#+BEGIN_EXAMPLE
  StW 45-33-32 BtW 5x3-5-6-9
#+END_EXAMPLE

* <2020-02-22 Sat>
  :PROPERTIES:
  :CUSTOM_ID: section-3
  :END:

1. Running

* <2020-02-23 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-116
  :END:

#+BEGIN_EXAMPLE
  StW 43-37-33 BtW 3x2-2x3-2x4-5
#+END_EXAMPLE

2. Workout

   Warm-up : 3 skin the cat Muscle-up : 3-6-3 (on revient aux épaules
   pour travailler le grip => ne pas mettre sur l'ulna...) Pistols
   (assisted) : 3x5 Front-lever row (tucked) : 4-3-3 Planche tucked
   push-up: 3+2 - 3+2 - 2+1 Extension (lower-back) : 3x22 Compression :
   3x10 (jambes enfin tendues !) L-sit : 3-2-2

* <2020-02-25 Tue> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-13
  :END:

#+BEGIN_EXAMPLE
  Circuit : par tranches de 3 exercices

  -   crawl back + front x3
  -   knee drive 3x15
  -   dips 3x5
  -   pull-up 3x5
  -   lunges 3x10
#+END_EXAMPLE

* <2020-02-26 Wed>
  :PROPERTIES:
  :CUSTOM_ID: section-4
  :END:

1. Running

* <2020-02-27 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-117
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-30 BtW 3x2-3x3-5-2x7
#+END_EXAMPLE

2. Workout

   Warm-up : Muscle-up : 3 - 2 - 3 - 2 (en intérieur, position "assise"
   mais pieds en l'air) Pistols (assisted) : 4-2-3 (appui sur radiateur,
   plus dur qu'avec les anneaux !) Front-lever row (tucked) : 4-4-3
   Planche tucked push-up: 3x{3+2+1} Extension (lower-back) : 3x22
   Compression : 3x10 L-sit: 3x2

* <2020-02-29 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-118
  :END:

#+BEGIN_EXAMPLE
  StW 35-32-28 BtW 3x2-4x3-4-2x8
#+END_EXAMPLE

* <2020-03-01 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-119
  :END:

#+BEGIN_EXAMPLE
  StW 35-30-30 BtW 2x2-2x3-4-2x5-6
#+END_EXAMPLE

2. Parkour

   2x5 pompes 3x4 dips 3x16 lunges 3x17 knee raises 3x3 pull -up
   (conditions météo difficiles)

* <2020-03-02 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-120
  :END:

#+BEGIN_EXAMPLE
  StW 32-31-25 BtW 2x3-4x4-6
#+END_EXAMPLE

* <2020-03-03 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-121
  :END:

#+BEGIN_EXAMPLE
  StW 37-33-25 BtW 3x2-2x3-2x4
#+END_EXAMPLE

2. Workout

   Warm-up : 2 skin the cat, 3 burpee Muscle-up : 3-5-3 (épaule) Pistols
   (assisted) : 5-3-3 (plus dur avec un point d'appui bas) Front-lever
   row (tucked) : 4-4-3 Planche tucked push-up: 4+3 - 1+2 - 2+1
   Extension (lower-back) : 22 Compression : 10 L-sit: 3

* <2020-03-04 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-122
  :END:

#+BEGIN_EXAMPLE
  StW 42-30-24 BtW 2-3-4x4-5-7
#+END_EXAMPLE

2. Parkour

   Passe-muraille : 2 circuits avec 1 circuit =

   - cat hang shimmy 8s x2
   - top out 3 x2
   - cat hang pull-up 3x2
   - knee raises 4 x2
   - pied au sol 4

* <2020-03-05 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-123
  :END:

#+BEGIN_EXAMPLE
  StW 32-28-28 BtW 3x3-3x4
#+END_EXAMPLE

2. Running

* <2020-03-06 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-97
  :END:

#+BEGIN_EXAMPLE
  (NB fatigue++) Warm-up : 4 burpee Muscle-up : 3-4-3 Pistols
  (assisted) : 5-4-4 Front-lever row (tucked) : 5-3-3 Planche tucked
  push-up: 2+2+1 - 3+2 - 2+1 Extension (lower-back) : 3x22 Compression
  : 3x10 L-sit : 3x3
#+END_EXAMPLE

* <2020-03-07 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-124
  :END:

#+BEGIN_EXAMPLE
  StW 30-27-31 BtW 2x3-3x4-5-2x6-8
#+END_EXAMPLE

* <2020-03-09 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-125
  :END:

#+BEGIN_EXAMPLE
  StW 41-35-30 BtW 3x2-3x3-3x4-6
#+END_EXAMPLE

2. Parkour

   échauffement 2x5 burpees (dos droit pour pompes) endurance : 5
   mouvements x 3 knee-drive : 4 de chaque côté

* <2020-03-10 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-126
  :END:

#+BEGIN_EXAMPLE
  StW 20-20-18 BtW
#+END_EXAMPLE

2. Workout

   Warm-up : 2x5 burpees, 2 skin the cat Muscle-up : 3x4 Pistols
   (assisted) : 3x5 Front-lever row (tucked) : 4-4 Planche tucked
   push-up: 2+2 - 3+2 - 2+2 Extension (lower-back) : 3x22 Compression :
   3x10 L-sit: 3-3-2

* <2020-03-12 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-127
  :END:

#+BEGIN_EXAMPLE
  StW 35-23-23 BtW 3x2-3-5-7
#+END_EXAMPLE

2. Workout

   Warm-up : Skin the cat 2-1 et Burpee 2x6 Muscle-up : 3x4 Pistols
   (assisted) : 5-4-4 Front-lever row (tucked) : 4-4 Planche tucked
   push-up: 3+2 - 3+2 Extension (lower-back) : 3x22 Compression : 3x10
   L-sit : 2-2

* <2020-03-14 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-128
  :END:

#+BEGIN_EXAMPLE
  StW 35-28 BtW 2-2x3-2-4-5-6
#+END_EXAMPLE

* <2020-03-15 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-14
  :END:

#+BEGIN_EXAMPLE
  Kong large : ok mais seulement milieu de la rampe. Endurance : 4
  obstacle x 3
#+END_EXAMPLE

* <2020-03-16 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-129
  :END:

#+BEGIN_EXAMPLE
  StW 37-37-30 BtW 3x2-5-2x6
#+END_EXAMPLE

2. Workout

   Warm-up : Trampoline Muscle-up : 5-4-4 Pistols (assisted) : 3x4
   Front-lever row (tucked) : 3x4 Planche tucked push-up: 2+2 - 3+2 -
   3+2 Extension (lower-back) : 3x22 Compression : 3x10 L-sit : 3-2-2

* <2020-03-18 Wed> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-15
  :END:

#+BEGIN_EXAMPLE
  Lazy vault x5 Underbar x5 Kong : presque ok au 1/3 latéral Knee
  raise x4 de chaque côté
#+END_EXAMPLE

* <2020-03-19 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-130
  :END:

#+BEGIN_EXAMPLE
  StW 32-33-27 BtW 6x3-4-2x5
#+END_EXAMPLE

2. Running

* <2020-03-20 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-131
  :END:

#+BEGIN_EXAMPLE
  StW 23-23 (on économise le poignet) BtW 2-5x3-3x4-2x5
#+END_EXAMPLE

2. Workout

   Warm-up : Trampoline Muscle-up : 1-3-3 (difficile ajourd'hui) Pistols
   (assisted) : 3x3 (plus difficile si on descend à 90% seulement)
   Front-lever row (tucked) : 3x4 Planche tucked push-up: 3+3 - 3+2 -
   2+2+1 Extension (lower-back) : 3x4 Compression : 3x10 L-sit : 3x3

* <2020-03-21 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-132
  :END:

#+BEGIN_EXAMPLE
  StW 32-10 BtW 3x2-5x3-2-4-5-8
#+END_EXAMPLE

2. Parkour

   Kong : plateau Knee -up : too tired Underbar : need another place to
   train

* <2020-03-22 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-133
  :END:

#+BEGIN_EXAMPLE
  StW 40-35-35 BtW 3x2-4x3-6
#+END_EXAMPLE

2. Running

* <2020-03-23 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-134
  :END:

#+BEGIN_EXAMPLE
  StW 15-30-35 (fesses serrées !) BtW 3x3-4-2x5
#+END_EXAMPLE

2. Workout

   Warm-up : Trampoline Muscle-up : 4-4-3 Pistols (assisted) : 3-3(-1) -
   3 Front-lever row (tucked) : 5-3-3 Planche tucked push-up: 4+2 -
   4+1 - 3+1 Extension (lower-back) : 3x22 Compression : 3x10 L-sit :
   3-3-4

* <2020-03-24 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-135
  :END:

#+BEGIN_EXAMPLE
  StW 37-30 BtW 2x3-2x5-7
#+END_EXAMPLE

* <2020-03-25 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-136
  :END:

#+BEGIN_EXAMPLE
  StW 42-30-25 BtW 2x3-4-2x5-8
#+END_EXAMPLE

* <2020-03-26 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-137
  :END:

#+BEGIN_EXAMPLE
  StW 43-32-30 BtW 4x3-4-2x5+6
#+END_EXAMPLE

2. Workout

   Warm-up : Trampoline Muscle-up : 1 (+4 avec appui) - 2(+4) - 1(+4) !
   Bien retravailler la descente Pistols (assisted) : 3x3 (bien
   travailler la forme) Front-lever row (tucked) : 3-4 Planche tucked
   push-up: 2+1 - 3+2 - 3+2 Extension (lower-back) : 2x2 Compression :
   2x9 L-sit : 2x3

* <2020-03-28 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-138
  :END:

#+BEGIN_EXAMPLE
  StW 37-42-30 BtW 2x2-4x3-2x4-2x5-10
#+END_EXAMPLE

* <2020-03-29 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-139
  :END:

#+BEGIN_EXAMPLE
  StW 40-35-32 BtW 4x2-3x3-4-2x5
#+END_EXAMPLE

2. Parkour

   Kong, à retravailler Reverse passe muraille, idem Lazy vault à
   continuer Demi-tour ok, à maintenir

* <2020-03-30 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-140
  :END:

#+BEGIN_EXAMPLE
  StW 45-30-25 BtW 3x3-3x4-5
#+END_EXAMPLE

2. L-sit

   7-7-6 (jambes pliées)

3. Workout

   Warm-up : RTO 2x15, trampoline, skin the cat x2 Muscle-up : 1(+4) -
   3(+2) - 3(+1) Pistols (assisted) : 4-4 (dont 1 sans appui à jambe
   gauche !) - 5D+2G (sans appui à G) Front-lever row (tucked) : 5-4-5
   Planche tucked push-up: 3+3 - 4+1 - 3+2 Extension (lower-back) :
   Compression :

* <2020-03-31 Tue>
  :PROPERTIES:
  :CUSTOM_ID: section-5
  :END:

1. Running

* <2020-04-02 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-141
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-25 BtW 5x2-3x3-4-7
#+END_EXAMPLE

2. L-sit

   7-7

* <2020-04-03 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-16
  :END:

#+BEGIN_EXAMPLE
  Léger progres en lazy vault D. Constant à gauche Régression en kong
#+END_EXAMPLE

* <2020-04-04 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-98
  :END:

Warm-up : RTO 17x2-10, trampoline, skin the cat x2 Muscle-up : 1(+4
assisté) - 1(+4) sans toucher le sol Pistols (assisted) : 3x5 (appui)
Front-lever row (tucked) : 5-5-3 Planche tucked push-up: 4+4 - 4+3 - 3+1
Extension (lower-back) : 3x22 Compression : 3x9 L-sit : 3x2

* <2020-04-05 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-142
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-30 BtW 3x2-3x3-2x4
#+END_EXAMPLE

2. L-sit

   3x7

3. Parkour

Workout (sans pause sur une série, 20m ?) Quadrupédie avant + sprint : 5
puis 2 min pause Quadrupédie arrière + sprint : 3 puis 2 min pause Kong
avant : 3 puis 2 min pause Kong arrière : 1

* <2020-04-07 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-143
  :END:

#+BEGIN_EXAMPLE
  StW 25 BtW 2x2-2x3-2x4-6
#+END_EXAMPLE

2. L-sit

   7-6-7

3. Workout

   Warm-up : RTO 20-20-7 Muscle-up : 0(+5 avec appui bout du pied) -
   2(+3) - 1(+4) Pistols (assisted) : 3x5 Front-lever row (tucked) :
   5-5-5 Planche tucked push-up: 4+3 - 4+1 - 3+1 Extension (lower-back)
   : 3x22 Compression : 10-9-10

* <2020-04-09 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-17
  :END:

#+BEGIN_EXAMPLE
  Stride : à peaufiner

  Passe-muraille :

  -   négatifs 3-3
  -   pull-up 3 chaque chote
  -   top out 4
  -   cat hold
  -   cat move sideway
  -   knee up 4
  -   with help
#+END_EXAMPLE

* <2020-04-10 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-144
  :END:

#+BEGIN_EXAMPLE
  StW 37-32-33 BtW 5x3-3x4-2x5
#+END_EXAMPLE

2. L-sit

   3x7

* <2020-04-11 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-99
  :END:

#+BEGIN_EXAMPLE
  NB: début de torticolis Warm-up : RTO : 6x10 Burpee : 4 Muscle-up :
  0(+5) - 1(+4) - 1(+3) Pistols (assisted) : 3x5 Front-lever row
  (tucked) : 5-4-3 Planche tucked push-up: 4+2 - 3+2 - 4+1 Extension
  (lower-back) : 2x22 Compression : 9-10 L-sit : 3-4
#+END_EXAMPLE

* <2020-04-13 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-145
  :END:

#+BEGIN_EXAMPLE
  StW 37-37-36 BtW 2x2-2x3-4
#+END_EXAMPLE

2. L-sit

   3x7

3. Parkour

   Burpee 7+4+5 Side vault : légère progression (trottine à droite,
   contact à gauche...) Kong : 2 validés Demi tour ok

* <2020-04-15 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-100
  :END:

Warm-up : RTO 20-10-10 (dos droit = dur++) Muscle-up : 0(+5) - 1(+4) -
2(+3) Pistols (assisted) : 3x5 Front-lever row (tucked) : 4-4 Planche
tucked push-up: 2+2+1 - 3+2 Extension (lower-back) : 2x22 Compression :
3x10

* <2020-04-16 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-146
  :END:

#+BEGIN_EXAMPLE
  StW 20-37-30 BtW 4x4-2x5-7
#+END_EXAMPLE

2. Parkour

   Passe-muraille :

   - cat hang 8s de chaque côté x2
   - cat hang shimmy 3 de chaque côté
   - top out 4 (dont 3 combiné avec un négatif = fatiguant++)
   - négatifs
   - cat hang leg press 3 de chaque côté
   - cat hang pull-up 3 de chaque côté
   - knee raises 4 de chaque côté x2
   - wall climb avec appui au sol : 4 x 2

* <2020-04-17 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-147
  :END:

#+BEGIN_EXAMPLE
  StW 41-31-33 BtW 2-2x3-2x4-2x5
#+END_EXAMPLE

2. L-sit

   3x7

3. Running

* <2020-04-18 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-148
  :END:

#+BEGIN_EXAMPLE
  StW 37-30-31 (quasiment main au bas du mur mais difficile !) BtW
  2x2-4x3-3x4-5-8
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 3x10 Muscle-up : 2(+3) - 4 - 2(+2) Attention à ne pas
   tricher et garder les bras le plus tendus Pistols (assisted) : 3x5
   Front-lever row (tucked) : 5-5-4 Planche tucked push-up: 4+4 - 4+2 -
   5+1 Extension (lower-back) : Compression : L-sit :

* <2020-04-19 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-149
  :END:

#+BEGIN_EXAMPLE
  StW 30-30-25 BtW 3x3-2x4-2x7-8
#+END_EXAMPLE

* <2020-04-21 Tue>
  :PROPERTIES:
  :CUSTOM_ID: section-6
  :END:

1. Running

* <2020-04-22 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-150
  :END:

#+BEGIN_EXAMPLE
  StW 35-28-26 BtW 2-2x3-4x4-2x5
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 3x10, burpee 3x5 Muscle-up : 5-6-4 (dont 3 répétitions
   enchaînées ! Bras pas assez tendu mais impression de franchir un
   plateau) Pistols (assisted) : 3x4 Front-lever row (tucked) : 2x4
   Planche tucked push-up: 4+2 - 4+2 Extension (lower-back) : 3x22
   Compression : 2x9 L-sit :

* <2020-04-23 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-18
  :END:

#+BEGIN_EXAMPLE
  Side vault : à retravailler Kong vault : enfin la sensation d\'un
  kong sur une barrière ! désormais, travailler la distance
  Passe-muraille : 2x4 knee drive, 10 negative
#+END_EXAMPLE

* <2020-04-24 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-151
  :END:

#+BEGIN_EXAMPLE
  StW 36-27-27 BtW 7x3-3x4
#+END_EXAMPLE

2. Running

* <2020-04-25 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-101
  :END:

Warm-up : Burpee 2x6, RTO 4x10 Muscle-up : 3x3 (négatifs complets !
Jambes tendues mais bras encore pliés) Pistols (assisted) : 3x5
Front-lever row (tucked) : 5-5 Planche tucked push-up: 5+2 - 3+1 - 3+1+1
Extension (lower-back) : 3x22 Compression : 3x10 L-sit : 3x3

* <2020-04-26 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-152
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-30 BtW 2x2-2x3-4-5-3x6
#+END_EXAMPLE

2. Parkour

   Passe-muraille :

   - cat hang shimmy : 3 moves
   - top out : 3
   - negative : 2x4 (assisted)
   - cat hang leg press : 3 (each side)
   - cat hang pull-up 3 (each side)
   - knee raises : 4 (each side)
   - assisted (1 foot down) 2x4

3. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 30s
   Front split : 30s Frog pose (dynamic) : 30s Horse stance : 15s-15s
   Standing pancake : 1min

* <2020-04-27 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-153
  :END:

#+BEGIN_EXAMPLE
  StW 40-30-25 BtW 2-2x3-4x4-4x6
#+END_EXAMPLE

2. Running

3. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 0 Low lunge : 30s
   Front split : 2x30s Frog pose (dynamic) : 1min Horse stance : 2x30s
   Standing pancake : 2x1min

* <2020-04-28 Tue>
  :PROPERTIES:
  :CUSTOM_ID: section-7
  :END:

1. Splits

   Standing splits (2-5s + rest) : 2x30 Wall calf : Low lunge : 2x30s
   Front split : 1min Frog pose (dynamic) : 1min Horse stance : 2x30s
   Standing pancake : 1min

* <2020-04-29 Wed>
  :PROPERTIES:
  :CUSTOM_ID: section-8
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 40s Standing pancake :
   1min10 Front split : 1min

2. Parkour

   Kong workout : 20m + 20m sprint + 40m marche 5 quadrupédie 5 reverse
   kong 5 quadrupédie à l'enverse

* <2020-04-30 Thu>
  :PROPERTIES:
  :CUSTOM_ID: section-9
  :END:

1. Running

* <2020-05-01 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-154
  :END:

#+BEGIN_EXAMPLE
  StW 35-30-30 BtW 4x2-2x3-4-5-6-7
#+END_EXAMPLE

* <2020-05-02 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-155
  :END:

#+BEGIN_EXAMPLE
  StW 40-32-30 BtW 5x2-2x3-2x4-7
#+END_EXAMPLE

2. Workout

   Warm-up : 4x10 RTO Muscle-up : 0(+4 avec bras plus tendus) - 1+(3) -
   2+(2 mais négatifs avec appui Pistols (assisted) : 3-2-3 (appui avec
   barre mais difficile de se relever) Front-lever row (tucked) : 4-4
   Planche tucked push-up: 1+1+1 - 3+2 Extension (lower-back) : 3x22
   Compression : 3x10 L-sit : 3x3

3. Splits

   Standing splits (2-5s + rest) : 40s Wall calf : 10s Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 5+10-10-5 Standing pancake
   : 1min25 Front split : 1min

* <2020-05-03 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-156
  :END:

#+BEGIN_EXAMPLE
  StW 32-29-29 BtW 3x3-3x4-2x5
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : Low lunge : 50s Frog
   pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

3. Parkour

   15 burpee avec 1 pause Kong : 3 validés Passe-muraille :

   - 3x5 négatifs (avec appui
   - 4 kip up
   - avec appui : 5

   ! Je pense avoir compris comment poser le pied !

* <2020-05-04 Mon>
  :PROPERTIES:
  :CUSTOM_ID: section-10
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 20s Low lunge : 1min
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

* <2020-05-05 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-157
  :END:

#+BEGIN_EXAMPLE
  StW 43-37-33
#+END_EXAMPLE

2. Workout

   Warm-up : trampoline Muscle-up : 4 (en tendant de plus en plus les
   bras : mieux. Et descendant au maximum) - 1 (douleur)-4 Pistols
   (assisted) : 3x4 Front-lever row (tucked) : 5-6-6 (Dos un peu rond
   mais on valide quand même => niveau supérieur !) Planche tucked
   push-up: 6+3 (!!) - 6+2 - 6+2 (On peut passer au niveau supérieur !)
   Extension (lower-back) : 3x22 Compression : 3x10 L-sit : 3x3

3. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 0 Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

4. Notes

   Augmenter la difficulté pour FL row : commencer à tendre les jambes
   Idem pour le planche push-up

* <2020-05-06 Wed> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-19
  :END:

#+BEGIN_EXAMPLE
  fatigue++ Passe-muraille :

  -   cat hang shimmy (each side) : 10s
  -   top out (each side) : 3
  -   negative : 3x5
  -   cat hang leg press (each side) : 3
  -   cat hang pull-up (each side) : 4
  -   knee raises (each side) : 2x4
#+END_EXAMPLE

* <2020-05-07 Thu>
  :PROPERTIES:
  :CUSTOM_ID: section-11
  :END:

1. Running

* <2020-05-08 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-158
  :END:

#+BEGIN_EXAMPLE
  StW BtW 2x2-2x3
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : Wall calf : 15s Low lunge : Frog pose
   (dynamic) : Horse stance : Standing pancake : 1min Front split :

3. Handstand

   StW 35-35-32 BtW 2x2-4x3-4x4

4. Workout

   Warm-up : 5x10s RTO Muscle-up (négatifs lents) : 7-5-5 Pistols
   (assisted) : 5-5-3 Front-lever row (advanced tuck) : 0-1-1 Planche
   push-up (advanced tuck : 0-0-0 (que des négatifs)

* <2020-05-09 Sat>
  :PROPERTIES:
  :CUSTOM_ID: section-12
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 10s Low lunge : 50s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 45s
   Front split : 45s

2. Handstand

   StW 32-32-32-31 BtW 2x2-4x3-3x4-2x5

* <2020-05-10 Sun> Sunday
  :PROPERTIES:
  :CUSTOM_ID: sunday
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15 Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

2. Parkour

   Side vault, endurance training (low intensity)

* <2020-05-11 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-159
  :END:

#+BEGIN_EXAMPLE
  StW 35-35-32 BtW
#+END_EXAMPLE

2. Workout

   Warm-up : 20-20-19 RTO Muscle-up (négatifs lents) : 7-5-4 Pistols
   (assisted) : 3x5 Front-lever row (advanced tuck) : 0-0-0 Planche
   push-up (advanced tuck): 0-0-0 Extension (lower-back) : 3x14
   (dynamique) Compression : 3x10 L-sit : 3-1-2

* <2020-05-12 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-160
  :END:

#+BEGIN_EXAMPLE
  StW 35-38-30 BtW 5x2-3x3-3x4
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

3. Running

* <2020-05-13 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-161
  :END:

#+BEGIN_EXAMPLE
  StW 47-32-33 BtW 3x3-6-10
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 1min

* <2020-05-16 Sat> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-20
  :END:

#+BEGIN_EXAMPLE
  Quadrupédie avant + sprint x10
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : Frog
   pose (dynamic) : 30s Horse stance : 20s Standing pancake : 30s Front
   split :

3. Handstand

   StW 27-36-37-27 BtW 5x2-3-2x4-5

* <2020-05-17 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-21
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 10s
  -   top out (each side) : 5 (avec 1 négatif à chaque fois)
  -   negative : 2x5
  -   cat hang leg press (each side) : 3
  -   cat hang pull-up (each side) : 4
  -   knee raises (each side) : 4
  -   avec appui : 2.5 x 4 (2 côtés)

  Progression sur le passe-muraille avec appui. Bien pousser avec les
  jambes
#+END_EXAMPLE

* <2020-05-18 Mon>
  :PROPERTIES:
  :CUSTOM_ID: section-13
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15 Low lunge : 45s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 20s
   Front split : 30s

2. Running

   Les sprint précédents étaient plus longs que prévus... Essayé de
   forcer plus aujourd'hui sur la distance mais diminution des distances
   à la moitié

3. Handstand

   StW 37-27-26 BtW 2x2-3x3

* <2020-05-19 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-102
  :END:

Warm-up : RTO 17x3 Muscle-up (négatifs lents) : 5 Pistols (assisted) :
5-5-4 Front-lever row (advanced tuck) : 3x2 tentatives. À la 3eme dos
droit mais difficile. Pas d'amplitude encore (1cm max) Planche push-up
(advanced tuck): 3x2 négatifs Extension (lower-back) : 3x22 (dynamique)
Compression : 3x10 L-sit : 2-3-2

2. Splits

* <2020-05-20 Wed> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-22
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 3 déplacements
  -   top out (each side) : 3
  -   negative : 3x5
  -   cat hang leg press (each side) : 3
  -   cat hang pull-up (each side) : 4
  -   knee raises (each side) : 4
  -   avec appui : 4
#+END_EXAMPLE

2. Handstand

   Freestanding : 12 essais

3. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 10s Low lunge : 30s
   Frog pose (dynamic) : 1min Horse stance : 30s Standing pancake : 1min
   Front split : 30s

* <2020-05-21 Thu>
  :PROPERTIES:
  :CUSTOM_ID: section-14
  :END:

1. Running

   *

* <2020-05-22 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-162
  :END:

#+BEGIN_EXAMPLE
  StW BtW 2-3x3-4
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 30s
   Frog pose (dynamic) : 40s Horse stance : 30s Standing pancake : 30
   Front split : 35

3. Handstand

   StW 40-35-32 BtW 2-3-5x4-2x5

4. Workout

   Warm-up : RTO 17-15-10-9 Muscle-up (négatifs lents) : 3x5 Pistols
   (assisted) : 3x5 Front-lever row (advanced tuck) : 3x3 tentatives.
   dos droit mais 1mm amplitude Planche push-up (advanced tuck): 3x2
   négatifs Extension (lower-back) : 3x22 Compression : 3x10

* <2020-05-23 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-163
  :END:

#+BEGIN_EXAMPLE
  StW 30-27-25 BtW 3x3-4-2x5-6
#+END_EXAMPLE

* <2020-05-25 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-164
  :END:

#+BEGIN_EXAMPLE
  StW 39-33-27-25 BtW 3x2-3-4-2x6
#+END_EXAMPLE

* <2020-05-27 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-165
  :END:

#+BEGIN_EXAMPLE
  StW 32-30-25
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 17-7 (mais combiné au muscle-up))) Muscle-up (négatifs
   lents) : 3x5 Pistols (assisted) : 5-4-3 Front-lever row (advanced
   tuck) : 3x3 tentative (1cm max mais dos droit) Planche push-up
   (advanced tuck): 3-2-2 négatifs Extension (lower-back) : 2x22
   Compression : 2x10 L-sit : 3x4 (échauffement)

* <2020-05-28 Thu>
  :PROPERTIES:
  :CUSTOM_ID: section-15
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40s
   Frog pose (dynamic) : 1min Horse stance : Standing pancake : 1min
   Front split : 55s

2. Handstand

   StW 35-35-25 BtW 7x3-2x4-5

3. Running

* <2020-05-29 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-23
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang : 10
  -   top out (each side) : 5 (un seul côté)
  -   negative : 2x5 (toujours avec appui)
  -   cat hang leg press (each side) : 4
  -   cat hang pull-up (each side) : 3
  -   knee raises (each side) : 4
  -   avec appui : 4
#+END_EXAMPLE

2. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40S
   Frog pose (dynamic) : 1min Horse stance : 15s Standing pancake : 40s
   Front split : 40s

* <2020-05-31 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-166
  :END:

#+BEGIN_EXAMPLE
  StW 39-30-25-25 BtW 3x2-3-3x4-5
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 18-18-15 Muscle-up (négatifs lents) : 3x5 Pistols
   (assisted) : 3x5 Front-lever row (advanced tuck) : 3x3 tentatives
   (fesses un peu hautes) Planche push-up (advanced tuck): 3x2 négatifs
   Extension (lower-back) : 3x22 Compression : 3x10

* <2020-06-01 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-167
  :END:

#+BEGIN_EXAMPLE
  StW 38-28-24 (mains plus prèss = max, avec pieds qui décollent du
  mur légèrement => semble bien aider !!) BtW 4x3-2x4-6-9
#+END_EXAMPLE

2. Running

* <2020-06-03 Wed>
  :PROPERTIES:
  :CUSTOM_ID: section-16
  :END:

1. Splits

   Standing splits (2-5s + rest) : 30s Wall calf : 15s Low lunge : 40S
   Frog pose (dynamic) : 1min Horse stance : 15s Standing pancake : 40s
   Front split : 40s

2. Handstand

   StW 37-39-32-28-24 (main au max) BtW 4-5-6-7

* <2020-06-05 Fri>
  :PROPERTIES:
  :CUSTOM_ID: section-17
  :END:

1. Running

* <2020-06-06 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-168
  :END:

#+BEGIN_EXAMPLE
  StW 40-37-27 BtW 2-3x3-4-2x5-6
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 19-15-15 Muscle-up (négatifs lents) : 3x5 Pistols
   (assisted) : 3x5 Front-lever row (advanced tuck) : 3 x 3 tentatives
   (dos droit, 1cm amplitude max) Planche push-up (advanced tuck): 3x3
   tentatives en négatif Extension (lower-back) : 3x22 Compression :
   3x10 L-sit : 2-3-2

* <2020-06-08 Mon> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-24
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang (each side) : 10s
  -   top out : 5
  -   negative : 3x5
  -   cat hang leg press (each side) : 5
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 4
  -   assisted : 4
#+END_EXAMPLE

* <2020-06-09 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-169
  :END:

#+BEGIN_EXAMPLE
  StW 35-30-30-23 (en quasi équilibre !)
#+END_EXAMPLE

* <2020-06-11 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-170
  :END:

#+BEGIN_EXAMPLE
  StW 31-37-25 BtW 3x2-3-2x4-2x6
#+END_EXAMPLE

2. Handstand

   StW 33-23-21

* <2020-06-13 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-171
  :END:

#+BEGIN_EXAMPLE
  StW 10-10-26-23 BtW 5x3-2x5
#+END_EXAMPLE

* <2020-06-14 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-172
  :END:

#+BEGIN_EXAMPLE
  StW 32-25 BtW
#+END_EXAMPLE

* <2020-06-17 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-173
  :END:

#+BEGIN_EXAMPLE
  StW

  -   29-25-34
  -   23-32-26

  BtW 2-6x3-2x4
#+END_EXAMPLE

2. Workout

   Warm-up : RTO 23-21 Muscle-up (négatifs lents) : 3x5 Pistols
   (assisted) : 3x5 Front-lever row (advanced tuck) : 3 tentatives
   Planche push-up (advanced tuck): 3 tentatives Extension (lower-back)
   : 3x22 Compression : 3x10 L-sit : 4x4

* <2020-06-18 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-174
  :END:

#+BEGIN_EXAMPLE
  StW 20-33-32 BtW 5x3-4-2x5-6
#+END_EXAMPLE

* <2020-06-19 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-175
  :END:

#+BEGIN_EXAMPLE
  StW 48-35-31 BtW 2x3-3x4-5-7
#+END_EXAMPLE

* <2020-06-20 Sat> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-25
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang hold (each side) : 10s
  -   top out assisted (each side) : 2x4 (en mettant le coude pour
      retenir le mouvement)
  -   negative : 3x5
  -   cat hang leg press (each side) : 4 (jambes bien tendues !)
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 4 (sans pause !)
#+END_EXAMPLE

* <2020-06-21 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-176
  :END:

#+BEGIN_EXAMPLE
  StW : 3 répétitions filéme : ok BtW : 6 essai filmé : non aligné !!
  Après 3 essais, aligné mais ne tient pas la position
#+END_EXAMPLE

2. Workout

   RTO-up : 2x23 L-sit : 3x4 Muscle-up (négatifs lents) : 5-5-4
   (transitiont très lente !) Pistols (assisted) : 3x5 (sensation de
   plus contrôler) Extension (lower-back) : 3x22 Front-lever row
   (advanced tuck) : 3x{2(+1)} tentatives (attention à ne pas bouger que
   les fesses... pas de triche) Planche push-up (advanced tuck): 4-3-3
   tentatives Norwegian curls: 3x3 (15° ? douloureux...) Compression :
   9-10

* <2020-06-22 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-177
  :END:

#+BEGIN_EXAMPLE
  StW 40-37-25 BtW 5 (travailler la posture en filmant depuis hier)
#+END_EXAMPLE

2. Running

* <2020-06-23 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-178
  :END:

#+BEGIN_EXAMPLE
  StW 45-39-33) BtW 4x2-4x3-2x5
#+END_EXAMPLE

* <2020-06-24 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-179
  :END:

#+BEGIN_EXAMPLE
  StW 46-32-35-30 (jambes pas assez droites et pieds trop en avant !
  travailler plus près du mur) BtW 2x2-2x3-4-6-8
#+END_EXAMPLE

* <2020-06-25 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-180
  :END:

#+BEGIN_EXAMPLE
  StW 47-41-25 BtW 2-2x4-5-6
#+END_EXAMPLE

* <2020-06-26 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-103
  :END:

#+BEGIN_EXAMPLE
  RTO-up : 20-19-17 L-sit : 3x4 Muscle-up (négatifs lents) : 5-5-4 (ok
  pour le false grip ! descendre plus bas) Pistols (assisted) : 3x5
  Extension (lower-back) : 3x22 Front-lever row (advanced tuck) : 3
  essais (1er = 1cm) Planche push-up (advanced tuck): 3 essais avec
  début de remontée Norwegian curls: 4 Compression : 9
#+END_EXAMPLE

2. Handstand

   StW 37-32-31

* <2020-06-27 Sat> Tricks
  :PROPERTIES:
  :CUSTOM_ID: tricks
  :END:

Goals

#+BEGIN_EXAMPLE
  -   front flip propre sur trampoline
  -   front flip sur matelas
  -   back flip sur trampoline
  -   front handspring
  -   kip up (utile pour back handstring)
#+END_EXAMPLE

Tricks

#+BEGIN_EXAMPLE
  Front flip plutôt propre sur trampoline Kip up : essai méthode de
  pigme mais pas encore ça Back flip : encore latéral. Selon Thibault,
  rester désaxé pour le moment mais travailler plus le tuck Front
  handscsrip : handstand + roll pour le moment
#+END_EXAMPLE

* <2020-06-28 Sun> Tricks
  :PROPERTIES:
  :CUSTOM_ID: tricks-1
  :END:

#+BEGIN_EXAMPLE
  Kip up Back flip Front handspring
#+END_EXAMPLE

* <2020-06-29 Mon> Tricks
  :PROPERTIES:
  :CUSTOM_ID: tricks-2
  :END:

#+BEGIN_EXAMPLE
  Kip up : 2 réussis Back flip Front flip : ok à mi-hauteur Front
  handspring : toujours pas
#+END_EXAMPLE

* <2020-06-29 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-181
  :END:

#+BEGIN_EXAMPLE
  StW 45-45-38 BtW 2-3x3-3x4-6-7
#+END_EXAMPLE

* <2020-06-30 Tue> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-26
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 3
  -   top out (un côté) : 5
  -   assisted : 7-2
  -   negative : 2x5
  -   cat hang leg press (each side) : 4
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 4
#+END_EXAMPLE

2. Tricks

   Kip up : 4 réussis Front handspring : toujours pas

* <2020-07-01 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-182
  :END:

#+BEGIN_EXAMPLE
  StW 55 (!) - 45 BtW 2-2x3-5-7
#+END_EXAMPLE

2. Running

3. Tricks

   Kip up : aucun réussi Back flip : 3 essais mais trop fatigué Front
   flip : 0 Front handspring : : avec un peu d'élan, atterissage sur les
   fesses (attention au dos)

* <2020-07-02 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-183
  :END:

#+BEGIN_EXAMPLE
  StW 50-37-32 BtW 4-4x5-9
#+END_EXAMPLE

* <2020-07-03 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-104
  :END:

#+BEGIN_EXAMPLE
  RTO : 23-23-17 (!) L-sit : 3x5 (!) Muscle-up (négatifs lents) :
  4-5-4 (descente trop rapide...) Pistols (assisted) : 3x4 (jambe
  tendue = pluse difficile) Extension (lower-back) : 22-30 Front-lever
  row (advanced tuck) : 3x3 tentatives Planche push-up (advanced
  tuck): 3x3 tentatives Norwegian curls: 3-4-4 Compression : 3x10
#+END_EXAMPLE

* <2020-07-04 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-184
  :END:

#+BEGIN_EXAMPLE
  StW 45-36-27 BtW plusieurs tentatives non chronométrées
#+END_EXAMPLE

* <2020-07-06 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-185
  :END:

#+BEGIN_EXAMPLE
  StW 47-35-30 BtW 3 essais filmés
#+END_EXAMPLE

2. Tricks

   Kip up : 5, semble bon la moitié du temps ! Back flip : Trop sur le
   côté... Front flip : OK assez bas avec peu d'élan ! Front handspring
   : : au mieux, on arrive sur les fesses

3. Running

* <2020-07-07 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-186
  :END:

#+BEGIN_EXAMPLE
  StW 40-30 BtW 2 essais filmés
#+END_EXAMPLE

2. Parkour

   Passe-muraille :

   - cat hang shimmy (each side) : 4
   - top out (each side) : 5
   - negative : 3x5
   - cat hang leg press (each side) : 4
   - cat hang pull-up (each side) : 5
   - knee raises (each side) : 4
   - assited : 4 dont 3 avec passage complet en haut du mur !!!!

3. Tricks

   Kip up : travail avec moins d'élan Back flip : oui Front flip : oui,
   avec peu de hauteur Front handspring : : travail transition
   équilibre - pont

* <2020-07-08 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-105
  :END:

#+BEGIN_EXAMPLE
  RTO-up : 27-20 Muscle-up (négatifs lents) : 3x5 (essai de non
  négatifs mais bof sur 2 essais) Pistols (assisted) : 3x5 Extension
  (lower-back) : 3x22 Front-lever row (advanced tuck) : 3x3 (qq mm en
  plus ?) Planche push-up (advanced tuck): 3x3 Norwegian curls: 3-4-3
  Compression : 3x10
#+END_EXAMPLE

2. Tricks

   Kip up : 5 Back flip : 3 Front flip : 0 Front handspring : : travail
   lent

* <2020-07-09 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-187
  :END:

#+BEGIN_EXAMPLE
  StW 34-15-30 BtW 3 essais
#+END_EXAMPLE

* <2020-07-10 Fri>
  :PROPERTIES:
  :CUSTOM_ID: section-18
  :END:

1. Running

2. Tricks

   - Kip up : contine travail avec moins d'élan Back flip : 0 Front
     flip :: 0 Front handspring : : j'atteris en position accroupie.
     Pousser plus avec les bras

* <2020-07-13 Mon>
  :PROPERTIES:
  :CUSTOM_ID: section-19
  :END:

1. Running

* <2020-07-14 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-188
  :END:

#+BEGIN_EXAMPLE
  StW 25-32 BtW 3 essais filmés
#+END_EXAMPLE

2. Tricks

   Kip up : 4 Back flip : 3 Front flip : 0 Front handspring : : à
   l'arrêt et avec élan, pas de progrès

3. Parkour

   Passe-muraille :

   - cat hang shimmy (each side) : 3
   - top out (each side) : 5
   - negative : 2x5
   - cat hang leg press (each side) : 4
   - cat hang pull-up (each side) : 5
   - knee raises (each side) :
   - assisted : 4+2 avec arrivée sur le mur !

* <2020-07-15 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-189
  :END:

#+BEGIN_EXAMPLE
  StW 20-30 (mains encore plus proches) BtW 0
#+END_EXAMPLE

2. Tricks

   Kip up : 5 Back flip : 5 Front flip : 0 Front handspring : : 5

* <2020-07-16 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-106
  :END:

#+BEGIN_EXAMPLE
  RTO-up : 18-8-13 L-sit : 3x4 Muscle-up (négatifs lents) : 5-5-4 + 1
  positif Pistols (assisted) : 3 (pied gauche **sans** aide) / 3
  (droite avec aide) - 1/3 - 2/3 Extension (lower-back) : 3x22s
  Front-lever row (advanced tuck) : 2+2 - 3+1 - 3 essais Planche
  push-up (advanced tuck): 3x2 Norwegian curls: 4-4-3 Compression :
  3x10
#+END_EXAMPLE

* <2020-07-17 Fri> Running
  :PROPERTIES:
  :CUSTOM_ID: running-1
  :END:

* <2020-07-17 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-190
  :END:

#+BEGIN_EXAMPLE
  StW BtW 3 essais de 2
#+END_EXAMPLE

* <2020-07-17 Fri> Tricks
  :PROPERTIES:
  :CUSTOM_ID: tricks-3
  :END:

#+BEGIN_EXAMPLE
  Kip up : 4 Back flip : 3 Front flip : 0 Front handspring : : 3
#+END_EXAMPLE

* <2020-07-18 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-191
  :END:

#+BEGIN_EXAMPLE
  StW 33-32-19 BtW 4 essais
#+END_EXAMPLE

2. Tricks

   Kip up : 5 Back flip : 9 Front flip : Front handspring : :

3. Parkour

   Passe-muraille :

   - cat hang shimmy (each side) : 4
   - top out (each side) : 5
   - negative : 2x5
   - cat hang leg press (each side) : 4
   - cat hang pull-up (each side) : 5
   - knee raises (each side) : 4
   - assisted : 2+2 (mais avec un seul bras)

* <2020-07-19 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-107
  :END:

#+BEGIN_EXAMPLE
  RTO-up : 2x17 L-sit : 5-4 Essai de circuit : notation = 1ere passe
  \# 2eme passe \# 3eme passe Muscle-up (négatifs lents) : 3 \# 5 \# 5
  Pistols (assisted) : 3x5 \# 3x5 (avec aide) Extension (lower-back) :
  22 \# 22 Front-lever row (advanced tuck) : 2 \# 3 Planche push-up
  (advanced tuck): 2 \# 3 Norwegian curls: 3 \# 3 Compression : 10
#+END_EXAMPLE

* <2020-07-21 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-192
  :END:

#+BEGIN_EXAMPLE
  StW BtW 4 essais
#+END_EXAMPLE

2. Tricks

   Kip up : 5 Back flip : 5 Front flip : Front handspring : :

3. Running

* <2020-07-22 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-193
  :END:

#+BEGIN_EXAMPLE
  StW 40-35-25 BtW
#+END_EXAMPLE

2. Workout

   RTO-up : 20-19 L-sit : 5-4 Muscle-up (montée avec appui (genou pliés,
   anneau hauteur cour + négatifs lents en descente) : 2-3-3 Pistols
   (assisted) : 3#4 - 3#4 - 3#4 (non assité à gauche, assisté à droite
   mais presque bon) Extension (lower-back) : 3x22 (bien contracter et
   mouvement d'arcs de cercle) Front-lever row (advanced tuck) : 3x3
   tentatives Planche push-up (advanced tuck): 3x3 tentatives Norwegian
   curls: 3x4 Compression : 3x10

* <2020-07-26 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-108
  :END:

Warm-up : 25-21 Muscle-up (négatifs lents) : 3x3 (normaux, jambes
tendues inclinées au sol) Pistols (assisted) : 3x5 (assisté) Front-lever
row (advanced tuck) : 3x3 (3 répétitions identiques) Planche push-up
(advanced tuck): 3x3 Extension (lower-back) : 3x22 Compression : 9-10-9
L-sit : 2x5

* <2020-08-09 Sun> Sunday
  :PROPERTIES:
  :CUSTOM_ID: sunday-1
  :END:

1. Running

* <2020-08-10 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-109
  :END:

#+BEGIN_EXAMPLE
  RTO-up : 2x17 (douleur en essayant de mettre les épaules en arrière
  ...) Muscle-up : 3-4 (courbatures dans les pectoraux...) Pistols
  (assisted) : 2x5 Extension (lower-back) : 2x21
#+END_EXAMPLE

* <2020-08-11 Tue> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-27
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 3
  -   top out (each side) : 5
  -   negative : 3
  -   cat hang leg press (each side) : 3
  -   cat hang pull-up (each side) : 4
  -   knee raises (each side) : 4
  -   assisted : 2-2 (!)
#+END_EXAMPLE

* <2020-08-12 Wed>
  :PROPERTIES:
  :CUSTOM_ID: section-20
  :END:

1. Running

* <2020-08-15 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-110
  :END:

#+BEGIN_EXAMPLE
  Demi-sessions RTO-up : 11-13 L-sit : 2x4 Muscle-up (négatifs lents)
  : 4-4-2 Pistols (assisted) : 3x5 Compression : 3x9
#+END_EXAMPLE

* <2020-08-17 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-194
  :END:

#+BEGIN_EXAMPLE
  BtW 5 essais
#+END_EXAMPLE

2. Workout

   RTO-up : 18-20 L-sit : 6-5 (nouveau record !) Muscle-up (négatifs
   lents) : Pistols (assisted) : Extension (lower-back) : 3x22
   Front-lever row (advanced tuck) : 3+1 - 2+1 - 2 (presque la moitié !,
   peut-être parce que demi-session ?) Planche push-up (advanced tuck):
   3x3 tentatives, début remontée Norwegian curls: 3x4

3. Running

* <2020-08-17 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-195
  :END:

#+BEGIN_EXAMPLE
  StW BtW 3 essais
#+END_EXAMPLE

2. Running

* <2020-08-18 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-196
  :END:

#+BEGIN_EXAMPLE
  StW BtW 3 essais
#+END_EXAMPLE

2. Parkour

   Passe-muraille :

   - cat hang shimmy (each side) : 4 (nouveau record)
   - top out (each side) : 5
   - negative :
   - cat hang leg press (each side) : 5
   - cat hang pull-up (each side) : 5
   - knee raises (each side) : 4
   - assisted : 5 (nouveau record !)
   - non-assisted : 2 (!!!!! enfin !!!!!! Mais trop de brute force, plus
     s'aider des pieds)

* <2020-08-20 Thu> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-197
  :END:

#+BEGIN_EXAMPLE
  StW BtW 4 essais
#+END_EXAMPLE

2. Workout

   RTO : 13-15 Skin-the-cat : 2 L-sit : 2x5 Muscle-up : 3-3-2 (quasiment
   sans pause sur une série, le temps de reprendre la bonne position)
   Pistols (assisted) : 6/2 - 6/6 - 5/3 (gauche/droit) avec appui fort)
   Extension (lower-back) : 3x22 Front-lever row (advanced tuck) : 2+1 -
   2+1 (plus difficile en fin de session...) Planche push-up (advanced
   tuck): 2x3 tentatives (idem) Norwegian curls: 2x4 Compression : 2x9

* <2020-08-30 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-198
  :END:

#+BEGIN_EXAMPLE
  StW 37-19 BtW 2 tentatives
#+END_EXAMPLE

* <2020-08-30 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-111
  :END:

#+BEGIN_EXAMPLE
  RTO : 25/17 Skin-the-cat : 2 L-sit : 2x5 Muscle-up : 3x3 (plus
  facile avec les pieds sous les anneaux) Pistols (assisted) : 3x6
  (assisté) Extension (lower-back) : 3x22 Front-lever row (advanced
  tuck) : 2+1 - 2 - 2 Planche push-up (advanced tuck): 3x3 Norwegian
  curls: 3x4 Compression : 9-10-10
#+END_EXAMPLE

* <2020-09-19 Sat>
  :PROPERTIES:
  :CUSTOM_ID: section-21
  :END:

1. Running

* <2020-09-22 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-112
  :END:

#+BEGIN_EXAMPLE
  Reprise très tranquille RTO : ok Skin-the-cat : ok Muscle-up : 2x2
  avec appui sur jambe + impulsion bras Pistols (assisted) : 3#3 en
  moyenne Extension (lower-back) : ok Front-lever row (advanced tuck)
  : 80% Planche push-up (advanced tuck): 70% Norwegian curls: ok
  Compression : ok
#+END_EXAMPLE

* <2020-09-23 Wed>
  :PROPERTIES:
  :CUSTOM_ID: section-22
  :END:

1. Running

* <2020-09-25 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-113
  :END:

#+BEGIN_EXAMPLE
  RTO : 13-15 Skin-the-cat : 2+1.5 L-sit : 2 tentatives sur anneaux
  Muscle-up : 2-4-2 (descente avec appui !) Pistols (assisted) : 3x4
  Extension (lower-back) : 3x22 (bras tendus) Front-lever row
  (advanced tuck) : 3-2-2 tentaives Planche push-up (advanced tuck):
  2-2 (+1 tentative straddle mais échec) Norwegian curls: 3x3
  Compression : 3x10
#+END_EXAMPLE

* <2020-09-26 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-199
  :END:

#+BEGIN_EXAMPLE
  StW 35-24 BtW 1-2x2-3x3-5
#+END_EXAMPLE

* <2020-09-27 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-200
  :END:

#+BEGIN_EXAMPLE
  StW 35-20 BtW 2x3-4-2x5-6-10
#+END_EXAMPLE

2. Goals : éviter les plateaux

   - Front lever pull-up : descendre d'un niveau (tucked) et augmenter
     jusque 3x15
   - Planche push-up : descendre d'un niveau (tucked) et sur barres
     parallèles
   - L-sit: viser 60min au total

3. Workout

   RTO : 18+18 Skin-the-cat : 2.5 normaux L-sit : 3x8 + 5 (rings +
   tucked) Muscle-up : 2-3-3 (seul la première série a des négatifs en
   plus) Pistols (assisted) : 4-4-3 Extension (lower-back) : 3x22
   Front-lever row (tuck) : 7+2 - 5+2 - 4+3 Planche push-up (tuck): 0
   (douleur à l'essai sur les barres) Norwegian curls: 3x3 Compression :
   3x10

* <2020-09-29 Tue> ning
  :PROPERTIES:
  :CUSTOM_ID: ning
  :END:

* <2020-09-30 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-201
  :END:

#+BEGIN_EXAMPLE
  StW 30-23 BtW 5x2-3-4-5-2x6
#+END_EXAMPLE

* <2020-10-01 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-114
  :END:

#+BEGIN_EXAMPLE
  RTO : 2x18 Skin-the-cat : 2 L-sit : 3x6+3 Muscle-up : 3x3 (+
  négatifs !) Pistols (assisted) : 3x4 Extension (lower-back) : 3x22
  Front-lever row (tuck) : 3+3 - 3+3 + 3-2 Planche push-up (tuck):
  3x{2+1+1} Norwegian curls: 3x3 Compression : 3x10
#+END_EXAMPLE

* <2020-10-03 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-202
  :END:

#+BEGIN_EXAMPLE
  StW 40-18 BtW 2-3x3-4
#+END_EXAMPLE

* <2020-10-04 Sun> Sunday
  :PROPERTIES:
  :CUSTOM_ID: sunday-2
  :END:

1. Running

* <2020-10-05 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-115
  :END:

#+BEGIN_EXAMPLE
  RTO : 20-17-17 Skin-the-cat : 2-1 L-sit : 3x6 Muscle-up : 3x3
  (négatifs) Pistols (assisted) : 3x5 Extension (lower-back) : 3x22
  Front-lever row (tuck) : 3x{5+3) Planche push-up (tuck): 3x{3+2}
  Norwegian curls: 3x3 Compression : 3x10
#+END_EXAMPLE

* <2020-10-06 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-203
  :END:

#+BEGIN_EXAMPLE
  StW 35-25 BtW 3x3-5
#+END_EXAMPLE

* <2020-10-07 Wed> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-28
  :END:

#+BEGIN_EXAMPLE
  Side vault : travailler fluidité (G) + sans pied (D) Passe-muraille
  : 3 avec appui et 5 sans appuis !!! -\> Travailler maintenant de
  l\'autre côté (pente) et en mettant les 2 bras
#+END_EXAMPLE

* <2020-10-10 Sat> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-29
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 5
  -   top out (each side) : 5
  -   cat hang leg press (each side) : 3
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 2
  -   4 assisted
  -   3 non assisted

  Continuer le travail (assisté + non-asisstié)
#+END_EXAMPLE

* <2020-10-13 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-204
  :END:

#+BEGIN_EXAMPLE
  StW 32-25-22 BtW 2x2-3x3-5-6
#+END_EXAMPLE

* <2020-10-14 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-116
  :END:

#+BEGIN_EXAMPLE
  Skin-the-cat : 2+1 L-sit : 4x6s Muscle-up : 2-4-4 (sans descente
  sauf les 2 premiers) Pistols (assisted) : 3x4 Extension (lower-back)
  : 3x22 Front-lever row (tuck) : 2x{5+3} - 4+4 Planche push-up
  (tuck): 2+2+1 - 3+2+1 - 3+271 Norwegian curls: 3x4 Compression :
  3x10
#+END_EXAMPLE

* <2020-10-16 Fri> Running
  :PROPERTIES:
  :CUSTOM_ID: running-2
  :END:

* <2020-10-18 Sun> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-30
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 3
  -   top out (each side) : 5
  -   cat hang leg press (each side) : 4
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 4
  -   avec appui : 5 pour bien saisir le mouvement et du côté gauche
  -   sans appui : 3
#+END_EXAMPLE

* <2020-10-19 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-205
  :END:

#+BEGIN_EXAMPLE
  StW 15-20 BtW 2x2-3x4-7-8-11 (!)
#+END_EXAMPLE

* <2020-10-19 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-117
  :END:

#+BEGIN_EXAMPLE
  (Anneau un peu plus écartés) Skin-the-cat : 1.5-1.5 L-sit :
  6-6-3-3-5-5-2-2 Muscle-up : 3(+3neg) - 4(+2neg) - 4(+2neg) Pistols
  (assisted) : 3x5 Extension (lower-back) : 3x22 Front-lever row
  (tuck) : 8+2 - 5+2 Planche push-up (tuck): 4+3+1 - 4+2 Norwegian
  curls: 2-4 Compression : 10-9 (forcant plus)
#+END_EXAMPLE

* <2020-10-20 Tue> Running
  :PROPERTIES:
  :CUSTOM_ID: running-3
  :END:

* <2020-10-22 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-31
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang shimmy (each side) : 3(0 autre côté)
  -   top out (each side) : 4
  -   negative :
  -   cat hang leg press (each side) :
  -   cat hang pull-up (each side) : 3
  -   knee raises (each side) : 4
  -   assisted : 6 (trop glissant pour normal)
#+END_EXAMPLE

* <2020-10-24 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-118
  :END:

#+BEGIN_EXAMPLE
  RTO : Skin-the-cat : 2.5 L-sit : 4x7 Muscle-up : 3-4-3 (bras plus
  tendus et négatifs à chaque fois !) Pistols (assisted) : 3x5
  Extension (lower-back) : 3x22 Front-lever row (tuck) : 5+2 - 1+2 -
  4+2 Planche push-up (tuck): 3+2+1 - 2+1 - 3+1 Norwegian curls: 3x3
  Compression : 3x10
#+END_EXAMPLE

* <2020-11-06 Fri> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-119
  :END:

#+BEGIN_EXAMPLE
  RTO : Skin-the-cat : 2 L-sit : 2 essais Muscle-up : 2-4-4 Pistols
  (assisted) : 4-5-4 Extension (lower-back) : 3x22 Front-lever row
  (tuck) : 2+2 - 4+2 - 3+2 Planche push-up (tuck): 3+2 - 2+2 - 2+2
  Norwegian curls: 3x3 Compression : 9-10-9
#+END_EXAMPLE

* <2021-08-27 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-206
  :END:

#+BEGIN_EXAMPLE
  StW 44-42-25 BtW 2-2x3-4
#+END_EXAMPLE

* <2021-08-28 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-207
  :END:

#+BEGIN_EXAMPLE
  StW 13-2)-33-39-42 BtW 3-2x8
#+END_EXAMPLE

2. L-sit (half-tucked)

   11s-11-11

* <2021-08-29 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-120
  :END:

#+BEGIN_EXAMPLE
  RTO : 7-13 Skin-the-cat : 2-2 Forward roll : 3 essais L-sit : 5-7
  Muscle-up L-sit : 2x1-4x1 (dernier sans négatif) - 4x1 (idem)
  Pistols (assisted) : 3x1 - 3x1 -3x1 Extension (lower-back) : 3x22
  Front-lever row (tuck) : 2x2 - 3+1 - 3+2 Planche on rings (tuck):
  2x4 - 4+3+3 - 6 - 3 essais de pompes ! Norwegian curls: 4-3
  (crampe)-3 Compression : 10-5-7
#+END_EXAMPLE

* <2021-09-02 Thu> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-32
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille : 10 Technique
#+END_EXAMPLE

* <2021-09-04 Sat> Running
  :PROPERTIES:
  :CUSTOM_ID: running-4
  :END:

* <2021-09-04 Sat> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-208
  :END:

#+BEGIN_EXAMPLE
  StW 51-41 BtW
#+END_EXAMPLE

* <2021-09-04 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-121
  :END:

#+BEGIN_EXAMPLE
  RTO : 22-21 Skin-the-cat : 2-1 L-sit : 9-8 Muscle-up L-sit : 3x1 -
  4x1 - 5x1 (!) Pistols (assisted) : 3x3 Extension (lower-back) : 3x22
  Front-lever row (tuck) : 3+2 - 3+2 - 3+2 Planche on rings (tuck +
  push-up): 3x1 + 2x1 + 2x1 Norwegian curls: 3x4 Compression : 3x9
#+END_EXAMPLE

* <2021-09-05 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-209
  :END:

#+BEGIN_EXAMPLE
  StW 53-38
#+END_EXAMPLE

* <2021-09-05 Sun> Running
  :PROPERTIES:
  :CUSTOM_ID: running-5
  :END:

* <2021-09-07 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-122
  :END:

#+BEGIN_EXAMPLE
  Routine: haut: 2x1 + 1muscle-up et 1 pompe en tucked planche bas: 4
  pistols, 22 extensions, 10 compressions, 4 curls

  haut: 2 bas: idem haut: 2 bas: idem
#+END_EXAMPLE

* <2021-09-09 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-123
  :END:

#+BEGIN_EXAMPLE
  RTO : 23-23 Skin-the-cat : 2-1 L-sit : 9-9 Muscle-up L-sit :
  1+1.99+2 (!!) - 2(!!)+1 - 2(!!)+1 Pistols (assisted) : 3x4 Extension
  (lower-back) : 3x22 Front-lever row (tuck) : Planche on rings
  (tuck): Norwegian curls: Compression :
#+END_EXAMPLE

* <2021-09-11 Sat> Running
  :PROPERTIES:
  :CUSTOM_ID: running-6
  :END:

* <2021-09-13 Mon> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-33
  :END:

#+BEGIN_EXAMPLE
  Passe-murail avec appui glissant Underbar
#+END_EXAMPLE

* <2021-09-13 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-124
  :END:

#+BEGIN_EXAMPLE
  Routine: haut = 2x1 bas : 22 extension - 3 curl - 3 pistols haut 3x1
  (!) bas : 22 extension - 3 curl - 3 pistols haut 2x1 bas : 22
  extension - 3 curl - 3 pistols
#+END_EXAMPLE

* <2021-09-15 Wed> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-210
  :END:

#+BEGIN_EXAMPLE
  StW 15-42-10 BtW
#+END_EXAMPLE

* <2021-09-16 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-125
  :END:

#+BEGIN_EXAMPLE
  RTO : 28-18 Skin-the-cat : 2 L-sit : 9-7 Muscle-up L-sit : 3x1 -
  2+2x1 - 2+2x1 Pistols (assisted) : 3x4 Extension (lower-back) : 3x22
  Front-lever row (tuck) : 3+3+ - 3+3 - 3+2 Planche on rings (tuck):
  2+2 - 2+2 - 2+2 Norwegian curls: 3x4 Compression : 3x10
#+END_EXAMPLE

* <2021-10-01 Fri> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-211
  :END:

#+BEGIN_EXAMPLE
  StW 13-28-35-33 BtW 4x4
#+END_EXAMPLE

* <2021-10-03 Sun> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-212
  :END:

#+BEGIN_EXAMPLE
  StW 45-38 BtW
#+END_EXAMPLE

* <2021-10-03 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-126
  :END:

#+BEGIN_EXAMPLE
  RTO : 2-1 Skin-the-cat : 2-2 L-sit : 9-8 Muscle-up L-sit : 3x1 -
  2+1+1 - 2+1+1 Pistols (assisted) : 3x4 Extension (lower-back) : 3x25
  Front-lever row (tuck) : 3+2 - 2x2-2+2 Planche on rings (tuck):
  3x1 - 2+1 - 3x1 Norwegian curls: 3x4 Compression : 3x10
#+END_EXAMPLE

* <2021-10-15 Fri> Parkour
  :PROPERTIES:
  :CUSTOM_ID: parkour-34
  :END:

#+BEGIN_EXAMPLE
  Passe-muraille :

  -   cat hang (each side) : 10
  -   top out (each side) : 5
  -   cat hang leg press (each side) : 4 (jambes presques tendues)
  -   cat hang pull-up (each side) : 5
  -   knee raises (each side) : 4
  -   passe-muraille: 10 (élan correct)
#+END_EXAMPLE

* <2021-10-16 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-127
  :END:

RTO : 28-18 Skin-the-cat : 1-1 L-sit : 8-7 Muscle-up L-sit : 4x1 -
2+1+1-3x1 Pistols (assisted) : 3x4#3 Extension (lower-back) : 2x22
Front-lever row (tuck) : 3+2 - 3+2 - 2+2 Planche on rings (tucked
pushed-up): 3x1 -2x1 - 3x1 Compression : 3x10

* <2021-10-19 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-128
  :END:

RTO : 2-2 Skin-the-cat : 2-2 L-sit : 9-5 (jambes semi-tendues)

Routine: Muscle-up L-sit - Tucked planche - RTO - L-sit - FL row 2x1 2x1

Pistols (assisted) - Extension - Compression 3-22-9 3-22-10

* <2021-10-26 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-129
  :END:

(à l'arrache) Pull-up L-sit Tucked front lever Pistols Compression

* <2021-10-26 Tue> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-213
  :END:

Back to wall : 45-35-30 Stomach to wall : 3x2

* <2021-10-26 Tue> Jump rope
  :PROPERTIES:
  :CUSTOM_ID: jump-rope
  :END:

* <2021-11-01 Mon> Handstand
  :PROPERTIES:
  :CUSTOM_ID: handstand-214
  :END:

Back to wall : 40-39 Stomach to wall : 11 ## 2021-11-01 L-sit tucked
5-6s

* <2021-11-04 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-130
  :END:

Tout enchainé RTO : 20-15 Skin-the-cat : 2-1+1 L-sit : 6-4 (jambes
semi-tendues) Muscle-up L-sit : 3x1-2+1+1-1+1 Pistols (assisted) : 3x3
Extension (lower-back) : 3x22 Front-lever row (tuck) : 3+2 - 3+2 - 2+1
Planche on rings (tuck): 3x{3x1} Norwegian curls: 3x3 Compression : 3x10

* <2021-11-06 Sat> Running
  :PROPERTIES:
  :CUSTOM_ID: running-7
  :END:

20min en montée la moitié du temps

* <2021-11-07 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-131
  :END:

RTO : 30-20 Skin-the-cat : 2-1+1 Pull-up (milieu poitrine) : 5x1 L-sit :
6-4 (jambes semi-tendues) Muscle-up L-sit : 3x1-2+1=1-2+1 Pistols
(assisted) : 3x4 Extension (lower-back) : 3x22 Front-lever row (tuck) :
3+2 - 3+2 - 2+1 Planche on rings (tuck): 2+1 - 2+2 - 2+1 Norwegian
curls: 3x4 Compression : 3x10

* <2021-12-08 Wed> Running
  :PROPERTIES:
  :CUSTOM_ID: running-8
  :END:

10km, 400m de dénivelé De nuit, dans la boue, 1000 personnes 1h40

* <2021-12-12 Sun> Running
  :PROPERTIES:
  :CUSTOM_ID: running-9
  :END:

25min, moderate

* <2021-12-20 Mon> Jump rope
  :PROPERTIES:
  :CUSTOM_ID: jump-rope-1
  :END:

* <2021-12-21 Tue> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-132
  :END:

Routine sur barre : pull-up - negative pull-up - planche - extension -
compression - L-sit - FL - nordic curl

* <2022-01-08 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-133
  :END:

Routine sur anneaux (3x2 pour haut)

* <2022-01-13 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-134
  :END:

Muscu sur anneaux (avec muscle-up négatifs à la fin)

* <2022-01-14 Fri> Running
  :PROPERTIES:
  :CUSTOM_ID: running-10
  :END:

Sprint : 7x30s 2min de pause # 2022-01-15 Workout Routine sur barre avec
muscle-up en négatif seulement Retravailler le L-sit !!

* <2022-01-23 Sun> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-135
  :END:

RTO: 2 fois L-sit: 3s - 2s Muscle-up : 1-2x1 - 3x1 (difficile !) PLanche
on rings: 2+1+1 - 3+1 - 1+1 Compression: 3x10 Curl: 4x3

Pistol: 3x{3#4} Extension: 3x22 FL row: 3+2 - 2+1

* <2022-01-24 Mon> Running
  :PROPERTIES:
  :CUSTOM_ID: running-11
  :END:

15min de nuit, rythme rapide au retour

* <2022-01-27 Thu> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-136
  :END:

Routine avec x2 en haut

* <2022-02-05 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-137
  :END:

Muscle-up intro avec movement athlete

* <2022-02-07 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-138
  :END:

Handstand avec movement

* <2022-02-09 Wed> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-139
  :END:

Full body avec movement athlete mais fait seulement la moitié (covid)

* <2022-02-11 Fri> Running
  :PROPERTIES:
  :CUSTOM_ID: running-12
  :END:

15 minutes

* <2022-02-13 Sun> Running
  :PROPERTIES:
  :CUSTOM_ID: running-13
  :END:

46min

* <2022-02-14 Mon> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-140
  :END:

40min mais peu satisfait des exercices

* <2022-02-24 Thu> Tricking
Tricking : 1ere fois - Butterfly Kick - Roundhouse Kick - Hook Kick -
Macaco - Scoot

Parkour
* <2022-02-26 Sat> Tricking
10min, régression - cartwheel

* <2022-02-27 Sun> Tricking
Tricking : comme avant Workout 45 min

* <2022-02-28 Mon> Tricking
  :PROPERTIES:
  :CUSTOM_ID: tricking
  :END:

Butterfly kick Macaco Kicks

* <2022-03-08 Tue> Tricking
  :PROPERTIES:
  :CUSTOM_ID: tricking-1
  :END:

Inner et outer kick Macaco

* <2022-03-09 Wed> Tricking
  :PROPERTIES:
  :CUSTOM_ID: tricking-2
  :END:

* <2022-03-12 Sat> Workout
  :PROPERTIES:
  :CUSTOM_ID: workout-141
  :END:

* <2022-03-13 Sun> Tricking
  :PROPERTIES:
  :CUSTOM_ID: tricking-3
  :END:

inner 1x15 outer 2x 15 back 1x15 butterfly 1x15 + 1x15 avec demitour
tornado 1x15 + 1x15 avec demitour combo 1x2
* <2022-03-27 Sun> Workout
45min
* <2022-03-28 Mon> Tricking
Essai Fei-Lin +/- bkick
Bckick pas assez bas !
* <2022-03-29 Tue> Workout
* <2022-03-30 Wed> Running
20min montée + descente
* <2022-03-31 Thu> Workout
demi-workout, trop fatigué
* <2022-04-09 Sat> Running
50min au total avec de nombreuses pauses à la montée
Perte d'orientation dans la forêt !
* <2022-04-08 Fri> Workout
Appli. 40min au lieu de 50 car vent + pluie !
* <2022-04-07 Thu> Tricking
B-kick surtout et Feilong.
Bkick commence à décoller
Feilong /= saut !
* <2022-04-10 Sun> Tricking, tir à l'arc
Bkick, petite session car courbature
Foret : perdu 1 flèches, cassés 4
* <2022-04-12 Tue> Running
12min montée douche puis 3min plat puis descente
Total 25min
* <2022-04-13 Wed> Tricking
* <2022-04-14 Thu> Workout
* <2022-04-16 Sat> Tricking
Bkick : commence un peu à venir
Feilong : bof
Bkick aerial
Tornado kick
* <2022-04-17 Sun> Workout
* <2022-04-18 Mon> Running
50min avec 6 min de montéé
* <2022-04-19 Tue> Workout
<2022-04-27 Wed> Tricking
<2022-04-28 Thu> Workout
* <2022-04-23 Sat> Workout
Échauffement : 10min tricking
Demi-session car appli a crashée puis 15min planche avec quelques tractions et pompes en mode planche
* <2022-04-25 Mon> Running
7min échauffement tricking
15min course
* <2022-05-02 Mon> Tricking
20min, peu de progrès
* <2022-05-03 Tue> Running
5min montée pentue
12min total
* <2022-05-04 Wed> Workout
Rings :
- warmup :
  RTO: 5-15-17-8
  skin the cat (avec descente lente pour abdo)
  L-sit x3
  negative muscle-up x3
- muscle-up : 3x1 - 1
- extension 22s
- compression 9s
  pas plus à cause de la fatigue
* Workout: objectifs d'ici 1 mois
Muscle-up : 3x2
FL tucked row : 3x10
Pistols : 3x1 sans appuis
Planche tucked push-up: 3x8
* <2022-05-05 Thu> Tricking
Roundkick 15
Reverse roundkick 15
Bkick 15
Tornado kick 15
Fei long 15
* <2022-05-06 Fri> Workout
Handstand : 1 min avec appui, 40s et 30 avec essai décollement
L-sit : 5x10 + 3 + 2
RTO 18 15
Muscle-up (anneau sur arbre donc bas) 1+1 - 2+1 - 2
Pistols 3x4
(pause)
FL tucked row : 4+2+1 - 5+3+1 - 5+2
Extension 3x22
(pause)
Planch tucked push-up 3+2+1 - 4+2+1
Compression 3x9
* <2022-05-07 Sat> Running
Trail 11km 300m dénivelé
~1h22
* <2022-05-16 Mon> Tricking
* <2022-05-19 Thu> Workout
Muscle-up 1 - 2+3x1 - 2+2x1
Pistols
Novergian curl
* <2022-05-20 Fri> Tricking
Bkick
180kick
fei long
* <2022-05-22 Sun> Tricking
15min seulement
* <2022-05-22 Sun> Workout

- RTO: 40-18
L-sit: 2
Skin-the-cat (avec descente): 2x2
- Muscle-up 1+1 - 2+1 - 2+1
Extension: 3x22
- FL tucked row : 5+2+1 - 2x{5+3+1}
Pistols : 3x4
- Planche tucked push-up: 3x {4+3+1}
Compression: 3x9
* <2022-05-31 Tue> Jumprope
15min
* <2022-06-01 Wed> Workout
Routine: 3x{1+1}
Muscle-upx1 - RTO 1s - Tucked pushed-upx1 - L-sit (halfway) - negative muscle-up - skin the cat - negative FL
+ Compression x3
* <2022-06-02 Thu> Tricking
Essai combo
* <2022-06-07 Tue> Running
Hills run : 1min sprint, 1min descente, 2min repo x5
* <2022-06-09 Thu> Workout

- RTO: 30-10
L-sit: 2-2
Skin-the-cat (avec descente): 2
- Muscle-up 2+1 - 2+1+1 - 2+1+1
Extension: 3x22
- FL tucked row : 7+3+1 - 6+3+1 - 5+3+1
Pistols : 3x4
Planche tucked push-up: 4+1+1 - 4+2 - 3+1+1
Compression: 3*10
* <2022-06-11 Sat> Running
11km, 1h40. Gennes -> Yamana
3 pause dans la montées, 4 en ville à cause de la chaleur
* <2022-06-12 Sun> Workout
Haut seulement.
- RTO: ?-?
L-sit: 2x2
Skin-the-cat (avec descente): 2x2
- Muscle-up 2+1 - 3+1 !! - 3+1 !!
- FL tucked row : 7+3+1 - 6+3+1 - 5+3+1
- Planche tucked push-up: 4+3 -4+3 - 4+2

* Workout: objectifs
Muscle-up 3x2 validé une fois -> 3x3
* <2022-06-15 Wed> Workout
- RTO: 30-12
L-sit: 12
Skin-the-cat (avec descente):
Routine x 3
- 2x{Muscle-up - RTO - planched tucked - L-sit - skin the cat - dragon flag negative}
Extension- Pistols - Compression:
* <2022-06-19 Sun> Handstand
Back to wall x2
Stomach to wall x2
* <2022-06-19 Sun> Workout
- RTO: 30-20
L-sit: 2x2
Skin-the-cat (avec descente): 2x2
- Muscle-up 2+1 - 2+1+1 - 3+1 !
Extension: 3x22
- FL tucked row : 8+4+1 ! - 7+3+1 - 7+3
Pistols : 3x4
- Planche tucked push-up: 5+1 ! - 5+1 - 4+1
Compression: 3x10
* <2022-06-22 Wed> Workout

- RTO: 30-20
L-sit: 2x1
Skin-the-cat (avec descente): 2x2
- Muscle-up 2+1 - 3+1 - 3+1
Extension: 3x22
- FL tucked row : 3x10 !
Pistols : 3x4
Planche tucked push-up: 6+3 - 4+3 - 4+2
Compression: 10-10-9
* <2022-07-09 Sat> Tricking
Basics : kicking
* <2022-07-10 Sun> Workout
RTO 28-18
- Muscle-up 2+1 3+1 3+1
  Pistols 3x4
  L-sit 2+1 - 1 - 0
-  FL 90° 2+2+1 3+2
  Planche tucked pushup 4+3 - 5+3 - 6+1
  Compression: 10-10-9
* <2022-07-11 Mon> Tricking
Basics : kicking
* <2022-07-16 Sat> Tricking
30min, basic kicks
* <2022-07-14 Thu> Workout

- RTO: 17-22
L-sit: 3x1 x2
Skin-the-cat (avec descente): 2x2
- Muscle-up 2+1 - 3+1 - 3+1
Extension: 3x22
- FL tucked row : 3+2 - 3+1 - 3+1
Pistols : 3x4
- Planche tucked push-up: 6+1 - 4+2 - 2+2
Compression: 3x9
* <2022-07-17 Sun> Running
15min jusqu’à la colline, exploration
10min de descente
