#+title: Milles et Une Nuits #+roam_tags: review * Rôle de la femme
Soumission certes mais plusieurs contes montrent une domination
parfois. - Théologique : plusieurs contes montrent des esclaves qui
surpassent tous les meilleurs théologiens dans la connaissance du
Coran - Valeur militaire : cf conte sur les Amazones - Intelligence : cf
le conte qui montre comment les hommes sont des dupeurs, et idem pour
les femmes ! * Valeur historique Mélange des périodes. Seuls points
fixes = les califes. Parfois sont mélangés des personnages d'époques
différentes Géographie vite approximative * Un recueil disparate -
Contes écrits sur une période large - Pas de source unique. La Pléiade
utilise la plus reconnue et y ajoute le conte de Sinbad - Contes courts
(1p) à très long (200p), blagues, leçons de morales, contes épiques... *
DONE 1. Nuits 1 à 327 CLOSED: [2020-11-23 Mon 21:32] Conte d'Umar an
Nu'mân, Sharr Kân et Daw' al-Makân = très long mais épique avec une
histoire sur plusieurs générations Grande variété de contes : fables,
comiques, drames... Parfois un langage très cru * DONE 2. Nuits 328 à
719 CLOSED: [2021-01-11 Mon 21:32] * DONE 3. Nuits 720 à 100 CLOSED:
[2021-02-01 Wed 21:33] - Maruf le savetier : à lire pour la partie
"duperie" assez énorme - Aladdin : en annexe car pas dans la version de
Calcutta, mais celle de Galand. On a droit à du vieux français (cf
vouvoiement entre Aladin et sa mère). L'histoire a des différences
notables avec la version Disney (ce n'est pas le vizir qui veut épouser
Jasmine).
