#+title: Hémoglobine (gas du sang)
#+author: Alexis Praga
#+setupfile: ./fiche.setup


* Localisation, rôle physiologique
L’hémoglobine sert à transporte l’oxygène des poumons aux tissus et du CO_2 des tissus vers le poumon. C’est une protéine avec 4 sous-unités, chacune comportant une molécule d’hème avec un atome de fer. Chaque hème peut fixer une molécule d’oxygène.

L’hémoglobine totale est la somme de tous les fractions d’hémoglobine mesurées : oxyhémoglobnie, désoxyhémoglobine, méthémoglobine, carboxyhémoglobine (voir fiches idoines).
* Tissus/organes de production et d'élimination
Les chaînes de globine sont synthétisées dans les érythroblastes.
Après la lyse des hématies vieilles, les hémoglobines sont catabolisées dans le système réticul-histiocytaire dans la rate, foie et omeille osseuse. les macrophages du foie vont libérér l’hémoglbine qui va perdre des molécules d’hème, qui seront oxydées avec une transformation de porphyrine. Une partie sera conjugée pour être éliminée dans la bile.
* Valeurs de référence (adulte)
Adulte 12-18 g/dL
* Principe analytique de mesure
Chaque dérivé de l’hémoglobnie a un spectre d’asorption spcéféqiue. On mesure donc l’absorbance aux longueurs d’onde caractéristique.
* Principales interactions analytiques
- hyperlipémie (augmentation)
- émulsions lipidiques (augmentation)
- congélation avec de l’azote liquide
* Vigilance pré-analytiques et analytiques
* Augmentation et diminution
- Diminution : anémie par perte de sang, destruction de globules rouges, incapacité à en produire de nouveau
- Augmentation = polycthémie primaire ou secondaire (hypoxie, déshydratation, complication de transfusion)
