#+title: Immuno-enzymatique
#+options: toc:nil
* Description
Le principe consiste à doser un antigène via des anticorps spécifiques selon le principe général d'immunoanalyse. Dans le cadre du dosage immuno-enzymatique, les anticorps sont liés à une enzyme. Après l'ajout d'un substrat, la réaction va produire un signal qui va permettre la détection.

Le dosage peut être direct avec un signal sera proportionnel à la quantité d'antigène ou indirect avec un signal inversement proportionnel à la quantité d'antigène (compétiton des anticorps).
* Points forts
- Bonne sensibilité et spécificité
- Peu coûteux
- Processus simple
* Points faibles
- Préparation manuelle
- Difficulté de préparer des anticorps spécfiques
- Faux positifs
* Interférences
- diminution du signal en cas de forte concentration d'antigène (effet "crochet")
- anti-immunoglobuline se liant à l'anticorps (contact avec les animaux, maladies auto-immunes)
- facteur rhumatoïde
- cryoglobuline
- réaction croisée avec un autre antigène
- Influence sur la liaison antigène-anticorps (pH, température, concentration antigène, protéine...)
- biotine via une intérfrénce sur le système avidine-biotine (grossesse, dialyse, sclérose en plaque, maladie métabolique, dermatite, complément vitaminique.)
- mauvaise reconnaissance des antigène (variabilité inter/intra-individuelle)
* Paramètres représentatifs
- histamine, IgE spécifique
- Interleukine
- Methotrexate
- Phenobarbital
- Phényalalanine
- Protéine \tau
- TNF-alpha
