​#biochimie Voir aussi - [[file:Bilirubine%20directe.md][Bilirubine
directe]] - [[file:Bilirubine%20conjuguee.md][Bilirubine conjuguee]] #
Localisation, physiologie

Lors de la destructions des hématies âgées, l'hémoglobine est transformé
par protéolyse en hème. Celle-ci est, suite à la libération de l'atome
de fer, transformée par l'hème oxygénase en biliverdine, qui est réduite
en bilirubine. La bilirubine va ensuite circuler dans le plasma en étant
liée à l'albumine: il s'agit de la bilirubine libre. Après captation par
l'hépatocyte, elle est conjuguée et deviens hydrosoluble et atoxique
(voir fiche bilirubine directe). À la sortie des voies biliaire, la
bilirubine est déconjuguée et réduite en stercobilinogène et
urobilinogène. Celles-ci sont oxydées dans l'iléon et caecum en
stercobiline et urobiline qui donnent leur couleur aux selles. À noter
qu'une partie de l'urobilinogène va repasser dans le foie et qu'une
petite partie va être éliminée par le rein dans les urines.

La bilirubine totale est la somme de la bilirubine conjuguée et la
bilirubine libre.

* Production
:PROPERTIES:
:CUSTOM_ID: production
:END:
Pour 80%, la bilirubine provient des hématies dans la rate par les
macrophages. 20% viennent du catabolisme hépatique des autres composés
de l'hème, de la destruction des érythroblastes dans la moelle. #
Principe analytique de mesure

Test colorimétrique diazo. Mesure par photométrie à 546 nm de
l'azobilirubine rouge qui est proportionnelle à la concentration de la
bilirubine totale.

* Valeurs de référence [cite:@thomas2008labor]
:PROPERTIES:
:CUSTOM_ID: valeurs-de-référence-thomas2008labor
:END:
- hommes  ≤ 21μmol/L
- femmes  ≤ 17μmol/L

Risque cliniquement significatif chez les nouveau-nés
[cite:@american2004management] :  ≥ 137 μmol/L à 24h, ou 222μmol/L à 48h
ou  ≥ 290μmol/L à 84h ou ≥ 95e percentile

* Principales interactions analytiques
:PROPERTIES:
:CUSTOM_ID: principales-interactions-analytiques
:END:
- immunoglobuline > 28g/L
- diminué si B12 (hydroxycobalamine)
- augmenté si myélome multiple
- gammapathie IgM (très rare)

* Vigilance pré-analytiques et analytiques
:PROPERTIES:
:CUSTOM_ID: vigilance-pré-analytiques-et-analytiques
:END:
- âge du patient
- tube hépariné (lithium, EDTA di- ou tri-potassique)

* Variations [cite:@bonnefont2019explorations]
:PROPERTIES:
:CUSTOM_ID: variations-bonnefont2019explorations
:END:
- physiologique : nouveau né
- une augmentation pathologique doit prendre en compte la bilirubine
  conjuguée pour orienter le diagnostic:
  - augmentation de la bilirubine non conjuguée:
    - augmentation de l'hémolyse qui va saturer les capacité de
      conjugaison du foie
    - immaturité hépatique (ex: nouveau-né)
  - augmentation de la bilirubine conjuguée : voir fiche bilirubine
    directe
