#+title: Metabolique
#+author: Pr Schiff
#+date:<2022-06-29 Wed>

* Classification
** Intoxication = urgence médicale
- intervalle libre (foetus : placenta = épurateur et la mère est htz [maladie récessive])
- cerveau foie
- déclenché par situation activant catabolisme (jeṷne, infection, accouchement)
** Maladie energétiqu = urgence médicale
peu sont traitable (acide gras)
acide gras = substrat energétique (effort long pour muscle, épargne le glucose)
-> sévère : coeur, foie,
Mḙme circonstances déclenchantes
pas d’intervalle libre
** Molécules complexes = moins urgent
- Mitochondriale
- Lysosome "poubelle de la cellule" ->_maladie de surcharge
  ttt :
  - certaines sont accessibles à l’enzymothérapie (muccopolysaccharidose)
  - enzymothérapie : ne passe pas la barrière hématoencéphalique -> greffe de moelle osseuse (enzyme lysosomale est sécréteée): passe un peu la barrière
  - thérapie génique (on extrait les CSH puis manip puis réinjection)
- Glycosylation (réticulum endoplasmique)
NB: pour les mitochondries, double membrane donc très compliqué d’envoyer des médicaments

Bloc enzymatique : accumulation peut ḙtre traité par alimentation, enzyme,dialyse
* Accès aigù
Savoir doser pendant l’accès aigu
NB: acide métabolique avec TA augmenté = hypochlorémie. TA normal = hyperchlorémie [fn:1]
Hyperammionémie -> transport 4degrés (dans la glace) !!
Lactatue = anoxie mais peut aussi ḙtre ure fausse anoxie (ex: prélèvement au garrot)
BU = important ! Il ne faut pas de corps cétonique dans les urines du nouveau né (ne doit pas ḙtre à jeun!)
** Intoxication
- Phénylcétonurie = 1ere cause de retard mental traitable par régime
phénylaline = exprimée uniquement dans le foie
Retard de dev progressif
- Thyrosine: toxicité directe sur le foie et le rein
*** Avec quoi ?
acide aminé = aminoacidopathie (phénylcétonurie)
acide organique = acidurie organique
ammoniaque (déficcit cycle de l’urée)
sucre (intolérance au sucre)
*** Quand y penser en néonat (les formes les + sévères)
- interavlle libre
- grossesse, accouchement normal
- examin clinique normal à J1 mais problème J3
- coma progressif !
- mouvements anormaux *avant* le coma
- odeur particulière,  "pieds en sueurs" (acidurie ...) ou sirop d’érable (leucinose)

*** Coma "nu" (sans acidose)
Urine au contact DNPH change de couleur (leucinose ?)

*** Vidéo :
mouvements anormaux lents de grande amplitude, des membres sup et infé (boxe et pédalage)
Coma
*** Leucinose
150 patients en France

Maple Syrup Urin Disease = MSUD
**** Physiopathie
catabolisme
1. enlève la fonction amine -> alpha cytoacide
2. complexe BCKD va dégrader -> ne marche pas si leucinoe -> accumulation en amont
Accumulation leucine = très neurotoxique :2 hypothèse
1. utilise transporteur LAT1 et va donc bloquer les autres acides aminés qui l’utilise -> carence en neurotransmetteur
2. interfère avec patho énergétique mitochondrial
3. ?
   Mouvement anormaux != épilepsie !
Lésion neuro caractéristqiue (Anomalies substance blance...)
Toxicité réversible si ttt !
**** Ttt en urgence
Régime strict en protéine
Dialyse
Mais risque sur les futures infections...

*** Dosages
  chromatographie acide aminé dans le sang ! (pas dans les urine... inutile)
  chromatographie acide organique urine (très volatile dans le sang)

  carnitine = aide oxydation acide gras, mais aide aussi à épurer acides organique
  -> usage thérapeutique
*** Acidurie organique
**** Acidocétose , contraireemnt à leucinée
- 3 diag métabolique
  - diabète 1
  - acidurie organique
  - trouble cétylose (acidocétose de jeṷne car n’arrive pas à dégrader)
- exogène : aspirine, méthanol
**** Clinique
Trémulations ! hpertonie périphérique
polypnée (compensation acidose)
neurotoxique mais physiopath compliqué
Interfère respi mitochondrial (secondaire, ubiquitaire), cycle de Krebs
Dialyse et régime
Devenir à long terme mauvais
**** NB: doser ammionémie
*** Attention aux formes plus tardives
** Déficit énergétique
enzymes régulant la glycémie, oxydation acide gras, mitoch
** Déficit oxydation acide gras
*** Physio
Normal : jeṷne -> TG donne des acide gras (lipolyse) -> oxydation donne corps cétonique -> utilisation périphérique
Anormal : pas de corps cétonique -> hypoglycémie *sans* cétose
Ttt: perfusion de sucre
*** ACide gras
Pendant hypoglycémie, prendre du sang si pas de coma *avant* resucrer !!
ACide gras = métabolisme du coeur au repos ->_explique CPK élevé, atteinte cardiaque, hypoglycémie

Prévenir le jeṷne +++

*** MCAD
Hypoglycémie sans cétose, arrḙt cardiaque : MCAD
Prévenir le jeṷne +++++ (repas fréquent, perfuser si infection)

*** Reye: coma, insuf hépatique et ?
- ?
-  ?
*** Hypoglycémie
Dextro parfois non fiable -> glycémie capillaire
Exclure insuf hépatique (cirrhose, hépatite) !
Hypoglycémie selon temps de jeṷne :
- postprandial immédiat -> sécrétion inaproprié insuline (tumeur, génétique)
- 2-5h:
  ...

Bilain urgence
- en hypo : ?
- hors hypo
*** Formes aigües possible chez adulte
ex: déficit en OTC (maladie liée à l’X)
*** Normes
Hypoglycémie < 0.55g/L
Hyperammionémie
- Nouveau-né > 100uM, nourisson/enfant >_50uM
Acidose métoblique : ph < +.»-, ra < 18mmol/L -> calcul TA. Si diminué, quelque chose va le complétér
** Examens spéciique métabolique
Urines: congeler
sang
Divers
** Cas clinique
Carence B12  -> Anémie macrocytaire -> choc cardiogénique
Enfant allaité  -> probable carence B12 chez mère :
- anémie de Biermer (auto-anticorps empḙche absorption B12)
- vegan (oeufs, poisson ... )
  NB: B12 normales chez la mère malgré tout...
* Chronique
** Phénylcétonurie - Hyperphenylalaninémie
Ttt à vie car neurotoxique (prévenri maladie neurodégénérative !)
Régime difficile : limitation protéine alimentation (selon le biomarqueur)

Attention à l’embryofoetopathie
Dysmorpho ressemblant au sd l’alcoolisation foetal (probablement mḙme mécanisme)
** Homocystinurie
- Ressemble à Marfan -> tout marfan doit avoir un dosage
Cyphoscoliose
- Thrombose
- Neurocognitp
Pour les chirurgie, régime particulier prophylactique avec hospit
Physio: acculumation homoscytéine par déficit CBS (vitamine B6)

ttt:
- régime liminté en met
- ttt bétaine (avec équilibre à trouver, cf schéma )
- peut répondre B6
*** Carence B12 -> CBLC
Cofacteur
Y penser sur SHU atypique,

Hyperhomocystéimé aussi !:
TTT B12 injectable (forme spécifique)
** Maladie lysosomale
Progressives, plusieurs systèmes
surcharge
Y penseR si atteinte osseuse et viscérale sans anémie ni thrombopénie -> mucopolysaccharidose
os + HGM + hmaté sans signe ni dysmorphie -> gaucher
neurocogn péridominante (régression+++, épilepsie) -> sphingolipidose
*** MPS 1
Spectre : Hurler - Hurler-Scheie - Schie
*** Glycosylation : CDG
Se fait dans cytolose, réticulum endoplasmique, Golgi
Trnasferrin a un point de pH différente

Ia
- Répartition des graisse anormales, fente
- Atrophie cérébelleuse
Ib = seule forme traitable !
- sévère = gastro, *entéropathie exsudative* majeure, pas d’anomalie neuro
  ttt par mannose
* Footnotes
[fn:1]
Acidose avec trou anionique normal (gain d’HCl) : perte rénale ou digestive de
HCO
3
– ¨ baisse du HCO
3
– compensée par une augmentation proportionnelle du
Cl– (gain d’HCl) ¨ acidose métabolique hyperchlorémique.
h Acidose avec trou anionique élevé (gain d’AH) : addition d’H+ associé à un anion
indosé ¨ baisse de [HCO3–] remplacée par un anion non mesuré (par exemple
le lactate).


lol

** Dépistage post natal
Existant
- la phénylcétonurie : maladie génétique due au déficit d’une enzyme qui transforme la phénylalanine présente dans l’alimentation. En l’absence de traitement, elle peut entraîner un retard mental sévère et des complications neuropsychiatriques ;

- l’hypothyroïdie congénitale : maladie qui se traduit par une sécrétion insuffisante des hormones thyroïdiennes par la glande thyroïde. En l’absence de traitement, son dysfonctionnement retentit sur les grandes fonctions de l’organisme et peut avoir notamment pour conséquence, un retard mental sévère ;

- l’hyperplasie congénitale des surrénales : défaut génétique du fonctionnement des glandes surrénales. En l’absence de traitement, elle peut être à l’origine de déshydratations aiguës sévères, parfois mortelles, et de troubles du développement des organes sexuels ;

- la mucoviscidose : maladie génétique qui entraîne des infections respiratoires sévères et répétées ainsi que des complications digestives ;

- le déficit en MCAD ( Medium-Chain-Acyl-CoA Déshydrogènase) : maladie qui entraîne une difficulté de l’organisme à utiliser les graisses comme source d’énergie. En l’absence de traitement, elle peut provoquer des comas pouvant aller jusqu’au décès de l’enfant ;

- et éventuellement la drépanocytose, si votre enfant fait partie des populations exposées à cette maladie : maladie génétique liée à la présence d’une hémoglobine dans le sang qui peut se traduire par une anémie persistante, des complications vasculaires, des crises douloureuses et des infections répétées.

+7 bientot :
  : la leucinose (MSUD), l’homocystinurie (HCY), la tyrosinémie de type 1 (TYR-1), l’acidurie glutarique de type 1 (GA-1), l’acidurie isovalérique (IVA), le déficit en déshydrogénase des hydroxyacyl-CoA de chaîne longue (LCHAD), et le déficit en captation de carnitine (CUD)
