​#biochimie # Localisation, physiologie

L'aspartate transférase est une enzyme transaminase qui va transférer un
groupement amine depuis un acide aminé (aspartate) vers un acide
cétonique (acide α-cétoglutarique) selon la réaction

aspartate + acide α-cétoglutarique ↔ oxaloacétate + glutamate

L'ASAT est le point de départ de nombreuses réactions métaboliques (ex:
pyrimidine) et le glutamate est impliqué dans le cycle glucose-alanine.

Elle se trouve principalement dans les cellules hépatiques et
cardiaques, et dans une moindre mesure dans les muscles squelettiques,
reins, pancréas, globules rouges et cerveau.

* Production
:PROPERTIES:
:CUSTOM_ID: production
:END:
Il existe 2 isoenzymes : une dans le cytoplasme et une dans les
mitochondries. Une cytolyse va conduire à une libération dans le sang.

* Principe analytique de mesure
:PROPERTIES:
:CUSTOM_ID: principe-analytique-de-mesure
:END:
Test enzymatique.

L'absorbance est mesurée par photométrie qui reflète la vitesse de
formation de NADH, qui est proportionnelle à l'activité de l'ALAT selon
l'équation : oxaloacétate + NADH + H^{+} → malate + NAD^{+}

* Valeurs de référence [cite:@thomas2005consensus]
:PROPERTIES:
:CUSTOM_ID: valeurs-de-référence-thomas2005consensus
:END:
- homme < 50U/L
- femme < 35U/L

* Principales interactions analytiques
:PROPERTIES:
:CUSTOM_ID: principales-interactions-analytiques
:END:
- hémolyse
- gammapathie IgM (très rare)

/Note: les carences en vitamine B_{6} ne sont plus une interaction/

* Vigilance pré-analytiques et analytiques
:PROPERTIES:
:CUSTOM_ID: vigilance-pré-analytiques-et-analytiques
:END:
- Prélèvement non hémolysé
- tube hépariné (lithium, di- ou tri-potassique)

* Variations [cite:@bonnefont2019explorations]
:PROPERTIES:
:CUSTOM_ID: variations-bonnefont2019explorations
:END:
- physiologiques: augmentation à la naissance puis diminution jusque 6
  ans [cite:@van2019davis], surcharge pondérale, exercice musculaire
  violent

- 
  - iatrogène: aigü = IMAO, méthyldopa, isoniazide, halothane;
    chronique :: isoniazide, nitrofurantoïne, AINS, sulfamide...

- augmentation pathologique
  - hépatite virale, autoimmune
  - infections (EBV, CMV, HSV, toxoplasmose)
  - alcoolisme aigü/chronique
  - inflammation modérée
  - obstruction voie biliaire, cirrhose
