#+title: Conférence du <2020-10-07 Wed>
Début 19h mais repris à 20h18.
Arrêté à 21h07
* Recommandations
HAS = la dernière version fera foi aux ECNI
Vérifier si chaque item a une version plus récente que le collège !
Autres sources : collège (CNGOF...), société savante
* Matières ultra-rentables
Médecine légale
MPR
Douleur et soins pall
5% des questions pour des tous petits collèges => rentable+++
On le voit dans les annales
* Référentiel secondaires
De manière générale, mieux vaut aller voir le spécialiste
- Médecine vasc : 3 items à travailler (EP, insuf veineuse et ?)
- Chir dig : choisir quelques items à travailler dans ce collège (hernies)
- Neurochir : compression médullaire, trauma crânien, HSA, tumeurs IC (tout ce qui est neurochir)
- Cancéro : travailler les cancers dans sa spécialité (plus de chance d'avoir un dossier par un non-cancérologue) mais connaître anapath, ttt à savoir
- Immunopathologie : même rédacteur qu'en médecine interne. Utile pour vascularite et allergie mais facultatif
- MIR : choc, trauma, intox. Tout le reste est redondant ...
- Anapath : idéalement, ouvrir pour chaque item. 5 QI d'anapath ! Pas de coupe à apprendre.. Pas une priorité
- Thérapeutique : inutile pour partiels. Utile seulement pour items génériques mais tombe peu en annales
- Parasito : inutile, les questions sont tirées du Pilly
- Imagerie : trouver une source plus pédagogique (radiopedia)
- Anesth-réa: même items que MIR mais questions plutôt de l'anesth-réa
- Activité physique et sportive : inutile
- Bio médicale : inutile
- Génétique : QI tous les ans => on ne trouve l'information que dans le livret spécial ECN du collège FASM2

NB: 2016 = pas représentatif, questions très dures
*  Faire des annales+++
2 fois
* Resources en lignes
Radiopedia
Chaîne d'anaptah
* ECNi interfac
Non représentatifs des ECN au final
