* Endocrino
** Cortisol
- minimal à minuit, max à 8h. Idem pour ACTH
- Acromégalie : test de freinage au glucose. Si diabétique, suivre cycle de GH sur
3 ans (\ne gold standard, simplement un argument !)

Acanthosis nigricans : monte insulino-résistance
** Antidiabétiques oraux
1ere intention : metformine
2eme intention : metformine + glinides ou victoza (GLP1) 
2eme intention (HAS) : metformine + sulfamides hypoglycémiants (moins chers ?)

NB : inhib de DPP-4 et analogue de GLP1 sont redondants ! Ne pas combiner...

** Insuline
- 50% basal 50% en rapide (sur les 3 repas) avec total = 0.5*poids si DT2, 0.8*poids si DT1
- Basal bolus ou novomix (semilente + rapide) 2x / jour selon les services
** Complications
3 stages (par gravité croissante) : hyperglycémique, cétosique, acido-cétosique

TTT : insuline par IV avec contrôle gylcémie toutes les heures, contrôle cétoné
Adaptation l'insuline sur la cétonémie+++ (pas la glycémie qui est trop rapide à se corriger)
Seuil : > 3mmol/L = insuilen IV. Patho si > 0.5mmol/L
Si besoin, ajouter glucose (si glycémie basse)

** Objectifs 
- standards : 0.8-1.3g/L avan repas et 1.3-1.8 => risque d'hypo mais évite
  complications long terme => sujet jeunes
- élargies :  1-1.5 avantrepas, 1.5-2g/L sinon
** Notes
Si coronaropathie, important de baisser le diabète (athérome)
** Examen clinique
*** ATCD
chir, med, gynéco, familial, perso
*** Ttt
habituel, allergies (dernier repas)
*** MDV
- profession, main dominante, sport
- toxiques, alcool, tabac, viral
- conditions de vie, autonome
*** HDM
- anamnèse: déclenché par ? favorisé par ?
- clinique : quantifier, signes
- complications, retentissement, fièvre, AEG
*** Examen physique
- constantes : TA, températeure, FR, FC, sat, poids, diurèse, CS
- hémodynamique,
- repi
- neuro
- infectieux
*** Endocrino 
- poids, taille, IMC, tour taille
- visag, répartition graisses, xanthome
- thyroïde, profil + face, tour cou, palpation
*** Diabétique
**** Clinique
- fonctionnel : angor, AIT, claudication HTA, vision
- FR CV : ATCD, tabac, obésité
- PA couché et debout
- pieds : pouls, cutané, TRC, réflexe achilléen, sensibilité superficiell,
  monofilament
- neuro
- pouls, souffle vasc
- bouches, sinus
**** Histoire
- découverte ?
- histoire du traitement
- DG (macrosome > 4kg)
- suivi des complications : ophtalmo (FO), cardio (doppler MI, TSA), rein
- poids, alim
- demander carnet glycémie, si autonome

*** CS pré-chir bariatrique,
- ATCD, ttt, allergie,
- Grossesse, DG (macrosome > 4kg, ttt)
- ATCD familiaux
- Histoire du poids
- Activié physique
- Comportement alimentaire (régimes précédents)
- SAOS
- Acanthosis nigricans
* Généraliste
** DONE J4
   page 1 + 2 faite
** TODO J5
** TODO J6 en cours
** TODO J7  à reprendre
TVP : rupture de kyste poplité
** TODO J8 
TVP : rupture de kyste poplité
** Dépistage
- Cancer colorectal : 
  + risque modéré (> 50A, asymptomatique) = test immuno de sang dans le selles tous les 2 ans \pm coloscopie.  
  + risque élevé : coloscopie tous les 3 à 5 ans selon ATCD
** Examen clinique
*** Hygroma 
    CLOSED: [2019-06-17 Mon 22:00]
 - Genou++, coude : fréquent si sollicitation professionnelle
 - Douleur local, aspect inflammatoire (chaud), épanchement liquidient palpation
 - Repos, glace, anti-inflammatoire
*** Réflexes archaïques (doivent avoir disparus à 4 mois)
    - Moro: extension cervical (en arrière) rapide => extension + abduction des bras
    - stimulation palmaire => agrippement
    - frottement des pieds => ébauche de marche
    - succion
    - stimulation péribuccal => tête tournée vers stimulation
    - allongement croisé : stimulation plante de pied => flexion et extension controlatérale
*** Critères d'Ottawa      
Radio de cheville si douleur malléolaire *et*
- impossible de marcher > 4 pas immédiatement et à l'examen
- *ou* sensibilité 6cm distaux tibia
- *ou* sensibilité 6cm distaux
*** Dorsalgie/cervicalgie
Palper épineuses (signe de la sonnette), muscles paravertébreux
*** Déchirure musculaire
Douleur brutale \pm hématome, voussure palpation
*** Douleur pouce
Tendinite de De Quervain ? Signe de DQ = pathognomonique
Rhizarthrose
** Examens
- Fracture de fatigue : scinti/TDM/IRM ou RX différée
** Médicaments
Acide fusidique : impétigo
Airomir : crise d'asthme
Antadys : rhumatismes inflammatoires, dysménorrhées(AINS)
Apranax = /naproxène/ : AINS
Atarax = anxiolytique
Auricularum = /dexaméthasone/ + /ATB/ : otite externe bactérienne, otite chronique
Avodart = /dutasteride/ : HBP
Bedelix : symptomes des manifestation fonctionnelles intestinale
Bilaska : rhino-conjonctivite allergique
Bipreterax = /périndopril/ (IEC) + /indapamide/ (diurétique) : HTA
Celebrex : arthrose, PR, spondylarthrite ankylosante
Cerulyse = /xylène/ : bouchons cérumène
Ciclopirox = antifongique : intertrigo, onychomycoses...
Ciloxadex = /ofloxacine/ + /dexaméthasone/ : otite aigüe externe
Clindamycine = /macrolide/
Coversyl = /périndopril/
Daily = contraceptif estroprogestatif
Duplavin = aspirine + clopidogrel : prévention secondaire chez SCA ST-, IDM ST+
Ezetimibe : +statine pour hypecholestérolémie primaire
Flector = /diclofénac/ : tendinite (AINS)
Fluinidone = /previscan/ (AVK)
Flécaïne : TV
Gibiter = /corticoïde/ + /BDLA/ pour l'asthme
Hamamélis : hémorroïdes, insuf. veinolymphatiques
Hamamélis : hémorroidies, insuf. veinolymphatique (phytothérapie)
Ibufetum = AINS en gel
Izalgie = /opium/ + /paracétamol/ (> Lamaline)
Kétoconazole =: antifongique  : dermite séborrhéqiue, candidoses
Lasilix = /furosémide/ = diurétique de l'anse
Lumirelax = relaxant musculaire
Micardis = /telmisartan/ (ARA II)
Norset = /mirtazapine/ : épisodes dépressifs majeurs
Norset = /mirtazapine/ : épisodes dépressifs majeurs
Optimizette = contraceptif progestatif
Pradaxa = /dabigatran/
Prolia = /dénosumab/ : ostéoporose (5 ans puis 1 an biphosphonates)
Salbutamol : asthme, BPCO
Smecta = /diosmectite/ : adsorbant intestinal (diarrhée)
Spasfon : troubles fonctionnels digestifs
Spedra : dysfonction érectile
Stresam : anxiolytique
Structocal = calcium + vitamine D3
Tanganil = antivertigineux
Tiorfan = /racecadtril/ : complément des diarrhées aigüe de l'adulte
Ténormine = /aténolol/
Uvédose : carence vitamine d
Vogalène = /métopimazine/ : antiémétique
** Orientation
- Sensation faiblesse persistante : cardio (rythme, conduction), infection, thyroïde, pulmonaire
** Prévention risques foetaux
- Toxoplasmose : sérologie *systématique* < 10SA => si négatif, contrôle *mensuel* !
- Rubéole : sérologie *systématique* < 10SA
- Syphilis : sérologie *systématique* < 10SA
- VHB : sérologie *systématique* 6eme mois
- VIH
- streptocoque : prélèvement *systématique* 36-38SA

** Suivi
** Vaccins
Diphtérie, tétanos, coqueluche, polio => 2M, 4M et rappel à 11M et 6A puis 11A
(vaccin différent)
  - Tétravac, Repevac (seulement après 3A)
Haemophilus influenzae : 2M, 4M, 11M
Pneumocoque, hépatite B : idem
Ménigocoque : 5M et 12M
Rougeole, oreillons, rubéole :12M et 16-18M

* Médecine nucléaire
Scinti
| Isotope              | Vecteur              |                            |
|----------------------+----------------------+----------------------------|
| Technetium           | HDMP (diphosphonate) | os                         |
| Technetium           | albumine             | perfusion pulmonaire       |
| Technetium           | Technegas (carbone)  | ventilation pulmonaire     |
| Technetium           | DMSA                 | masse rénale fonctionnelle |
| Technetium           | HMPAO                | perfusion cérébrale        |
|----------------------+----------------------+----------------------------|
| Iode                 | 0                    | thyroïde                   |
|----------------------+----------------------+----------------------------|
| Indium  (Octréoscan) | Pentétréotide        | tumeurs neuroendocrines    |
TEP
| 18-F | FDG           |
| 18-F | FCH (choline) |
| 18-F | FDOpa         |
** Cours
*** Médicaments radiopharmaceutiques : constitués d'un radio-élement (émet le rayonnement) + un vecteur (se fixe aux organes)
  - technétium : scintigraphie++. Produit directement dans le service
  - F18-fluorodésoxyglucose : grande sensibilité pour la détection de nombreux
    cancers (sauf prostate), certaines maladies inflammatoires ou infectieuses
  - analogues de la somatostatine + gallium 68 : certaines tumeurs endocrines
  - bisphosphonates : métastases osseuses
  - Radiothérapie : hyperthyroïdes, métatastes osseuses des adénomes prostatique

Choix du radio-élement
  - scintigraphie : émissions de *photons \gamma*
  - TEP : émissions de *positons* (électrons avec charge positive).
*** Principe technique :
**** Détection des photons \gamma
1. Après émissions, ils arrivent sur un cristal. Leur énergie est transférée aux
électrons du cristal, qui émet des photons lumineux ("scintillation") dans
toutes les direction.
2. Conversion en signal électrique et amplification dans des tubes photomultiplicateurs
3. NB: Les premiers photons \gamma peuvent interagir avec les tissus biologiques et
   diffuser d'autres photons (source d'erreur) => filtrage
4. NB: Dans l'étape 1, comment savoir d'où vient le photon *lumineux* si émis
   dans des direction aléatoire ? Le nombre de photons reçus est inversement
   proportionnel à la distance de la source => comparaison des différents tubes
/Comment retrouver la position du photon initial depuis le cristal ? Collimation physique (scinti) ou  électronique (TEP)/

**** Gamma caméra : collimation physique
- canaux parallèle : filtre les photons arrivant perpendiculairement au cristal
- "pinhole" : bonne résolution mais mauvaise sensibilité => Thyroïde
- Il faut trouver un compromis entre résolution spatiale et sensibilité
 - Acquisition planaire ou tomoscintgraphie (le détecteur tourne autour du
   patient, 15min donc sur un seul organe...)
**** TEP
 - Annihilation d'un position génère une paire de photons gamma partant à 180°.
 Grâce à des détecteurs en "couronne", détection simultanée (enfin presque,
 fenêtre de 10ns)
 - Contrairement à la scinti, plusieurs cristaux sur chaque récepteur
 - Meilleure sensibilité et résolution spatiale que la scinti
 - souvent combiné à une TDM en même temps
**** Correction des biais de quantification
Imprécise en tomoscintigraphie, meilleure en TEP
**** Évolution
- Cristaux semi-conducteur pour gamma-caméra : améliore sensibilité et résolution spatiale
- Tube PM => photodiodes plus compact pour TEP
** Stage
Choline : adénome parathyroïdien
Scinti : utile pour algodystrophie
Ganglion sentinelle : opération du sein++, pour aider le chirurgien à repérer le
ganglion (injection la veille/le jour même)
*** Cancers
**** Prostate
- Scinti : bilan d'extension de K de la prostate
- Classif selon PSA et score Gleason (histo), mais cinétique importante
- Méta  = os, ganglions de l'abdomen et du bassin
*** Lymphome
Classif d'Ann Arbor : I= 1 territoire, II = N territoires du même côté, III =
sus et sous-diaphragmatique, IV = viscérale
*** Scinti thyroide
- Basedow : diffus
- De Quervain : pas de fixation
- Hashimoto : hyperthyroïde puis hypothyroïde : fixation faible hétérogène
*** Scinti cardiaque
- Effort et repos, sans et avec correction à chaque fois (sert à corriger
l'atténuation corporelle)
- Déficit réversible = ischémie, sinon nécrose
** ECNI
Scinti thyroïdienne, éventuellement pulmonaire peuvent tomber

* Gynéco
- Diabète gestationnel :
déclenchement pour éviter macrosomie et d'aggraver le diabète (à vérif)
- HELLP (completer)
- SHAG
- GUE : methotrexate possible (sauf si à la base des trompes)


* Urgences
Douleurs abdo : urgence = torsion testiculaire (1 testicule remonté, voire
gonglé et rouge). Y penser même sans douleurs...

* Gardes
** 1. Urgences : ABCDE
https://www.resus.org.uk/resuscitation-guidelines/abcde-approach/
[[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&ved=2ahUKEwjqre3gkezkAhWPohQKHWVxAygQFjALegQIBBAC&url=https%3A%2F%2Fwww.who.int%2Femergencycare%2Fpublications%2FBEC_ABCDE_Approach_2018a.pdf&usg=AOvVaw3Cu1L7fniTpCUwq9PwOeap][WHO]]
Éliminer les risques vitaux en 30s
*** A : airway
_corps étranger, brûlure, anaphylaxis, trauma ?_
Peux parler ?
  - oui :
    + difficilement ? cherche obstruction, fluide
      * Corps étranger : si visible, enlever. Si toux, encourager. Sinon frappes
        dans le dos (par 5)
      * anaphylaxie : adrénalie IM
  - non : dégager voies respi
*** B : breathing
_pneumothorax, overdose, asthme, BPCO ?_
Très rapide, très lent ?
Muscles accessoires, tirage, balancement thoraco-abdominal
*** C : circulation
_0 pouls, chock, hémorragie sévère, tamponnande cardiaque ?_
Perfusion : extrémités froides, TRC > 2s, hypotension, tachypnée, tachycardie,
pas de pouls
Saignement ? Poitrine, abdomen, fractures
Tamponnade ? hypotension, veines du cous, bruits du coeur étouffés
Pression sanguine
*** D : disability
_Hypoglycémie, HTIC, convulsion ?_
Conscient ? Glasgow
Hypoglycémie ?
Pupille ?
  - myosis :  opiodes ? => naloxone
  - inégales : HTIC ? lever la tête
  - sinon : trauma ?
Convulsion ?
*** E : exposure
Autres blessures, réactions allergiques
Protéger de l'hypothermie, enlever vêtements/bijous "constricteurs"

** 2. Si non, reste de l'examen
*** Examen clinique
- Genou : tiroir antérieur postérieur, laxité latéral, épanchement ? (bilatéral !!), Zohlen, amplitude passive
- plaie : infectée, oedème, lymphangite (trainée rouge ?)
*** Enfant
- examen de la bouche : bras en arrière de la tête
- trauma crânien : si a pleuré, pas de perte de conscience !
  Surveillance simple à domicile si pas de point d'appel. Les parents
  doivent le réveiller régulièrement et surveiller : vomissements,
  céphalées, troubles cognitifs....
* Footnotes

[fn:1] Les rayonnements X proviennent d'un réarrangement des électrons, les rayonnements gamma viennent des transformations du noyau.
