#+title: pCO2
#+author: Alexis Praga
#+setupfile: ./fiche.setup

* Localisation, rôle physiologique
Le CO2 transporté dans le sang est sous 2 formes : dissous dans le plasma et le cytoplasme des globules rouges et combinés sous forme de bicarbonate, ainsi que lié à l’hémoglobine.
* Tissus/organes de production et d'élimination
Le CO2 est produit lors du métabolisme cellulaire normal de manière continue et libéré dans le sang. Il est ensuite transporté dans les poumons, où aura lieu une diffusion des capillaires pulmonaires dans les alvéoles. Il sera ensuite expiré.
* Valeurs de référence (adulte)
- artériel : 35 - 46 mmHg (4.7 - 6.1 kPa)
* Principe analytique de mesure
 Ampérométrie par mesure du courant généré entre 2 électrodes suite à la réaction d’oxydation du CO2
* Principales interactions analytiques
- Dilution si prélèvement sur cathéter
- Tube EDTA, citrate, fluorure *proscrits*
* Vigilance pré-analytiques et analytiques
- Vérifier que la température est renseignée
- Absence de caillot ou de bulle
- Seringue/capillaire hépariné
- 1mL minimum pour une seringue (si < 0.5, choisir une analyse), 100μL pour un capillaire
* Augmentation et diminution
La pO2 reflète l’état respiratoire général.
- Une pCO2 faible traduit une hyperventilation
- Une pCO2 élevée révèle une hypoventilation ou insuffisance respiratoire
  - soit d’origine pulmonaire
    - BPCO sévère
    - Emphysème pulmonaire sévère
    - Résection chirurgical
    - Pneumopathie inflammatoires
  - soit d’origine non pulmonaire
    - défalliance du Contrôle ventilatoire
      - origine cérébrale : infections, traumatismes, tumeurs, AVC
      - centres respiratoire :
        - perte de contrôle (sédatifs, Parkinson, tétanos...)
        - lésions voies afférentes/éfférente (traumatisme médullaire cervical, sclérose en plaque)
        - récepteurs périphériques  :  syryngomyiélie, neuropathie diabétique
      - Pompe ventilatoire
        - neuromusculaire : SLA, Guillairn-Barré, toxique, myasthénie  hypokalémiée, hypophosphatémie
        - cage thoracique : Cyphoscolioase, fibrose, obésité...
