#+title:      Determining the incidence of rare diseases
#+date:       [2024-07-18 Thu 14:36]
#+filetags:   :bib:facebook:
#+identifier: 20240718T143615
#+reference:  bainbridge2020determining

MAF pour allèles patho dans maladies récessives. Calculable à la main

* Contexte (maladies récessives)
Majorité = hérité donc on peut calculer une incidence si toute les allèles patho sont connues et qu'on connat leur MAF
Pour une population nombreuses avec des "mating" aléatoires, on peut utiliser Hardy-Weinberg.
Mais la MAF des allèles patho est difficile à trouver.

* Biblio
- [cite:@schrodi2015prevalence] : approche bayésienne pour maladie récessive également, limite non claire pour moi dans l'article ("head allele ?")= allèles

* Apport
Allèles trop rare pour avoir une MAF d'une base de données publique, voir trop rare pour avoir un individu attent
* Prérequis
 - cohorte de ~50 individus avec allèles patho connues
 - MAF d'une base de donnée publiques
- seulement allèles patho
* Hypothèses ("raisonnables")
 - les allèles pathogènes ségrègent de manière indépendente (raisonnable pour allèles très rares, Browning 2012)
 - pas de consanguinité et mating aléatoire
 - pénétrance complète
 - MAF des bases de données publiques = représentation correcte de la MAF de la cohorte
 - pas de biais de sélection des patients atteints dans la cohorte
* Méthode
1. allèles sans MAF mais présentes dans la cohorte: la MAF totale est calculée par
  #+begin_src latex
\frac{m}{c} X
  #+end_src
  où m est la somme de ces MAF, c le nombre total des allèles et X le nombre d'allèles sans MAF mais présentes (à vérifier)

   - Si la plupart des allèles ont été observées M \approx vraie MAF
   - sinon, il faut aboslumenet le nombre total des allèles dans la population
     - on suppose en plus que toutes les allèles non vues ont la mme MAF (raisonnable pour allèles rare)

     - estimé par une loi de poisson dont le paramètre est estimé par un maximum likely hoood estimater
     - la MAF par allèle est estimée par MAF moyenne
2. allèles sans MAF et absentes de la cohorte: non mentionne de l'article
3. allèles avec MAF et présente cohorte : non mentionné non plus :/
* Validation
** Données simulée
 distribution MAF connue avec 50 indivisu biallélique/homozygote. Distribution testées
 - 5 allèles courantes et 20 rare
 - idem mais 110 rare
 - 43 allèles de meme fréquence
  Erreur : <= 2.6%
** Cohorte SCL13A5
37 famnilles
MAF totale : p = 0.18 de différence
* Limites
Biais dans la cohorte (origine européenne)
