:PROPERTIES:
:ID:       1c36e841-fad4-4345-ab8c-d1d753818dfd
:ROAM_REFS: @dyke2015epigenome
:END:
#+title: Dyke, Stephanie OM and Cheung, Warren A and Joly, Yann and Ammerpohl, Ole and Lutsik, Pavlo and Rothstein, Mark A and Caron, Maxime and Busche, Stephan and Bourque, Guillaume and Rönnblom, Lars and others :: Epigenome data release: a participant-centered approach to privacy protection

Contexe: réidentification des participants par correspondance sur l'ADN = "attribute disclosure attacks using DNA"[cite:@erlich2014]

Ici: peut-on *ré-identifion donnée = attributer à un individu en faisant correspondre information génétique identifée à données anonymisée*
Anomisation totale impossible pour ADN mais donnée épigénomique plus facible

* Données épigénétiques
Principe du whole genome bisulfite sequence = reporte CpG méthylé et non métholyé cytosine

** Informatino génétique dans données de méthylation
Principe : variant qui va perturber la méthylation -> différence entre les 2 brins

Identification de CpG génomique où la methélytaion est du à un variant génétique -> a priori  39k sites qui ont > 98% predictive accuracy  et correspondent à un SNP connu

En pratique, on peut supprimer ces îlots perturbés par SNP sans perdre peaucoup d'information.
Limites (cf conclusion) mais on peut utiliser des masques
* Metadata

nomenclature HPO enlève certains détails trop spécifique lié au patient mais il faut parfois du texte libre
Pour maladies rare, date de naissance et endroit de résidence peut conduire à rédentification
Si syndrome cliniques, peossible stigmalisation

#+begin_quote
1 Is the place of residence provided (even indirectly, for example, in the project name)?
2 Is the rare disease outwardly visible?
3 How rare is the disease?
4 Does the rare disease provide information about the likely geographical location of individuals?
5 Does the rare disease provide information about ethnicity that may be considered potentially stigmatizing?
6 Was the participant aware of the potential risks of data re-identification?
#+end_quote
* Conclusion
- [cite:@erlich2014] on peut retrouver l'identité d'un individé mais il faut dans la majorité des cas données génétique d'une autre source
- Cas spéciaux: exemple du chromosome Y [cite:@Gitschier_2009]
- RNA: complexe pour retrouver
