:PROPERTIES:
:ID:       ea91e30d-7b5b-4339-89e7-85105ac97915
:END:
#+title: Les Travailleurs de la mer
#+filetags: victor-hugo review

très différente de la première : semblable à un guide touristique en
effet, il décrit de manière très positive l'ile de Guernsey. Par contre,
on a plusieurs allusions ironiques dans le roman au comportement de ses
habitants.

La seconde contient le moment le plus épique pour moi : la lutte d'un
homme face à l'océan L'introduction parle du combat contre la pièuvre
comme apogée mais j'ai trouvé cela à moitié comique du fait des erreurs
biologique (une pieuvre ne suce pas de sang avec ses ventouses), ce qui
ruine l'effet dramatique.

Sinon, très belle écriture mais parfois très "lourde", surtout dans les
passages glauques. Le personnage de Giliat est très pathétique... Tous
ces efforts sont pour rien ! À noter un épisode de voyeurisme qui m'a
rappelé Notre-Dame de Paris

Notes de la pléiade sont utiles pour ce roman ! À noter le parallèle
entre Deruchette et la propre fille d'Hugo, Adèle, qui a fugué avec un
militaire.
