:PROPERTIES:
:ID:       4a9a1a38-d2b9-4b4c-817a-a5ba69978290
:END:
#+title: Oeuvres de Duby
#+roam_tags: books review
* DONE Leçon inaugurale
du Collège de France Introduit sa notion d'histoire des sociétés, qui se
veut englobante mais différentes de l'histoire des mentalités (mal
définies)
* DONE Le Dimanche de Bouvines Intéressant car assez
révolutionnaire. Prétend qu'il est illusoire de vouloir accéder à la
réalité historique au travers des sources, car on est dépendant du biais
de la source. Utilise la bataille de Bouvines (1214) pour examiner
l'idéologie Notes : - les chevaliers sont passés d'un esprit de groupe à
solidaire entre le début XII et début XIII - la bataille était vue comme
une manière d'instaurer la paix en confrontant les adversaires une bonne
fois pour toute Dans la dernière partie ("Légendaire") : - on voit
l'évolution de l'histoire de bouvines qui se transforme en épopée
épique - et surtout que l'histoire est instrumentalisées par le
pouvoir++
* DONE Le Temps des Cathédrales L'idée de ce livre est
d'évoquer sur une longue période (tout le Moyen-Âge) l'évolution de
l'art en fonction de l'évolution des sociétés.

En pratique, on a donc une écriture très littéraire, sans aucune
référénces, hormis des citations directes des contemporains. L'objectif
est d'immerger le lecteur dans la période et dans l'état d'esprit des
contemporains.

Il m'a fallut relire plusieurs fois quelques phrases donc une certaine
concentration est nécessaire. La somme de connaissances est
impressionnante même s'il n'y a aucune référence historographique. On a
plus l'impression de voir une histoire des sociétés avec des liens
ponctuels avec l'art. Des tournures de phrases très jolies.

Sur le contenu, la théorie est que la création artistique est captée par
les élites : d'abord les princes et l'Eglise (XIe siècle) puis les rois
(de France, de Sicile) ou les pouvoirs locaux (communes italiennes)
C'est un livre prévu pour illustrer des oeuvres d'art mais qui a été
réédité en texte simple (avec quelques illustrations dans la version de
la Pléiade)

Partie conséquente sur les théories religieuses et leurs applications
dans l'art. Sur la partie plus artistique, parfois un peu trop d'élans
lyriques.

Peut-être daté (1976) mais à relire probablement
* DONE Les trois
ordres Ouvrage très dense, au style certes agréable mais nécessitant une
forte concentration. Gagnerait à être beaucoup plus résuméet difficile à
suivre (confirmé par l'auteur...)

Résumé de la thèse : - étude de la conception des 3 "ordres" au XI-XIIe
siècle dans le nord de la France - plusieurs conceptions
s'entrecroisent, résumées en : moines/clerc | _ /\\
chevaliers paysans - ces conceptions sont des idéologies plaquées sur la
société pour mieux les contrôler

Plus précisément : 1ere version en 1025 (Adalbéron de Laon notamment =
consolider un pouvoir monarchique défaillant), puis pouvoir féodal ,
puis résurgence 1.5 siècle plus tard
* DONE Guillaume le Maréchal
Petit et intéressant. Attention, ce n'est pas un biographie Pourtant,
personnage haut en couleur : s'est hissé dans la hiérarchie, retombé,
puis remomnté pour finir steward du principe, marié à une riche
héritière. Et "meilleur chevalier du monde". L'objet est d'exploiter une
source à fond, notamment ses omissions
* DONE Dames du XIIe siecle 2
arguments : - importance des femmes dans la transmission du patrimoine
(les hommes se mariaient souvent au-dessus de leur niveau) - clergé et
nobles avaient peur des femmes et de leurs femmes 1 idée principale :
impossible de savoir quelle était leur vie quotidienne Donc étude de
l'image des femmes par les hommes NB: doute de l'authenticité des
lettres Abélard <-> Héloïse. Argument : démonstration au service d'une
vision de la femme (basé sur des lettres manques. TODO: vérifier)
* DONE Histoire des mentalités Article de la Pléiade. Définition un peu
floue : ensemble des croyances, valeurs, représentations mentales des
groupes. À rapprocher à la psychologie "historique"
* DONE Le plaisir
de l'historien Court récit autobiographique
* DONE L'art, l'écrite et
l'histoire Entretien avec Duby sur sa carrière
