#+title:      VIH
#+date:       [2024-08-19 lun. 17:20]
#+filetags:   :viro:
#+identifier: 20240819T172039


Patient connu: western blot peut être négatif ! Épidémio: VIH2 = 2%
* Structure
Virus enveloppé avec dans la capside 2 brins d'ARN mnoncaténaire de polarité+
Génome :
- /gag/ code pour les protéines structurales internes
- /env/ idem mais externes
- /pol/ ADN polymérase à activité transcriptase inverse, intégrase et protéase
* Tropisme et réplication
Cellules CD4+ (lymphocytes T, monocytes-macrophages, cellules dendritiques)

1. Entrée dans la cellule : Gp120 du virus interagit avec récepteur CD4 de la cellule-cible
2. Rétrotranscription en ADN double-brin (transcriptase inverse) <- *inhibiteur transcriptase inverse*
3. Dans le noyau, intégré au génome hôte (intégrase) = latence  <- *inhibiteur intégrase*
4. Transcription en ARNm puis traduction en protéine
5. Libération des nouveaux virions <- *inhibiteur de la protéase*
* Transmission
Rapports sexuels non protégé, mère-enfant
HIV2 = rare en France, mais ~100% Afrique de l'Ouest
* Clinique
1. 2 semaine d'incubation
2. Primo :
   - asympto/pharyngite + syndrome pseudo-grippal
   - [[denote:20240818T120431][Syndrome mononucléosique]] +/- thrombopénie, neutropénie, lymphopénie puis hyperlymphocytose CD8 +,[[denote:20240723T191636][cytolyse]]
3. Latence
4. SIDA (8 ans) défini par T CD4 + < 200/mm^3 avec infections opportunistes/cancer
   - cryptococcose, pneumocystose, toxoplasmose, CMV, tuberculose
   - lymphome [[denote:20240818T121417][Epstein-Barr virus (EBV)]]  cancer [[denote:20240831T142820][HPV]]


primo: objectif

- -2Log à ??
- < 400/mm^{3}
- < 50 copies/mL à 6mois

* Diagnostic
1. Dépistage: Ac-anti VIH1 et 2 et Agp42

2. négatitf: pas d'infection si exposition > 3 semaines
3. positif: western-blot avec >= 3 anticorps et >= 2 contre les protéines de l'enveloppe (Gp160,120,41)
   - positif: contrôle 2e prélèvement pour éviter erreur d'identification
   - négatif/douteux: primo-infection ? Ag p42 et ARN VIH1
     - négatif = réaction non spécifique en l'absence de traitement ou
       exposition VIH2
     - positif = primo-infection probable

confirmation par Western blot: obligatoire pour ne pas passer à côté
d'une co-infection VIH2 !!

*Déclaration Obligatoire*  si dépistage confirmé

** Notes
- Tests rapides : Ac anti HIV1,2 : détecte un contact > 3 mois, à confirmer en labo
** IgG contre

- glycoprotéine transmembranaire (gène /env/): gp160,gp120,gp41
- capside/matrice/core : p55, p24,p18 (gène /gag/)
- enzyme virale (p66, gène /pol/)
- intégrase : p34

-> 2 bandes /env/ et 1 bande /gag/ pour /pol/

- Plutot précoce : glycoprotéine, p55,p24
- Plutôt tardif : p34

* Bilan initial
Séro EBV, CMV

* Traitement
1 ou 2 inhibiteur nucléosidique transcriptase inverse + {1 non nucléo ou 1 intégrase}

- 1ere ligne :
  - dulotegravir + 2 inhibiteur nucléosidique.
    - Attention: abacavir : contre indiqué HLAB*5701 risque
      d'hypersensibilité
  - Sinon efavirenz - 2 INTI
  - Enfant : raltégravir + 2INTi

CD4+ < 200/mm^3 : cotrimoxazole pour les infections opportunistes. Prioritaires sur le traitement antirétroviral !
** Objectif
T CD4+ > 500/mm^3 et 0 symptômes
- +1 mois : -2 log10 copies par mL
- +3 mois : < 400 copies/mL
- +6 mois : indétectable
Primo:
- objectif = diminuer contagiosité.
- Utiliser traitement avec forte barrière génétique
- Si possible, traitement par ?? pour faire chuter la charge virale
** Prévention
- Pré-exposition : PrEP
- grossesse : traitement + zidovuline/ténofovit pendant le travait et traitement post-exposition de nouveau-né, /sans allaitement/
- [[denote:20240831T151020][Accident d'exposition au sang]] ou sexuel
** Notes
  EI: tenofovir = nephrotoxique, sauf forme alafénamide daru = pb cardio vasculaire

  Note: bithérapie possible dès début. Sinon allègement avec CV
  indétectable depuis 2 ans


* Résistance
:PROPERTIES:
:CUSTOM_ID: résistance
:END:
Lamivudine, emtricitabine = mutation M134 V/I

- codong ATG donne soit ATA (I) sout GTA (V): le premier est plus
  fréquent à cause d'APOBEC

  APOBEC= enzyme qui protège des infection virale : édition ARN C-> U
  qui rend la réplication quasi-impossible. Le VIH a ViF qui désactive
  cette enzyme. NB: APOBEC peut éditer le génome intégrer (peu d'effet ?
  contrairement à EBV)
