* NBIA
Neurogeneration with brain iron accumulation = progressive
extrapyramidal with accumulation of iron in the brain on MRI, usually
basal ganglia.
- 85% have a genetic basis and most of these are due to 4
genes: /PKAN2/,/PLA2G6/, /C19orf12/, /WDR45/.
- In total, 9 genes are reported.
- Classification is based on genes.
- Clincal and MRI may orient to a specific gene (Table 19.2 in [cite:@haylick2018]).
- PKAN is half of the case and its estimated prevalence is 1/1 000 000 [cite:@gregory2002]
BPAN = first X-linked, WDR45 and distinc phenotype
- suspicion : 7 patients in [cite:@gregory2009]
- confirmed + molecular basis in [cite:@haack2012] [cite:@hayflick2013]
* Beta-propeller protein associated neurodegeneration
** Phenotype [cite:@hayflick2013]
*** Clinical
- All (23): global developmental delay in infancy/early childhood + ID as adult
- Most children : made slow developmental gains over time. Developmental quotients ranged from 30–50, with severely limited expressive language in childood.
- Most : clumsy children (broad-based or ataxic gait) but generally healthy.
- 6: spasticity.
- 13: epilepsy in childhood requiring treatment
  - Various seizure types
  - EEG changes
- comorbid features in childhood : seizures, spasticity, disordered sleep and stereotypies that further define the BPAN phenotype.
- The prominent parkinsonism observed in BPAN justifies the designation of WDR45 as a PARK family gene

- all : neurological deterioration in adolescence/early adulthood: dystonia, parkinsonism, and new cognitive decline.
  - mean age 25.3 years (range 15–37 years).
  - parkinsonism = prominent bradykinesia, rigidity and freezing of gait; however, tremor was noted in only two subjects.
  - Dystonia common in adolescence
  - L-dopa is very efficent but only for a short period of time. Side effects led to interruption in a few years
  - deterioration of cognition concomitant with onset of the movement disorder, with progressive loss of limited expressive language skills advancing to severe dementia in end stages.
- life expectancy :
  - 18 living (16 to 44 years)
  - 5 female died during 30-50 years
    - 1 ; severe parkinsonism and dysphagia at 48 years of age (11 years after neurological deterioration)
    - 2 aspiration pneumonia
    - 2 unknown causes

  - Subset : disordered sleep, ocular defects and Rett-like hand stereotypies (Table 1).
*** MRI
- all = increased iron deposit in substantia nigra and globus pallidus (reports not seens)
- 13 MRI from 11 patients seen
  - T2 hypointense : substantia nigra and globus pallidus
  - all 13 : substantia nigra : more hypointense
  - 6/10 global pallidus hypointensity variable
  - T1: **halo** in substantia nigra and cerebral pedoncule (center = dark, hyperintensite haloi)
    -> unique to BPAN ?
  - 19/23 : generalized cerebral atrophy
  - 6/23 cerebellar atrophy
*** Neuropatho : 1 patient
- gross: mild cerebellar atrophy, thinned cerebral peduncles, dark/grey brown in substantia nigra
- microscopic (globus pallidus, substantia nigra)
  - iron
  - numerous large axonal spheroids, siderophages, reactive astrocytes
  - severe neuronal loss
  - putamen, thalamus, granular cell layer also affected
  -  tau-positive neurofibrillary tangles in hippocampus, neocortex, putamen, hypothalamus
** Genetic basis in Haack2012
- On chromosome X but no X-linked pattern : male and females are affected equally
Haack2012 hypothesis:
  - somatic mosaicism in male (germline likely not viable)
  - female somatic + germline
  - severity based on when and where the mutation occurs in embryogenesis (like in Rett's
syndrome)
  - in favor :
    - 2 DNA traces of differents peaks on 1 male (2 amplicons on exon 2)
    - skewed X inactivation
      - in favor : skewed in 10/12 women with WDR45 mutation

* References
- [ ] [cite:@Aring_2021] review + physiopathology of WDR45 deficit
  Design : in vitro model of neuronal fonction (SH-SY5Y neuroblastoma)
  - modified iron uptake in cells
  - possible link to increased iron uptake in neurons
  - impaired ferritinophagy
  - mitochrondrial iron accumulation + altered mitochrondrial metabolism (possible link to neuronal cell death, neurodegenration)
- [X] [cite:@haylick2013] phenotype details of the cohort in [cite:@haack2012]
  - The protein encoded by WDR45 is characterized as a beta-pro- peller scaffold that serves as a platform to enable specific protein– protein interactions that are important in autophagy.
- [X] [cite:@haack2012] first description of WDR45 in NBIA 19 mutations, 20 subjects.
  data: see[cite:@hayflick2013]
  MRI with arrows :)
- [ ] Gregory2002
- [X] Gregory2009
  7 patients: new phenotype
- [ ] Gregory2019
- [cite:@Lee_iron_2021] c.974-1G>A étude fibroblaste
- [cite:@lee_autophagic_2021] c.977-1G>A effet autophage fibroblaste
- [cite:@Ji_2021] autophagosome maturation into autolysosomes in neural cells
- [cite:@Kano_2020] revue 1 patiente
