Asgarov Fatima^{1}, Cecilia Altuzarra^{2}, Daniel Amsallem^{2} ,
Bénédicte Gérard^{3}, Patricia Fergelot^{4}, Alain Verloes^{5}, Juliette
Piard ^{1, 6}.

Compléter les affiliations

1- Centre de Génétique Humaine, Université de Franche-Comté, CHU,
Besançon, France

2- Service de Neuropédiatrie, CHU, Besançon, France

3-

4-

5-

6- Unité de recherche en neurosciences intégratives et cognitives EA481,
Université de Franche-Comté, Besançon, France

Corresponding author

Dr. Juliette Piard, Centre de Génétique Humaine, Centre Hospitalier et
Universitaire

2, place Saint-Jacques, 25000 Besançon, France

E-mail: [[mailto:jpiard@chu-besancon.fr][_jpiard@chu-besancon.fr_]]

Abstract

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:
Neurodegeneration with brain iron accumulation (NBIA) is a group of
inherited neurologic disorders characterized by abnormal accumulation of
iron in the basal ganglia. (Gregory and Hayflick, 2013).

NBIA includes the diagnoses of pantothenate kinase-associated
neurodegeneration (PKAN), phospholipase-associated neurodegeneration
(PLAN), fatty acid hydroxylase-associated neurodegeneration (FAHN),
mitochondrial protein-associated neurodegeneration (MPAN), Kufor Rakeb
syndrome, aceruloplasminemia, neuroferritinopathy, and beta-propeller
protein-associated neurodegeneration (BPAN).

BPAN is an X-linked condition due to pathogenic variants in /WDR45/
which encodes the WD repeat domain phosphoinositide-interacting protein
4 (WIPI4) (Kaleka et al.). WDR45 protein functions as a beta-propeller
scaffold and plays a putative role in autophagy through its interaction
with phospholipids and autophagy-related proteins. Loss of WDR45
function has been linked to defects in autophagic flux in patient and
animal cells. However, the role of WDR45 in iron homeostasis remains
elusive (Seibler et al., 2018).

Main clinical signs of BPAN are seizures, developmental delay,
intellectual disability with absent to limited expressive language and
behavioral disturbances with Rett syndrome-like features (Gregory and
Hayflick, 2013).*Seizures* are common during childhood, often starting
as febrile seizures then multiform [cite:@nishioka2015]. During
adolescence and early adulthood seizures tend to become less prominent,
while cognitive decline, progressive parkinsonism and dystonia emerge as
characteristic findings.

A clear female predominance has been described in patients with BPAN and
lethality for males with germline hemizygous variants was initially
suggested The description of few male cases was attributed to somatic
mosaicism. However, observations of affected male patients recently
described with germline variants inherited from their asymptomatic or
pauci-symptomatic mother were challenging this hypothesis.

Here, we report two unrelated male patients with missense variants in
/WDR45/ and a moderate phenotype. While two siblings (brother and
sister) and their mother shared the first variant, the second variant
occurred /de novo/.

* Material and methods
  :PROPERTIES:
  :CUSTOM_ID: material-and-methods
  :END:
* Participants
  :PROPERTIES:
  :CUSTOM_ID: participants
  :END:
* Written informed consent was obtained from all participants.
  :PROPERTIES:
  :CUSTOM_ID: written-informed-consent-was-obtained-from-all-participants.
  :END:
* Methods
  :PROPERTIES:
  :CUSTOM_ID: methods
  :END:
* NGS (Family 1)
  :PROPERTIES:
  :CUSTOM_ID: ngs-family-1
  :END:
* NGS (family 2)
  :PROPERTIES:
  :CUSTOM_ID: ngs-family-2
  :END:
* Sanger sequencing
  :PROPERTIES:
  :CUSTOM_ID: sanger-sequencing
  :END:
* Functional study (?)
  :PROPERTIES:
  :CUSTOM_ID: functional-study
  :END:
* Results
  :PROPERTIES:
  :CUSTOM_ID: results
  :END:
* Clinical features
  :PROPERTIES:
  :CUSTOM_ID: clinical-features
  :END:
*_Family 1_*

*Patient 1* was the first child of non-consanguineous parents of French
origin (figure 1). The pregnancy was uncomplicated. He was born at 36
weeks of gestation with a birth weight of 3010 g ( +1,5 SD), a birth
length of 48 cm (+0,5 SD) and a birth occipito-frontal-circumference of
34 cm (-1 SD). In the neonatal period, he had poor suckling and two
episodes of neonatal bronchiolitis requiring hospitalization. The
initial motor development was satisfactory. Autonomous walking was
acquired at 17 months. A language delay and fine motor difficulties were
noted at kindergarten. At the age of nine, the language was still very
poor. He said a dozen of words without association. Toilet training was
not acquired at night. He was oriented in a specialized school at the
age of 6. He can't read or write. Fine motor skills remain difficult
(image 1(A)). Clinical examination showed an overlapping of left toes, a
mild hypertonia of lower limbs, and mild dysmorphic features with
bilateral epicanthus and hooded eyelids. He had no epilepsy. The
metabolic screening did not show any abnormalities. Ophthalmologic
examination and hearing test were all normal. A brain MRI at age 7
showed bilateral and symmetric hypersignal of dentate nucleus in T2 with
no signs of iron deposition (figure 2).

*Patient 2* is the sister of P1. She was born at 38 weeks of gestation
with a birth weight of 2760 g (+1 SD), a birth length of 50 cm (-0.5 SD)
and a birth occipito-frontal-circumference of 32.5 cm (-1.5 SD). She
walked at 14 months. She presented a language delay and learning
difficulties. She is monitored in speech therapy. Toilet training of
night was acquired at the age of 9. Clinical examination showed a round
face, thick hair, short forehead and a right preaurical fistula. She has
corrective glasses for hyperopia and astigmatism (image 1(B)).

*Patient 3* is the mother of patient 1 and 2. She presented learning
difficulty at school and an episode of depression. She is completely
autonomous in daily life but her level of education is very inferior to
that of her two healthy brothers. A brain MRI realized after transient
visual disturbances indicated a left cerebellar lesion without expansive
character.

*** _Family 2_
    :PROPERTIES:
    :CUSTOM_ID: family-2
    :END:
*Patient 4* was the second child of healthy non-consanguineous parents
of Algerian and French origins. He had three healthy siblings.He was
born at 38 weeks of gestation with a birth weight of 3110 g ( -2.5 SD),
a birth length of 50,5 cm (-1 SD) and a birth
occipito-frontal-circumference of 34 cm (-1 SD). Suckling difficulties
and generalized hypotonia were noted in the neonatal period. .
Psychomotor milestones were delayed : head control was obtained at 4-5
months, sitting at 10 months and standing with support at 18 months of
age. At age 4, he was not ambulatory and had no speech. A gluten-free
diet was set up for gluten intolerance No seizure was reported. When
examined at age 4, he weighed 13.6 kg (-2SD), was 79 cm tall (-1SD) and
had an OFC of 47.5 cm (-3SD). There were no dysmorphic features.
Neurological examination showed axial hypotonia, pyramidal syndrome in
the lower limbs, mild peripheral hypertonia and bilateral nystagmus.

Biological workup included normal blood parameters, hepatic enzymes,
renal and metabolic screening. Ophthalmologic examination, hearing test,
EEG, and cardiac ultrasound were all normal. A brain MRI, performed at
age four, showed delayed myelination, ventricular and pericerebral
spaces enlargement, bilateral hypersignal of dentate nucleus in T2 and
bilateral hypersignal of subcortical white matter in the temporal
regions. Brain MRI repeated at age 6 showed additional cerebellar
atrophy, symmetrical T1 hyposignal and T2 hypersignal of dentate
nucleus. There were no signs of iron deposition.

* Genetics studies
  :PROPERTIES:
  :CUSTOM_ID: genetics-studies
  :END:
*_Family 1_*

Karyotype, array-CGH and fragile X study didn't show any abnormalities.
High-throughput sequencing study identified the hemizygous c.697C> T ;
p.(Arg233Cys) variant in /WDR45./Extensive family segregation study
showed that the variant was present at the heterozygous state in his
mother and his sister and was absent in his maternal uncles and maternal
grand-parents. ( Figure 1). Thus, the variant occurred /de novo/ in his
mother.

*_Family 2_*

Karyotype, array-CGH and fragile X study didn't show any abnormalities.
NGS study revealed the presence of the hemizygous (NM_007075.3):
c.698G>T ;p.(Arg233Leu) variation in /WDR45/. Parental study indicated
that the variant occurred /de novo/.

* Neuropsychological assessment
  :PROPERTIES:
  :CUSTOM_ID: neuropsychological-assessment
  :END:
*Patient 1.* Listening and understanding skills revolve around
understanding multi-part directions. It can make sentences with a
subject and a verb, but the sentence structuring ends there. The lexical
stock articulated and understood by all is limited. He is able to copy
some simple words. He can write his first name from memory. He shows
emerging skills in his socialization. The total psyco_motor results
indicate that he is limited in his cognitive abilities, with an overall
score that places him in the zone of average impairment.

*Patient 2.* A slight intellectual disability was indeed found during
the initial assessment (M. Campello, November 2018, CHU) while a
multiple learning disability was highlighted on the last assessment.

** Discussion
   :PROPERTIES:
   :CUSTOM_ID: discussion
   :END:
Since the causative gene was first identified in 2012, more than 80
caseshave been published in the literature. The majority of individuals
described to date are severely delayed with prominent expressive speech
impairment, epileptic encephalopathy, autism, and/or a Rett-like
syndrome. However, the phenotype of BPAN is expanding recognize with
milder cases emerging, thus expanding the phenotypic spectrum of this
condition.

Among reported cases, 20 male patients were described. Four of these
patients were mosaic, however they did not show less severe phenotype
compared to others.

Generally, female patients present less severe symptoms compared to
males. Among described cases, 93% of female cases present delayed
development, 53% of them have epilepsy and 57% have parkinsonism.
However all male patients present intellectual deficiency and 70% of
them have epileptic symptoms. Moreover all of these symptoms appears in
early ages in male cases compared to females.

Most of described mutations of WDR45 are /de novo/ mutations. 2
inherited male cases were been reported. In 2016 Zarate and al.,
detected a new in-frame deletion in the WDR45 gene (c.161_163delTGG, p.
(Val54del)) which was in hemizygous, heterozygous and mosaic states in
the brother, sister and mother, respectively. The variant was not found
in the father of the patients. The patient was a 20 year old male with a
history of global developmental delay and epilepsy. He had never been
able to walk independently and relies on the wheelchair. He was
completely dependent on the activities of daily living. He had several
contractures with limited range of motion. At age 20, her brain magnetic
resonance imaging (MRI) revealed severe diffuse brain atrophy and
findings suggesting iron deposition in the globus pallidus and
substantia nigra. His 14-year-old sister presented static
encephalopathy. Developmental problems appeared during the first year of
life. She only knows a few colors and can count to 20. She is able to
dress and undress, use utensils, and speak in short sentences. An MRI of
the brain revealed a deposit of iron in the basal ganglia. The mother of
patients was in good health.

Nakashima et al. have been reported a family with c.400C> T mutation.
First patient which was a 7-year-old boy and was the first child of
outbred parents. Psychomotor delay was identified by the lack of visual
fixation and ocular follow-up early in the postnatal period. At the age
of 5 months, a retinitis pigmentosa-like eye fundus was noted and
convulsions with spasms began. At 7 months, he presented with cluster
epileptic spasms. Brain MRI showed delayed myelination and generalized
cerebral and cerebellar atrophy at 8 months of age.At 4 years and 5
months, T2-weighted brain MRI did not detect apparent iron deposition,
but l Sensitivity-weighted imaging (SWI) involved iron deposition
(hypointensity) in the globus pallidus and the substantia nigra. At
present, the patient is bedridden and unable to control his head. A
profound intellectual disability has been recognized and he is unable to
pronounce meaningful words. His dizygotic twin sister had developmental
delay and intellectual disability. At 9 and 10 months and 2 years, she
had had complex febrile convulsions. At age 3, his EEG showed frequent
focal spikes or polyspike, but brain MRI at 2 years was normal. She
presented with mild hypotonia and no spasticity. Its development
milestones have been delayed. She could hold out at 2 years and 3 months
of age. She is unable to pronounce meaningful words. The mother of
patients was mosaic for mutation. She was in good health. 3 months of
age.

The principal anatomical indication of BPAN is the accumulation of iron
in in the basal ganglia which could be detected using radiography.
Iron-sensitive sequences, such as SWI, GRE, and T2*, should be used as a
first-line diagnostic investigation to identify the characteristic
changes in BPAN. By the time clear neurologic features are present, the
brain MRI almost always shows characteristic changes, although iron may
be visible only later in the disease course (Gregory and Hayflick,
2013). MRI in early childhood is nearly always reported normal, although
generalized cerebellar and cerebral atrophy and corpus callosum thinning
have been already described. As the disease progresses, T2w, but mainly
T2* and susceptibility‐weighted imaging sequences, reveal hypointensity
as a sign of early‐stage iron deposition. Iron accumulates mainly in the
SN and, to a lesser extent, in the GP. Prominent SN hypointensity is
often evident as a thin, dark central band surrounded by a peripheral
hyperintense halo (halo sign) on axial T1w images (Russo et al., 2019).
Neuropathologic findings include axonal spheroids in the CNS and, in
some types, in peripheral nerves. In both of indentified cases in this
study, bilateral and symmetric hypersignal of dentate nucleus in T2 was
observed in childhood without any signs of iron deposition which
correlated with recent data of the literature.

BPAN is an X-linked condition, the existence of milder female cases is
conceivable by way of possible X-inactivation. However, the existence of
these mildly affected individuals could also potentially be reflective
of mutations that have less of a detrimental effect on protein function.

The phenotype of BPAN is expanding and it is important to recognize that
a spectrum of severity with milder cases is emerging. There are three
cases were reported which clearly describe patients with milder BPAN
phenotypes: first, a 17-year-old female who attends a basic stream in
high school, is verbal but has issues with sentence structure, grammar
and articulation, and with no motor delays or seizures, variation
c.251A>G (p.Asp84Gly) (Long et al., 2015).; the second, a 36-year-old
female with an IQ of 45, who graduated from high school with assistance
and has intelligible speech, and had epilepsy that remitted at menarche
c.64DelT  (p.Cys22Alafs*16) (Fonderico et al., 2017).; third, 6-year-old
girl presented with mild motor delay and moderate speech delay, who was
reported to have had normal development up to 2 and a half years old.
The patient has difficulties in both receptive and expressive language
but can currently say upwards of 500 words and can speak in sentences.
Sequencing of the /WDR45/ gene revealed that the patient is heterozygous
for a /de novo/ variant c.299T>C (p.Phe100Ser) (Chard et al., 2019).
These observations suggest that the severity of the phenotype is
dependent on the location and type of mutation which could modify the
protein function more or less. However in general, a milder phenotype is
observed in females with point mutations compared to deletions, in males
any type of mutation results in a severe phenotype. Here, we reported
that a same mutation in male results more severe phenotype than female
by demonstrating the example of the family two where the mother of the
patient 1 was with normal phenotype without any symptoms. Finally, we
could conclude that the both mutations which were resulted with the
change of the same amino acid (233Arg) in the protein were pathogen in
male patients.

** References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:
