​#biochimie ## Localisation, rôle physiologique

L'hémoglobine sert à transporter l'oxygène des poumons aux tissus et du
CO_{2} des tissus vers le poumon. C'est une protéine avec 4 sous-unités,
chacune comportant une molécule d'hème avec un atome de fer. Chaque hème
peut fixer une molécule d'oxygène.

L'hémoglobine totale est la somme de tous les fractions d'hémoglobine
mesurées : oxyhémoglobine, désoxyhémoglobine, méthémoglobine,
carboxyhémoglobine (voir fiches idoines).

** Tissus/organes de production et d'élimination
:PROPERTIES:
:CUSTOM_ID: tissusorganes-de-production-et-délimination
:END:
Les chaînes de globine sont synthétisées dans les érythroblastes. Après
la lyse des hématies vieilles, les hémoglobines sont catabolisées dans
le système réticulo-histiocytaire dans la rate, foie et moelle osseuse.
les macrophages du foie vont libérer l'hémoglobine qui va perdre des
molécules d'hème, qui seront oxydées avec une transformation de
porphyrine. Une partie sera conjuguée pour être éliminée dans la bile.

** Valeurs de référence (adulte)
:PROPERTIES:
:CUSTOM_ID: valeurs-de-référence-adulte
:END:
Adulte 12-18 g/dL

** Principe analytique de mesure
:PROPERTIES:
:CUSTOM_ID: principe-analytique-de-mesure
:END:
Chaque dérivé de l'hémoglobine a un spectre d'asorption spécifique. On
mesure donc l'absorbance aux longueurs d'onde caractéristique.

** Principales interactions analytiques
:PROPERTIES:
:CUSTOM_ID: principales-interactions-analytiques
:END:
- hyperlipémie (augmentation)
- émulsions lipidiques (augmentation)
- congélation avec de l'azote liquide

** Augmentation et diminution
:PROPERTIES:
:CUSTOM_ID: augmentation-et-diminution
:END:
- Diminution : anémie par perte de sang, destruction de globules rouges,
  incapacité à en produire de nouveau
- Augmentation = polycthémie primaire ou secondaire (hypoxie,
  déshydratation, complication de transfusion)

* Autres hémoglobines
:PROPERTIES:
:CUSTOM_ID: autres-hémoglobines
:END:
** Méthémoglobine
:PROPERTIES:
:CUSTOM_ID: méthémoglobine
:END:
Cette dyshémoglobine a son fer oxydé en Fe^{3+}. Eelle est donc
incapable de se lier à l'oxygène.

Valeurs de référence (adulte): < 2%

** Hémoglobine réduite
:PROPERTIES:
:CUSTOM_ID: hémoglobine-réduite
:END:
Cette dyshémoglobine peut apporter plus d'oxygène aux tissus cellulaire
si l'oxygénation pulmonaire a été améliorée.

Valeurs de référence (adulte) < 5%

** Oxyhémoglobine
:PROPERTIES:
:CUSTOM_ID: oxyhémoglobine
:END:
Fraction de l'hémoglobine saturée en oxygène qui apporte effectivement
de l'oxygène aux tissus Valeurs de référence (adulte) 94 - 97 %.

** Sulfhémoglobine
:PROPERTIES:
:CUSTOM_ID: sulfhémoglobine
:END:
Cette dyshémoglobine est un composé stable d'hémoglobnie et de sulfure.
Elle ne peut pas apporter d'oxygène aux tissus cellulaires. Valeurs de
référence (adulte) < 22% ## Mesure Absorption spectrale
