:PROPERTIES:
:ID:       9160ba80-117b-4434-acc9-13676a534da0
:END:
#+title: Bactéries
#+filetags: personal medecine
* Résistante
PLP = paroi externe de la membrane plasmique. Sert à synthétisé le peptidoglycane = composant de la paroi. Les beta-lactamine vont inhiber la synthèse de peptidoglycane. En cas de PLP2a, moins d’affinité aux beta-lactamine.
https://pharmacomedicale.org/medicaments/par-specialites/item/beta-lactamines-penicillines-cephalosporines
* Bactéries
** Staphylocoques
*** Résistances
- β-lactamine : production pénicillinase (BlaZ)> 90%
- résistance méticilline (staph coag négative >> aureus) via
  - la Staphylococcal Cassette Chromosome mec (SCCmec) [= zone génomique comprenant /mecA/ qui code pour la protéine PLP2a ( [[*Résistante][Résistance]]).
  - Nouveau gène mecC: code PLP2c
  - S. aureus : 15-20% résistant méticilline
- Macrolides-Lincosamide-Streptogramine-Kétolide (MLSK)  : modification de la cible surtout (modification/mutation ribosome)
  - phénotype MLS_B: inductible ou constitutionnel
- 3 phénotype de résistance aux aminosides (inactivation enzymatique = 5% SAMS mais 80-90% SARM)
- glycopeptide : exceptionnel
*** Staphylococcus aureus
Cocci Gram+ en amas : aérobie +/- anaérobie. Immobiles. non capsulé, non sporulé

**** Facteurs de virulence
Associé à la paroi:
- *coagulase* liée = récepteur au fibrinogène, sur la paroi bactérienne -> diag (test d'agglutination)
- protéine A: liaison aux immunoglobuline, protection contre la phagolytose

Excrété
- hémolysine : lyse des hématies (β-complète)
- coagulase libre = excrétée, clive le fibrinogène -> embole septiques. Différence avec les staph. à coagulase négative (S. epidermidis)
- staphylokinase : libère bactéries des emboles
- *toxine* :
  - leucocidine de Panton et Valentine (LPV) -> leucotoxique dermonécrotique
  - toxine du choc staphylococcique (TSST1-1 -> activation lymphocytes T)
  - exfoliatines -> érythrodermie bulleuses
  - entérotoxines thermostables -> TIAC

**** Habitat
- 30% porteur sain (transitoire ou non)
- Transmission intra-humaine par les mains ou indirectevement (vêtements...)
- Commensal : microbiote nasal, oropharyngé, digestif, cutané (aisselles)

**** Clinique
- Porte d'entrée = cutanée <-> site de portage/infection
- Infection communautaires, associées aux soins
- Infection toxiniques :
  - LPV : infection cutanée, pneumonie nécrosante
  - TSST1 = choc toxinique avec érythrodermie. Entrée = vaginale ou cutanée
  - exfoliatine: impétigo bulleux, syndrome d'exfoliation généralisée
  - entérotoxine = diarrée à +2h ou 4h, TIAC
- Infections suppurative
  - cutanée superficielle (furoncle, impétigo, folliculite) ou profondre (abcèse, fasciite)
  - bactériémie, endocardite
  - infections profondes : ostéo-articulaire, pneumopathie, neuroméningées (abcès)
**** Diagnostic
- Culture : non exigeante
  - gélose sang 24h: *beta-hemolytique* (hémolyse total)
  - Chapman (mannitol + NaCl) : rouge -> jaune avec NaCl
  - catalase +, oxydase-, DNAse + (à la différece des tretop à coagulase négative)
**** Sensibilité et résistance
Résistance fréquent à l’hôpital
- β-lactamines :
  - phénotype sauvage sensible
  - pénicilinase > 90% des souches (disque FOX de pénicilline g): résistance pénicilline G, V, A -> ajout d’inhibiteur de β-lactamase
  - SARM = gène mecA : PLP2 additionnelle -> résistance à toutes les β-lactamines. Souvent multirésistance aminoside, macrolide, fluoroquinolonie
    -> vancomycine en 1ere intention
- Aminoside : sauvage sensible, résistance acquise par inactivation enzymatique
- Glycopeptide : sauvage sensible, phénotype gIA/hétéroGISA avec sensibilité diminusée, phénotype gRSA (résistance)
*** Staphylococcus saprophyticus
- Cocci gram + en amas, catalase positive, nitrate réductase négative
- Urine :rose sur milieu chromogène mais identification spectromètre de masse/biochimiue
- Sensbilité nature à la plupart des antibiotique anti-staph
- Résistance naturelle : fosfomycine, acide fusidique, novobiocine
- Résistance acquise fréquente : péni G, érythromycine
** Campylobacter
- Répartition mondiale
- Une des cause les plus fréquentes des diarrhées infectieuses bactériennes communautaires
- Microbiote digestive de nombreux animaux : /jejuni/ = volaille
- transmisison animale -> homme par *alimentation* : surtsout *jejuni*, *coli*, *fetus*
*** Pouvoir pathogène
- douleur abdo
- *gastro-entérique aigue fébrile* : (diarrhées aqueuse voire mucosanglange, fièvre , vomissement)
- bactériémée
- syndrome de l'intestin irritable
- syndrome de guillan-barré
*** Diagnostic bactério
- selles (copro): PCR, immunochromatographique
- sang (hémoc)
  - examen direct : en forme de S, non sporulé, en "vol de moucheron"
- culture : sélectif en microaérobie
- *oxydase+*, catalase soudvent +
- MALDI-TOF
*** ATBgramme
- résistance naturelle : vancomycine, pénicilline G, M, céphalosporine, triméthoprime, streopgramine B
- acquise : érythor, tétracycline, quilonone, amox
*** Traitement
- déshydratation
- si fièvre > 38°, sang dans les selles, enfants, persnnes agée, femmes enceintes: *azithromycine*
- systémique : FQ ou beta-lactamine + aminoside sur documentation
*** Prévention: hygiène (eau, alimentation)
** Proteus mirabilis
- Bacille gram négatif, *mobile*, oxydase négatif, nitrate-réductase positive
- Brun sur milieu chromosome, β-glucuronidase et β-glucosidase négative
- Désaminase positi, indole négative
- Sensible antibio actif sur bactille gram négatif
- Résistance acquise : pénicillnase, BLSE, céphalosporinase de haut niveau, carbapénémase
** TODO Pseudomonas aeruginosa
Bacille Gram négatif, très mobile

Origine : environnement++. saprophyte de,s milieux humaine
*Opportuniste* : 19= dse infectieuses hopsitalation
- infection nosocomiale (matériel) ou . 1ere bactérie en réa
- colonisation/infection bronchopulmonaire chronique sur mucoviscidose

Facteurs de virulence : exotoxine, exoprotéines, hémolysine
Facteur d'adhésion
Forte capacité à former des biofilms
*** Quand réaliser un antibiogramme
- suspicion responsable d'infection
- colonisation de patients fragile (ID, intbués)
- pulmonaire isolé de patients muco, BPCO, DDB
*** Diagnostic
- Pousse 24h à 37% sur milieu non sélectif.
- Milieu sélectif : cétrimide
- Oxydase positif (!= entérobactéries) -> test rapide pour différencier les 2
*** Résistance
Naturellement plus résistante que d'autres Bacille gram -

  - Catalase positif - lactose négatif
**** Résistance naturelle :
  - amox
  - C1G, C2G, *céfotaxime* (/! utilisé pour mécanisme/), ceftriaxone, *ertapénème*
  - anciennes FQ : nofloxacine, péflox, ofloxanie
  - cotrimoxazole
  - nitrofurantoine
  - macrolides
  - azithromycine

Association de plusieurs mécanisme (synérgie/complémentaire)
- β-lactamase AmpC (large spectre, inductible)
- enzyme modificatrice aminoside
- effluxs actif (mexAB-OprM, MexXY/OprM)
- imperméabilité (porine OpriF)
**** Résistance acquise
- Surproduction : efflux, β-lactamase AmpC, alétaration porine...
- gène codant β-lactamase

- Attention: certaines souches accumulent des résultats

- β-lactamase transférable : pénicillinase, BLSE, carbapénémase

  Quand chercher BLSE ?
  - synergie ceftazidime/cefepime et acide clavulanique
  - synergie ceftazidime/cefepime et impiénoèmeacide clavulanique
  Quand chercher carbapénémase ? (> 90% cabarpénème)

**** Antibiotique
- β-lactamine:
  - ceftazidime +/- avibactame
  - ticarcilline +/- clavulatane, pipéracilline +/- tazobactame,
  - céfépime
  - ceftolozane + tazobactame
  - imipénème, méropénème
- Aminoside
- FQ: ciprofloxacine, lévofloxacine
- colistine
** Streptocoques
Infections graves = /pyogenes/, /pneumoniae/.
Commensal mais opportunites (immunodépression) : oraux (*endocardite, SDRA)
*** Classification
- Hémolyse : α  partielle, β = totale.
- Lancefield : classification selon un composé de la paroi bactérienne (polyoside C) avec mise en évidence de l'antigène par agglutination.

En première approximation :
- α-hémolyse = non-groupable
  - /pneumoniae/ résistance par chimérisme PLP (acquis)
  - autres anginosus, mitis, sanguinis, bovis, salivarius, mutans
- β-hémolyse = groupable. Les plus importants
  - Groupe A = S. pyogenes. Cause d’angine++. *Pas de résistance aux β-lactamine*
  - Groupe B = S. agalactiae
   Infection materno-foetale ++ (note: l’antibioprophylaxie marche chez les nouveau-né mais seulement pour les infections avant 7 jours)
  - C : /dysagalactia/ (rarement /equi/)
  - G : /dysgalactia/, /canis/

/Note/: certaines sous-espèce de Lancefield peuvente être alpha-hémolytique
*** Résistances
- α-hémolytique : dépistage disque péniG: si résistant, CMI d’une β-lactamine (amox/céfotaxime/ceftriaxone)
- *β-hémolytique: pas de résistance β-lactamine*
- S. pneumonia : 25% résistance acquise β-lactamine (sensibilité diminuée)
- pas de β-lactamase
- MLSK (Macrolides-Lincosamide-Streptogramine-Kétolide): modification cible++, efflux, protection ribosomale
- pas de résistance streptococques
- linézode
*** Classification d’Ambler
A. BLSE
   - résistance pénicilline, C1, C2, C3G
   - sensible inhibiteur β-lactamase et carbapénème
   - détecté par ceftazidime + acide clavulanique
B. Métallo-beta-lactamases
   - résistance comme B. + carbapénème
C. ampC céphalosporinase
   - résistance BLSE + céfoxitine + inhibiteur β-lactamase
   - sensible carbapénème
   - détecté céfoxitine
D. oxacillinase
   - sensible β-lactamase
*** Streptococcocus pyogenes
Cocci gram+ en chaînettes, capsulé, non sporulé, immobile

Réservoire pharyngé. Transmission = aérienne, contact plaie infectée, accouchement.
**** Facteurs de pathogénicité
résistance à la phacogytose
- protéine M
- encapsulation
Facteurs de virulence
- enzyme :hyluronidase, stroplysine O et S (favorisent l’invasion tissulaire)
- exotexonie :  activation et prolifération d’une sous population lymphocytes T -> cytokine proinflammatoires
- Streptolysine = hémolyse β-complète
- toine érythrogène : hypersensibilité retardée à la scarlatine
**** Habitat
Strictement humaine, surtout pharyngé +- peau, vagin...
Pyogène = responsiable d’infections suppurées
**** Clinique
- non invasive = angine érythémateuse/érythémato-pultacée, otite moyenne aigüe de l’enfant, scalratine, infection cutanée
- invasive : cutanée sévère (fasciite nécrosante), septicémie, choc toxique streptococcique
- complications post-streptococciques  (rare) = immunologique :
  - rhumatisme articulaire, glomérulonéphrite aigüe, érythème noueux
**** Diagnostic
- bactérie exigeante -> gélose sang +/- ANC (inhibe Gram-)
- β-hémolyse
- Résistance potochine, sensbile bacitracine
- Catalase -, oxydase -
**** Sensibilité, résistance
- β-lactamine : sensible
- macrolide : sauvage sensible, résistance par mécanisme d’efflux, modiifcation cible ARN23S
*** TODO Strepto agalactiae
*Naturellement sensible β-lactamine*
*** Strepto. pneumoniae
Gram+ diplocoque encapsulé à multiplication extracullaire.
Classification selon la capsule (vaccins)
**** Habitat
Voie respiratoire supérieure
Transmission goutelette, interhumaine
**** Pathogénicité
- adhérence cellules épithélium rhinopharynx
- facteurs de virulence non capsulaire
- évasion à la phagocytose
- actionation complément, cytokien inflammatoire
**** Résistance
- β-lactamine: Selon les PLP (!inutile d’ulitiser les inhibiteurs de betalactamase)
- sensibilité possiblement dimunée aux fluoroquinolones
- Gènes mosaïque avec PLP chimérique
- 25% résistance acquise β-lactamine (pneumocoque sensibilité diminué pénicilline)
**** Clinique
- Infection neuroméningée
- Infection voies respiratoire: pneumonie franche lobaire aigüe, bronchopneumonie, otite, mastoïdite, sinusite, exacerbation BPCO
- Rare : purpura fulminas, endocardite
- Bactérimié, souvent à partir d’un foyer pulmonaire
** Entérobactéries
*** Résistances et groupe
Groupe selon la résistance *naturelle* β-lactamine
1. aucune : E. coli, Proteus mirabilis, Salmonella, Shigella
2. Pénicillinase à bas niveau : Klebsiella, Citrobacer koseri
3. Céphalosporinase à bas niveau : Enterobacter, Serratia, Morganella, Providencia, Citrobacter freundii
4. Pénicillinase + céphalosporinase : Yersinia enterolitica
5. β-lactamase à spectre étendu (BLSE): Kluyvera

Résistance acquises
*** Escherichia coli
- Bacille gram négatif, mobile, oxydase négative, nitrase-réductase positive
- Urine : rose sur milieu chromogène (β-glucoronidase positive)
- Sensbilité naturelles aux antibiotiques actif sur BGN
- Groupe 1 :
  - céphalosporinase chromosomique de très bas niveau.
  - Résistance acquise enzymatique : pénicillinase, β-lactamase à spectre étundes, céphalosporinase de haut niveau, carbapénémase
*** KES = Klebsiella, ENterobacter, Serratia
Vert (β-glucosidase +)
*** Salmonelle, Shigelle
- Bacille gram négatif, non sporulé, aéro-anaérobie facultatif
- non exigeat
- catalase, nitrate réductase
- pas dans le microbite digestf normal de l'homme
- porte d'entrée digestive
- responsible de
  - maladie du péril fécal (pays en voie de développement : Salmonelle typique et non typqiue, Shigelle)
  - TIAC : salmonelle non typhique >> shigelle
    - rappel:  TIAC>= 2 cas, déclaration opligatoire
**** Pouvoir pathègene
- salmonelle :
  - strictement humain = sér. Typhi, paratyphi => fièvre (para)typhoïde
  - animale = non typhique: gastroentérite
- shigelle : dysenteria... strictement humain => dysentérie bacillaire, gastroentérite sanglante
**** Physiopath
*Entéro-invasif*
- shigelle : envahissement + destruction cellules épithéliales (syndrome dysentérique)
- salmonelle  : envahissement sans destruction de la muqueuse (sd gastroentéritiques) +/- production de toxique

Clinique:
- salmonelle typhique: 1-2semaine incubation, fièvre continue élevée 40`, bactériémie, tuphos, diarrhée/constipation`
- salmonelle non typhique: incubation 12-36h, diarrhée fébrile, vomissement
- shigelle: incubation 1-3j, fièvre élevée, selle avec sang, glaire, pus, douleurs abdominales violentes
**** Diagnostic
- selles +/- sang pour salmonelle (para)typhique
- diag moléculaire
- culture:
  - "SS" (salmonelle/shigelle): salomnelle = lactose - et SH2+
  - Hektoen, Drigalski (BG-) : lactos-, h2s+
  - pour salmonelle : bouillon d'enrichissement
- identification: *salmonelle non différencie d'e. coli*
  - shigelle = immobile
  - shigelle = fermentation manitol ( sauf s. dysenteria )
- BG-
**** Traitement
- diarrhée infectieuse aigue = symptom
  - antipyrétique,
  - maintien hydro-élecrique
  - régime sans résidu
  - ! contre-indication ralentisseur du transite (lopéramique)
  - +/- antibio si forme grave > 3 ours, ID... : FQ/azithromycique
- bactériémie : FQ/azithromycine,/ceftriaxone

Déclaration obligatoire : TIAC, fièvre (para)typhoïde
Vaccination en prévention salmonelle typfique
** Entérocoques
Cocci gram+ , anaérobie facultative, ressemblantà des streptocoques

Espèce majoritaire: E. faecalis = 80-90=, faecium = 5-10%
*** Habitat
Ubiquitaire. Surtout tube digestif (homme, animaux), milieu extérieur
Home sain : tube digestif, périnée, parfois vagin, oropharynx

Pulpart des infections = à partir de la flère du patient. Mais exogène possible.

Commensal gastrointestinal + génital chez les femmes
Augmentation des infections avec les années
*** Facteurs de virulence
- Pas d’exotoxine, ni de superantigène
- Protéine de surface -> adhère à l’endocarde et l’urothelium -> endocardite et infections urinaire
*** Résistance
- Naturelle : céphalosporine
  - faecals = résistance oxacilline, C3G, ertapénème, lincomycine, acide fusidique
- *E. faecalis = sensible amox. E. faecium = résistant 80-90%*
- multi-résistance chez E. faecium
- aminoside (bas niveau)
- β-lactamine/glycopeptide seul = seulement effect bactériostatique sur > 90%. Mais aminoside + inhibiteur de la paroi (β-lactamine, glycopepited, lipopetide) = synergie
- glycopeptide
- MLSK (Macrolides-Lincosamide-Streptogramine-Kétolide): modification cible++, efflux, protection ribosomale
Attention: en cas de résistance surajoutée, les aminosides sont inefficaces.
*** Clinique
- Infection urinaire
- Infection de la peau et des parties molles
- Endocardite
- Bactériémie
- Infection abdopelvienne
*** Résistances
- résistance naturelle céphalosporine
- E. faecalis : pas résistance pénicilline A (contrairement à E. faecium)
- E. faecium :
  - multiréristance en émergence
  - > 80% faecium résistance pénicillines A
*** lol

Clinique
- infection urinaire: le plus fréquent, nosocomial
- bactériémie
- endocardite : de plus en plus fréquent
- infection intra-abdominal (en association)

Résistance: attention aux entérococques résistant vancomycine (surtout E. faecium)
- /vancA/ /vancB/
** Neisseria meningitidis
- Diplococque Gram - aérobie.
- Très gragile. Hautement variable
- Épidémio :
  - 2 pics : nourisson < 1 an (système immunitaire immature), ado/jeune adulte (socialisation)
  - ceinture de la ménigitde (Afrique sahel + subusaharanienne)
*** Habitat
réservoir 100% humaine. Transmission directement uniquement par goutelettes
Portage pharyngé, avec rarement invasion (sang +/- LCS) -> seulement souches
** Listeria monocytègene
*** Résistance
- résistance naturelle céphalosporine, clindamycine, fosfomycine
** TODO Haemophilus influenza
Résistance : regarder penicilline G
- suspicion beta lactamase, tester par cefinase
- PLP3 : faire CMI
