:PROPERTIES:
:ID:       9160ba80-117b-4434-acc9-13676a534da0
:END:
#+title: Bactéries
#+filetags: personal medecine
* Résistante
PLP = paroi externe de la membrane plasmique. Sert à synthétisé le peptidoglycane = composant de la paroi. Les beta-lactamine vont inhiber la synthèse de peptidoglycane. En cas de PLP2a, moins d’affinité aux beta-lactamine.
https://pharmacomedicale.org/medicaments/par-specialites/item/beta-lactamines-penicillines-cephalosporines
* Bactéries
** Staphylocoques
*** Résistances
- β-lactamine : production pénicillinase (BlaZ)> 90%
- résistance méticilline (staph coag négative >> aureus) via
  - la Staphylococcal Cassette Chromosome mec (SCCmec) [= zone génomique comprenant /mecA/ qui code pour la protéine PLP2a ( [[*Résistante][Résistance]]).
  - Nouveau gène mecC: code PLP2c
  - S. aureus : 15-20% résistant méticilline
- Macrolides-Lincosamide-Streptogramine-Kétolide (MLSK)  : modification de la cible surtout (modification/mutation ribosome)
- 3 phénotype de résistance aux aminoside (inactivation enzymatique = 5% SAMS mais 80-90% SARM)
- glycopeptide : exceptionnel
*** Staphylococcus aureus
Cocci Gram+ en amas : aérobie +/- anaérobie. Immobiles. non capsulé, non sporulé

**** Facteurs de virulence
Associé à la paroi:
- *coagulase* liée = récepteur au fibrinogène, sur la paroi bactérienne -> diag (test d'agglutination)
- protéine A: liaison aux immunoglobuline, protection contre la phagolytose

Excrété
- hémolysine : lyse des hématies (β-complète)
- coagulase libre = excrétée, clive le fibrinogène -> embole septiques. Différence avec les staph. à coagulase négative (S. epidermidis)
- staphylokinase : libère bactéries des emboles
- *toxine* :
  - leucocidine de Panton et Valentine (LPV) -> leucotoxique dermonécrotique
  - toxine du choc staphylococcique (TSST1-1 -> activation lymphocytes T)
  - exfoliatines -> érythrodermie bulleuses
  - entérotoxines thermostables -> TIAC

**** Habitat
- 30% porteur sain (transitoire ou non)
- Transmission intra-humaine par les mains ou indirectevement (vêtements...)
- Commensal : microbiote nasal, oropharyngé, digestif, cutané (aisselles)

**** Clinique
- Porte d'entrée = cutanée <-> site de portage/infection
- Infection communautaires, associées aux soins
- Infection toxiniques :
  - LPV : infection cutanée, pneumonie nécrosante
  - TSST1 = choc toxinique avec érythrodermie. Entrée = vaginale ou cutanée
  - exfoliatine: impétigo bulleux, syndrome d'exfoliation généralisée
  - entérotoxine = diarrée à +2h ou 4h, TIAC
- Infections suppurative
  - cutanée superficielle (furoncle, impétigo, folliculite) ou profondre (abcèse, fasciite)
  - bactériémie, endocardite
  - infections profondes : ostéo-articulaire, pneumopathie, neuroméningées (abcès)
**** Diagnostic
- Culture : non exigeante
  - gélose sang 24h: *beta-hemolytique* (hémolyse total)
  - Chapman (mannitol + NaCl) : rouge -> jaune avec NaCl
  - catalase +, oxydase-, DNAse + (à la différece des tretop à coagulase négative)
**** Sensibilité et résistance
Résistance fréquent à l’hôpital
- β-lactamines :
  - phénotype sauvage sensible
  - pénicilinase > 90% des souches (disque FOX de pénicilline g): résistance pénicilline G, V, A -> ajout d’inhibiteur de β-lactamase
  - SARM = gène mecA : PLP2 additionnelle -> résistance à toutes les β-lactamines. Souvent multirésistance aminoside, macrolide, fluoroquinolonie
    -> vancomycine en 1ere intention
- Aminoside : sauvage sensible, résistance acquise par inactivation enzymatique
- Glycopeptide : sauvage sensible, phénotype gIA/hétéroGISA avec sensibilité diminusée, phénotype gRSA (résistance)
*** Staphylococcus saprophyticus
- Cocci gram + en amas, catalase positive, nitrate réductase négative
- Urine :rose sur milieu chromogène mais identification spectromètre de masse/biochimiue
- Sensbilité nature à la plupart des antibiotique anti-staph
- Résistance naturelle : fosfomycine, acide fusidique, novobiocine
- Résistance acquise fréquente : péni G, érythromycine
** Proteus mirabilis
** TODO Pseudomonas aeruginosa
Bacille Gram négatif, très mobile

Origine : environnement++
Opportuniste :
- infection nosocomiale (matériel) ou . 1ere bactérie en réa
- mucoviscidose
Facteurs de virulence : exotoxine, exoprotéines, hémolysine
Facteur d'adhésion
Forte capacité à former des biofilms

*** Diagnostic
- Pousse 24h à 37% sur milieu non sélectif.
- Milieu sélectif : cétrimide
- Oxydase positif (!= entérobactéries) -> test rapide pour différencier les 2
*** Résistance
- Faible perméabilité membranaire
  - résistance naturelle : amox, augmenti
  - ertapénèmepénicillines,
  - cefotaxine, ceftriaxne
- Catalase positif - lactose négatif
** Streptocoques
Infections graves = /pyogenes/, /pneumoniae/.
Commensal mais opportunites (immunodépression) : oraux (*endocardite, SDRA)
*** Classification
- Hémolyse : α  partielle, β = totale.
- Lancefield : classification selon un composé de la paroi bactérienne (polyoside C) avec mise en évidence de l'antigène par agglutination.

En première approximation :
- α-hémolyse = non-groupable
  - /pneumoniae/ résistance par chimérisme PLP (acquis)
  - autres anginosus, mitis, sanguinis, bovis, salivarius, mutans
- β-hémolyse = groupable. Les plus importants
  - Groupe A = S. pyogenes. Cause d’angine++. *Pas de résistance aux β-lactamine*
  - Groupe B = S. agalactiae
   Infection materno-foetale ++ (note: l’antibioprophylaxie marche chez les nouveau-né mais seulement pour les infections avant 7 jours)
  - C : /dysagalactia/ (rarement /equi/)
  - G : /dysgalactia/, /canis/

/Note/: certaines sous-espèce de Lancefield peuvente être alpha-hémolytique
*** Résistances
- β-hémolytique: pas de résistance β-lactamine
- S. pneumonia : 25% résistance acquise β-lactamine (sensibilité diminuée)
*** Classification d’Ambler
A. BLSE
   - résistance pénicilline, C1, C2, C3G
   - sensible inhibiteur β-lactamase et carbapénème
   - détecté par ceftazidime + acide clavulanique
B. Métallo-beta-lactamases
   - résistance comme B. + carbapénème
C. ampC céphalosporinase
   - résistance BLSE + céfoxitine + inhibiteur β-lactamase
   - sensible carbapneme
   - détecté céfoxitine
D. oxacillinase
   - sensible β-lactamase
*** Streptococcocus pyogenes
Cocci gram+ en chaînettes, capsulé, non sporulé, immobile

Réservoire pharyngé. Transmission = aérienne, contact plaie infectée, accouchement.
**** Facteurs de pathogénicité
résistance à la phacogytose
- protéine M
- encapsulation
Facteurs de virulence
- enzyme :hyluronidase, stroplysine O et S (favorisent l’invasion tissulaire)
- exotexonie :  activation et prolifération d’une sous population lymphocytes T -> cytokine proinflammatoires
- Streptolysine = hémolyse β-complète
- toine érythrogène : hypersensibilité retardée à la scarlatine
**** Habitat
Strictement humaine, surtout pharyngé +- peau, vagin...
Pyogène = responsiable d’infections suppurées
**** Clinique
- non invasive = angine érythémateuse/érythémato-pultacée, otite moyenne aigüe de l’enfant, scalratine, infection cutanée
- invasive : cutanée sévère (fasciite nécrosante), septicémie, choc toxique streptococcique
- complications post-streptococciques  (rare) = immunologique :
  - rhumatisme articulaire, glomérulonéphrite aigüe, érythème noueux
**** Diagnostic
- bactérie exigeante -> gélose sang +/- ANC (inhibe Gram-)
- β-hémolyse
- Résistance potochine, sensbile bacitracine
- Catalase -, oxydase -
**** Sensibilité, résistance
- β-lactamine : sensible
- macrolide : sauvage sensible, résistance par mécanisme d’efflux, modiifcation cible ARN23S
*** TODO Strepto agalactiae
*Naturellement sensible β-lactamine*
*** Pneumocoque
Gram+ diplocoque encapsulé à multiplication extracullaire.
Classification selon la capsule (vaccins)
**** Habitat
Voie respratoire supérieure
Transmission goutelette, interhumaine
**** Pathogénicité
- adhérence cellules épithéliase rhinopharynx
- facteurs de virulence non capsulaire
- évasion à la phagocytose
- actionation complément, cytokien inflammatoire
**** Résistance
- β-lactamine: Selon les PLP (!inutile d’ulitiser les inhibiteurs de betalactamase)
- sensbilité possiblement dimunée aux fluoroquinolones
**** Clinique
- Infection neuroméningée
- Infection voies respiratoire: pneumonie franche lobaire aigüe, bronchopneumonie, otite, mastoïdite, sinusite, exacerbation BPCO
- Rare : purpura fulminas, endocardite
- Bactérimié, souvent à partir d’un foyer pulmonaire
** Entérobactéries
*** Résistances et groupe
Groupe selon la résistance *naturelle* β-lactamine
1. aucune : E. coli, Proteus mirabilis, Salmonella, Shigella
2. Pénicillinase à bas niveau : Klebsiella, Citrobacer koseri
3. Céphalosporinase à bas niveau : Enterobacter, Serratia, Morganella, Providencia, Citrobacter freundii
4. Pénicillinase + céphalosporinase : Yersinia enterolitica
5. β-lactamase à spectre étendu (BLSE): Kluyvera

Résistance acquises
*** Escherichia coli
- Bacille gram négatif, mobile, oxydase négative, nitrase-réductase positive
- Urine : rose sur milieu chromogène (β-glucoronidase positive)
- Sensbilité naturelles aux antibiotiques actif sur BGN
- Groupe 1 : céphalosporinase chromosomique de très bas niveau. Résistance acquise enzymatique : pénicillinase, β-lactamase à spectre étundes, céphalosporinase de haut niveau, carbapénémase
*** Entérocoques
Cocci gram+ , anaérobie facultative, ressemblantà des streptocoques

Espèce majoritaire: E. faecalis = 80-90=, faecium = 5-10%
**** Habitat
Ubiquitaire. Surtout tube digestif (homme, animaux), milieu extérieur
Home sain : tube digestif, périnée, parfois vagin, oropharynx

Pulpart des infections = à partir de la flère du patient. Mais exogène possible.
**** Facteurs de virulence
- Pas d’exotoxine, ni de superantigène
- Protéine de surface -> adhère à l’endocarde et l’urothelium -> endocardite et infections urinaire
**** Résistance
- Nombreux antibio ...
- Naturelle : C3G
- β-lactamine/glycopeptide seul = seulement effect bactériostatique sur > 90%. Mais aminoside + inhibiteur de la paroi (β-lactamine, glycopepited, lipopetide) = synergie
Attention: en cas de résistance surajoutée, les aminosides sont inefficaces.
**** Clinique
- Infection urinaire
- Infection de la peau et des parties molles
- Endocardite
- Bactériémie
- Infection abdopelvienne
**** Résistances
- résistance naturelle céphalosporine
- E. faecalis : pas résistance pénicilline A (contrairement à E. faecium)
- E. faecium :
  - multiréristance en émergence
  - > 80% faecium résistance pénicillines A
** Entérocoques
Commensal gastrointestinal + génital chez les femmes
Augmentation des infections avec les années

Clinique
- infection urinaire: le plus fréquent, nosocomial
- bactériémie
- endocardite : de plus en plus fréquent
- infection intra-abdominal (en association)

Résistance: attention aux entérococques résistant vancomycine (surtout E. faecium)
- /vancA/ /vancB/

E. faecalis = sensible amox. E. faecium = résistant
** Neisseria meningitidis
- Diplococque Gram - aérobie.
- Très gragile. Hautement variable
- Épidémio :
  - 2 pics : nourisson < 1 an (système immunitaire immature), ado/jeune adulte (socialisation)
  - ceinture de la ménigitde (Afrique sahel + subusaharanienne)
*** Habitat
réservoir 100% humaine. Transmission directement uniquement par goutelettes
Portage pharyngé, avec rarement invasion (sang +/- LCS) -> seulement souches
** Listeria monocytègene
*** Résistance
- résistance naturelle céphalosporine, clindamycine, fosfomycine
** TODO Haemophilus influenza
Résistance : regarder penicilline G
- suspicion beta lactamase, tester par cefinase
- PLP3 : faire CMI
