#+title: Epigenetique
#+author: Pr Schlutch-Bolard
#+date:<2022-06-27 Mon>

* Rôles
Régule l’expression des gènes
plasticité environnement
mémoire cellulaire

* Mécanisme
Ne modifie pas la séquence d’ADN mais apporte des informations complémentaire via marques biochomiques
- induites par l’environnement (stimulation hormonale, extérieure)
- réversibles
- trnasmissibles
* Marques
** Méthylation ADN
- groupement méthyl sur une cytosine, seulement sur dinucléotide CpG (méthylation symétrique de l’ADN)
- catalysée par ADN méthyltransférases (5 identifiées)

Méthylation soit
- Méthylation /de novo/
- Maintien de la méthylation au cours des réplications cellulaires

Déméthylation soit
- active (famille de dyoxygénase TET)
- passive (pendant réplication cellulaire)

*** Cycle
- déméthylation globale après la fécondation (zygote)
- stade blastocyle : méthylation
- déméthylation des cellules germinales primoridales
- re méthylation spécifique du sexe
*** Function
- Expression des gènes : corrélé au niveau de méthylation du promoteur
mais ilôts CpG (300-3000 bp) = 2/3 ne sont jamais méthylé !
- ?

Attention : plupart des facteurs de transcription non sensible à la méthylation

- assure la stabilité du génome : empche éléments viraux)
- inactivation du X
** Modification des histones
Protéines structurales -> nuclésome (octamère d’histones)
Modification sur la queue N-terminale :
- acétylation, méthylation, phosphorylation
- médiée par les enzymes: writer, eraser (enlève la marque), reader (reconnaît les modifications)
** Organisation 3d
- territoire chr : position spécifique dans le noyau, relativement stable dans une cellule
- compartimente chr : A (chromatine active), B (hétérochromatine)
- TAD : NB zones sans TAD = Xi, chromosomes mitotiques
- boucle chromatiniennes

  périphérie du noyau :
  - LAD (lamina associated domaine) quand la lamine entre en contact avec la chromatine. Pas forcément avec une frontière du TAD. 40% du génome !
  - souvent hétérochromatine, peu d’expression des gènes. Mais il existe des régions dans le noyau, pas orcément linéaires
** ARN non codant
- Petits ARNs, longs ARNs (> 200 nucléotide)
- Actions:
  - intérference transcriptionnelle (démarre trnascription en amont du gènes -> extinction de l’expression du gènes ; voire en positif)
  - remodelage de la chromatine et des histones
  - transcription des ARNs surtout anti-sens
  - vont liée des protéines en modulant son activité, modifiant la structure ou sa localisation
** État chromatine
Soit hétérochromatine (fermées, siliencieuse), soit euchromatine (ouverte, active)
* Indication en pathologies
- Inactivation de l’X
- Empreinte génomique parentale : cf cours dédié
- Dysonciton : chromatinopathie, cohésinopathie, anomalies méthylaton
- position
** Mutation d’un gène de la régulation épigénétiques
*** Chromatinopathies
Writers = Rubinstein-Taybi..
Erasers = KBG, Kabuki

Sd Rubinstein-Taybe :
- retard de croissance
- microcéphalie
- dysmorphie: réraction bitemporale, FP oblique en bas, ptosis, rcine du nez large, columelle longue, sourire grimacant
Initialement mis en évidence comme microdélétionnel
- 16p13.3 : Variant CREBBP
- 22q13.2 :  /EP300/
  -> fait partie du même complexe
*** Anomalie de méthylation
**** Syndrome de Rett : dominant lié X
mutation /MECP2/ avec perte de fonction
régulation transcriptionnelle
Protéine MeCP2 multifonction: condensation chromatine, ...
4 phases
1. 6-18 mois : stagnation, hypotonie, diminution PC
2. 1-3 ans régression avec stérétoype, retrait sociale, pas de la langage, pert de l’usage des mains
3. 2-10 ans :  DI, épilepsie,
4. scoliose, perte de la marche
*** Cohésinopathie
Cornelia de Lange:
- RCIU et postnatal, microcéphalie
gènes : NIPBL 80%
Anneau de cohésine = 5 sous-unitées avec facteurs auxiliaires (NIBPL, HDAC8)
- processus intra-chromatinien (formation TAD)
- cohésion entre différent chromatide (ségrégation chromatide soeurs)
-> tout ce complexe peut être affecté
** Effet de position
modification expression via modification de l’environnement chromatinien
1. variegation: ex inactivation de l’X avec transloc X-autosomique équilibrées (disomie fonctionnelle)
2. gènes de fusion : ex LMC = transloc 9 22 -> protéine chiméquie avec activité TK augmentée
3. GAIN DE SÉQUENCES activatircie : lymphome de Burkitt avec t(8,14) ->_promoteur d’immunoglobuline vont activer CYMG
4. perte élément régulateur : ex /PAX6/ (aniridie = AD) -> soumis régulation dans /ELP4/
   point de cassure vont faire de l’haploinsuffisance
5. altération d’un élément régulateur
  ex SOX9 : haploinsuffisance ->_dysplasie campomélique
   - AD
   - incurvation os long
   - dysplasie squelétette
   - réversion sexuelle
   - FP
    mutation ponctuelle, translocation possible
    en fonction de la région régulatrice, on peut avoir certains symptômes (ex: seulement une séquencue de Pierre-Robin)
6. effet des ARNs non codant
   ex: locus des alphaglobine : /HBA1/
   ->_alphathaassémie par délétion du gènes, séquence régulatrice 5’
   parfois délétion 18kbp en aval
   -> trnascription de LUC7L en anti-sens, qui va se poursuivre en anti-sens jusque local HBA2 -> ARN antisens ->_absence de transcription
7. effet de positon télomérique
   ex: insertion de /PLP1/ sur chr X
   - mère symptomatique car chrX normal inactivé (PLP1 i) effet de position sur le chr 19 -> pas d’expression de PLP
   - 2e fils avec X normal et 19 porteur de l’insertion qui est asymptomatique
     1 copie de PLP1 sur X et autre copie inhibié par effet de position télomérique -> protecteur

     ex: chromosome en anneau ->_sur le 20, syndrome épileptique
     même phénotype avec anneau et télomère intègre : hypothèse = effet de position télomérique
8. remodelage dans les TAD
   deletion frontière TAD -> change la régulation

    Pourquoi gain -> pas de phénotype ?
    duplication comprenant le TAD et le TAD adjacent ->_nouveau TAD sans le gène, SOX9 inchangé (cf image)
    duplication ->_formant nouvea TAD avec copie KCNDT2

* Hérédité transgénérationnelle
épigénétique = "mémoire" ->_comment se fait la transmission?
ex:
- exposition prénétale simple, pas de modification des gamètes
- exposition sur plusieurs génération : modification des gamètes mais avec "remise à zéro " à la génération suivante
- exposition foetus et modification gamètes  sans "remise à zéro"
Peut se transmettre par
- les gamètes
- ou non ! ex: souris qui modifie le comportement de son petit
