#+title:      Friday 19 July 2024 09:38
#+date:       [2024-07-19 Fri 09:38]
#+filetags:   :journal:
#+identifier: 20240719T093836

* Biblio
** Orphanet = données biblio
:PROPERTIES:
:CUSTOM_ID: h:25554172-e571-42d3-86d5-2a50aae2d4e2
:END:
- [cite:@orphadata2024epidemio] données orphanet : épidémié par maladies avec une liste d'article et la prévalence/incidence estimée pour chaque article. Format XML. Accès libre
- [cite:@orphanet2023prevalence] idem mais PDF et moins à jour ?
- orphadata: lien gène-maladie https://www.orphadata.com/genes/
- [cite:@orphadata2024phenotype] donne fréquence phénotype dans un contexte clinique selon 5 groupes. Critère diagnostic également
- [cite:@orphadata2024natural]  zygotie, age de début
- [cite:@hoomm2024ordo] : lien entre phénotype et clinique avec la fréquence. Idem que fréquence phénotypique au début ??
Méthodo [cite:@nguengang2019estimating]
** BNDMR
https://www.bndmr.fr/publications/nombre-de-cas-par-mr/
** Autre
- [cite:@smith2022estimating] mettre fig 3. Calcul non clair pour le nombre de maladies rares mais disent 12000! SNV si on considère la moitié des gènes
- [cite:@haendel2019how] à partir de monarch > 10k pour le nombre de maladies rares
- [cite:@macarthur2012systematic] 185 genomes ~ 1 200 variants LOF filtrés. Estimation génome en moyenne 97 variant LOF dont 18 homozygotes
