* 2024-05-24
** 09:52 RVI IOP
- 2304725 : exploration hémostase pour PLG ? (far-fetched...)
- 2101776  : MCM8 ok
- 2305313 : neg ?
a noter pour virginie : variant  BTNL3 hmz chez index + mère mais il y a une délétion en trans donc variant hémizygote
ERCC6 : non une seule publi non reproduite(seqone)
HSPG2 clinique non en faveur
- 2304151  : avis expert hypo hypo demandé, a priori neg
** 10:17 Erreur sur nom de gène
Dû à la vieille version de VEP mais difficile à metter à jour [[id:7310f8fa-7518-48f7-bc11-ec14d8e0cbf1][Limites annotation]]
** 10:40 Automatisation Hygen
1. POST https://hygen.auragen.fr/Module/Mocas_Parcours/ParcoursIntervenant/TableauDeBord
   - cookie
   - header Origin: https://hygen.auragen.fr et Referer: https://hygen.auragen.fr/BiologisteGeneticienAURAGEN?X-Correlation-ID=6dd93b9b-9410-47da-8422-124f306bbb7a
   - payload PageNumber=1&PageSize=50&CodesCR=%5B%22PFAURAG%22%5D&Etat=1&NumeroVenue=MR-2300926&take=50&skip=0&page=1&pageSize=50
   - réponse
     - JSON
       {
    #+begin_src json
    "Success": true,
    "Object": {
        "TotalNbItems": 1,
        "Items": [
            {
                "Patient": {...},
                "IdEnsembleVersion": 1,
                "Code_UF": "GrenoblMR",
                "LibelleEtCodeUF": "GrenoblMR - CHU Grenoble - domaine maladie rare",
                "IdPrescription": 39310,
                "DatePrescription": "2023-03-03T08:05:12.3639826",
                "IdEtat": 1,
                "IdPatient": 12278,
                "pres_NbEtapesRDVAPrendre": 0,
                "pres_NbEtapesRealisee": 9,
                "pres_NbEtapesAFaire": 0,
                "pres_NbEtapesTotal": 13,
                "DateEvtDecl": "2023-03-03T08:05:11.8649522",
                "NomResponsable": "DEVILLARD, Françoise",
                "MostToDo_Libelle": null,
                "MostToDo_DateDebut": null,
                "MostToDo_DateFin": null,
                "MostToDo_DateRDV": null,
                "MostToDo_IdEtapePrescrite": null,
                "Next_Libelle": "Extraction",
                "Next_DateDebut": "2023-03-08T00:00:00",
                "Next_DateFin": "2029-04-27T00:00:00",
                "Next_DateRDV": null,
                "Next_IdEtapePrescrite": 193575,
                "Titre": "AURAGEN filière maladie rare",
                "NumVersion": 18,
                "DateModification": "2023-12-05T00:06:10.6543087",
                "HasLiaisons": false,
                "CanEditPrescriptions": false,
                "HasEtapeAvecCodeCrCommeActeur": true,
                "IdResponsable": 396,
                "IdPrescripteur": 396,
                "TitreSuiviPrescription": "VOLLAND CLIN Louca - AURAGEN filière maladie rare"
            }
        ]
    }
}
    #+end_src
     - HTML

#+begin_src html
  <span ng-hide="false" class="tdb-hoverable ng-binding" title="PATIENT DDN - IPP" ng-mouseover="toolTipForPatientPrescription(dataItem.Patient)" ng-click="openConteneur(dataItem.IdPatient, dataItem.Code_UF)">
  PATIENT DDN
        </span>
  #+end_src
** 17:03 Réunion biologistes de Lyon
Participant: Louis Januel (Lyon), Nicolas Chatron (Lyon), Céline Richard (St-Étienne ?), Francis Ramond

1. Réunion bimensuelle pour discuter d'1-2 dossier complexe, 30min max. Présenté par un interprétateur «avancé". Public visé : plutôt ceux qui interprétent beaucoup mais invitation à tout le monde.
   Exemple du dossier 2400847 avec pic à 500x -> parvovirus probable ! (noté dans [[id:116b858b-5dd5-4b77-bd67-55fc3b7b76ea][Cas intéressants]] ).
   Demandé à assister à la prochaine
2. CNV en mosaïque : tester 5 dossiers
3. Amélioration interface :
   - Maëlle travaille sur nouvelle version pour avoir une page perso par biologiste
** 17:35 Discussion impromptue avec Julien
- Clinvar : la législation nous empêche d'y soumettre les variants. In fine, le CAD devrait servir d'entrepôt de données.
- Interprétation : voir avec Laurie pour bloquer un temps
Voir avec Wiame pour interprétation, sinon avec Julien (pas de mail !)
- Projet:
  - pseudo-gène démarré
  - doit envoyer biblio projet facebook par mail
  - point à faire
