* 2024-07-03
** 13:05 Bioinfodiag Julien Gganeur
Litérature : edgeR, deseq2 = analyse différentielle entre 2 maladies
Ici: on cherche un outlier dans une distribution. Pour un ensemble d'échantillons, stats pour identifier le gèneavec une expression aberrante !

*** Outrider
  Input = matrixe nb d'échantillions par gène -> on retient 10-14k gènes dans la cohorte
  Sttatsu
  Sortie pour chaque échantillons et un gène : fold change
  <5 gènes outlier par échantillons !

*** Fraser
regarde l'épissage: anomalies ?
Une seule métrique pour couvrir tous les cas d'épissages alternatif (Jaccard index)

matrice en entéeée
on compte les redas "split" et ceux on split à chaque conjuction. Matrice d'index de Jaccard

Sttas
Sortie taux de fausse découverte et valeur quantitative ΔJaccard
< 10 gènes par échantillons
*** DROP = pipeline intégrant les 2
- input: BAM (RNAseq) et VCF (DNA) + génome référence + annotation par gène
- modules : exrpession aberrante, épissage aberrante, expression monoallélic
  Dispo github
  https://github.com/gagneurlab/drop


Contrôle qualité :
- vérifier variants dans transcrit sont bien dans le génome
- profondeur de séquencage
- expression des gènes

  Sortie: pour un ARN et un gène : AbEx, AbSp, MAE

*** Reco pour annotation des résultat
Il en faut 43
- ARN : vérifie plot (pas de bruit)
- ADN : y a-t-il des variants qui supportent le mécanisme ? Douteux si : pas de avariant rare, pas de génome, mécanisme non clair ou non retrouvé en laboratoire
- clinique: similarité HPO
- ségrégation:

  Excl si ségrégation non en faveur, évenement non clear, non retrouvé en fonctionnel, phénotpe très différent
*** Cas clinique
1. del 9Mb. NB: 60% gènes OMIM sont exprimés dans le sang !!
2. deletion 1bp mais manque 2e varant. Expression diminuée
   FRASER: nouveel exon créé ? Vérifié IGV
   Où est le second variant : 2e variant dans ce nouvel exon
3. Cohorte : étude ARN : parmis les 5 outliers qui collent le plus à la clinique un gène retrouvé (NOP56) avec STR récemment connu
4. Étude de cas : DI + cardio -> rien de conclusif dans ADN
** 14:48 Discussion Maelle couchdb
ok pour héberger sur un VM "proche" couchdb
ok pour faire un minisite web
Sera seulement accessible aux gens avec URL (+ compte ?)
Clément: faire des specs pour Alain
Problème : comment faire des backup ?
