#+title: Marqueurs hépatiques: ASAT
#+author: Alexis Praga
#+setupfile: ./fiche.setup

* Localisation, physiologie
L'aspartate transférase est une enzyme transaminase qui va transférer un groupement amine depuis un acide aminé (aspartate) vers un acide cétonique (acide \alpha-cétoglutarique) selon la réaction

aspartate + acide \alpha-cétoglutarique \leftrightarrow oxaloacétate + glutamate

L'ALAT est le point de départ de nombreuses réactions métaboliques (ex: pyrimidine) et le glutamate est impliqué dans le cycle glucose-alanine.

Elle se trouve principalement dans les cellules hépatiques et cardiaques, et dans une moindre mesure dans les muscles squelettiques, reins, pancréas, globules rouges et cerveau.
* Production
Il existe 2 isoenzymes : une dans le cytoplasme et une dans les mitochondries.
* Principe analytique de mesure
Test enzymatique.

L'absorbance est mesurée par photométrie qui reflète la vitesse de formnation de NADH, qui est proportionnelle à l’activité de l’ALAT selon l'équation :
oxaloacétate + NADH + H^{+}  \rightarrow malate + NAD^{+}


* Valeurs de référence [cite:@thomas2005consensus]
- homme < 50U/L
- femme < 35U/L
* Principales interactions analytiques
- hémolyse
- gammapathie IgM (très rare)
/Note: les carences en vitamine B_6 ne sont plus une interaction/
* Vigilance pré-analytiques et analytiques
Prélèvement non hémolysé
* Variations [cite:@bonnefont2019explorations]
- physiologiques: augmentation à la naissance puis diminution jusque 6 ans [cite:@van2019davis], surcharge pondérale, exercice musculaire violent
- iatrogène:
  - aigù = IMAO, méthyldopa, isoniazide, halothane
  - chronique : isoniazide, nitrofurantoïne, AINS, sulfamide...
- augmentation pathologique par *cytolyse hépatique*:
  - hépatite virale, autoimmune
  - infections (EBV, CMV, HSV, toxoplasmose)
  - alcoolisme aigü/chronique
  - inflammation modérée
  - obstruction voie biliaire, cirrhose

#+print_bibliography:
