#+title: Bilirubine libre - Roche cobas c 503
#+author: Alexis Praga
#+setupfile: ./fiche.setup

* Localisation, physiologie

* Production
La bilirubine libre est captée par le pôle vasculaire de l'hépatocyte. Elle y est conjugée par glucuryonyl-transferiase ou bilirubine-UDP-glucuronosyl-transférase. La bilirubine conjlugée est ensuite transfrérée dans la bile via la membrane du canalicule, puis sécrétée dans le duodenum par les voies biliaries. Elle est également déconjuguée par la flore intestinale (voir fichie bilirubine).
* Principe analytique de mesure
Test colorimétrique par méthode diazo. Mesure par photométrie à 540 nm de l’azobilirubine rouge qui est proportionnelle à la concentration en bilirubine directe.
* Valeurs de référence [cite:@thomas2005consensus]
- Valeurs de référence : < 5μmol/L
* Principales interactions analytiques
  - *hémolyse si > 25mg/dL*
  - phénylbutazone
* Vigilance pré-analytiques et analytiques
- tube hépariné (lithium, di- ou tri-potassique)
- si la concentration en bilirubine totale dépend de la conjuguée, cela peut entrainer une valeur pour la conjugée supérieure à la bilirubine totale
- une hématocrite élevée peut diminuer les résultats
* Variations [cite:@bonnefont2019explorations]
- Augmentation
  - intra-hépatique (médicament, viral, parasite, cirrhose...)
  - extra-hépatique (obstruction des voies biliaire : lithiase, compression externe [tumeur pancréas]...)
