#+title: Gamma Gt - Roche cobas c 503
#+author: Alexis Praga
#+setupfile: ./fiche.setup

* Localisation, physiologie
La \gamma-glutamyltranspeptidase est impliquée dans le transfert des acides aminés au travers de la membrane cellulaire et dans le métablosme du glutathione.
Elle se trouve dans le foie, pancréas, reins, rate, poumons, prostate.

* Production
La version circulante est du à une destruction cellulaire, surtout d’origine hépatique.

* Principe analytique de mesure
Test colorimétrique enzymatique.

Il mesure par photométrie à 415nm (absorbance) de la quantité d’amino-5 nitro-2 benzoate, qui est proportionnelle à l’activité de la \gamma-GT.

* Valeurs de référence [cite:@thomas2005consensus]
  - homme < 60U/L
  - femme < 40U/L

* Principales interactions analytiques
 - Hémolyse >200mg/dL
 - Gammapathie IgM (très rare)

* Variations [cite:@bonnefont2019explorations]
- physiologique : population africaine, nouveau-né (augmentation) [cite:@van2019davis]
- iatrogènes : tricyclique, contraceptifs oraux, phénobarbital

- Augmentation pathologique
  - alcool
  - affection hépatobiliaire (cholestase notamment)
  - hyperthyroïdie, parasite (distomatose, larva migrans)

#+print_bibliography:
