:PROPERTIES:
:ID:       e3a64c7c-5381-499f-94c7-4b969115dce3
:END:
#+title: À écouter
#+filetags: music

- [X] Brahms violin concerto - Gluzman
- [X] Antonín Dvořák performed by Mahler Chamber Orchestra & Steven
  Isserlis under Daniel Harding - Cello Concertos - 2013
- [X] Antonín Dvořák performed by Prague Symphony Orchestra under
  Charles Mackerras - Symphonies Nos. 8 & 9 - 2005
- LISTEN Gluck - Gardiner - Orphée et Eurydice (1989) [
- Franz Schubert performed by Chilingirian Quartet & Jennifer Ward
  Clarke - String Quintet in C Ave Maria and other popular songs - 2005
  (CD - FLAC - Lossless)-3297699
- Franz Schubert performed by Helmut Deutsch & Jonas Kaufmann -
  Winterreise - 2014 (CD - FLAC - Lossless)-222573
- [X] Hildegard von Bingen performed by Sequentia - Canticles of
  Ecstasy - 1994 (CD - FLAC - Lossless)-1670285
- Janet Baker & Melos Ensemble of London under Bernard Keeffe - French
  Songs - 2010 (CD - FLAC - Lossless)-808082
- [X] Modest Mussorgsky performed by Boris Christoff under Georges
  Tzipine - Complete songs - 1989 (CD - FLAC - Lossless)-1663666
- Pérotin performed by The Hilliard Ensemble - Perotin - 1989 (CD -
  FLAC - Lossless)-1054007
- Rachmaninov Piano Concertos 1-4, Paganini Rhapsody
- Anton Webern performed by Quartetto Italiano - Complete Music For
  String Quartet - 1990
- Béla Bartók performed by Takács Quartet - The 6 String Quartets - 1998
- Dmitri Shostakovich performed by Borodin Quartet - Shostakovich
  Complete String Quartets - 1994
- Erik Satie performed by Anne Queffélec - Erik Satie - 1988
- Georg Friedrich Händel performed by Akademie für Alte Musik Berlin
  under Bernhard Forck - 12 Concerti grossi, Op. 6 Nos. 7-12 - 2020
- Georg Friedrich Händel performed by Les Talens Lyriques & Sandrine
  Piau under Christophe Rousset - Opera Seria - 2004
- Georg Nigl & Olga Pashchenko - Vanitas - Schubert, Beethoven & Rihm -
  2020
- Johann Georg Pisendel & Johann Sebastian Bach performed by Amandine
  Beyer - Sonatas & Partitas BWV 1001-1006 - 2011
- Johann Sebastian Bach performed by Rachel Podger - Bach Complete
  Sonatas and Partitas for Violin Solo - 2002
- Johannes Brahms performed by Belcea Quartet & Till Fellner - String
  Quartets & Piano Quintet - 2016
- Sergei Prokofiev performed by Barbara Nissman - Prokofiev Complete
  Piano Sonatas - 2002
- Sergei Rachmaninoff performed by Various Artists - Piano Concertos
  1-4, Paganini Rhapsody (1929-41) - 2017
- Stabat Mater, Veni Creator, Litany to the Virgin Mary - 2008
- The Four Symphonies ● Tragic & Academic Festival Overtures ●
  Variations on a Theme by Haydn - 2016
- Violin Concerto in D Major, Op. 77 - Violin Sonata No. 1 in G Major,
  Op. 78 Regen - 2017

**  Jazz
- [X] AIR - Air Time - 1996 (CD - FLAC - Lossless)-1432283.torrent
- [X] Abdullah Ibrahim - Yarona - 1995 (CD - FLAC - Lossless)-158236.tor
- [X] Ahmad Jamal Trio - Ahmad Jamal at the Pershing But Not for Me - 19
- [ ] Ahmad Jamal Trio - Cross Country Tour 1958-61 - 1998 (CD - FLAC -
- [X] Albert Ayler Trio - Spiritual Unity - 1998 (CD - FLAC - Lossless)-
- [ ] Art Blakey - A Night at Birdland, Volume 1 - 2001 (CD - FLAC - Los
- [ ] Art Blakey Quintet - A Night at Birdland, Volume 2 - 2001 (CD - FL
- [ ] Art Pepper - Meets the Rhythm Section - 1986 (CD - FLAC - Lossless
- [ ] Art Tatum - The Tatum Group Masterpieces, Vol. 8 - 2003 (CD - FLAC
- [ ] Jim Hall - Concierto - 2003 (CD - FLAC - Lossless)-1189566.torrent
- [ ] Jimmy Smith - Groovin' At Smalls' Paradise - 1999 (CD - FLAC - Los
- [ ] Joe Henderson - The State Of The Tenor • Live At The Village Vangu
- [ ] Joe Pass - Virtuoso - 2002 (SACD - FLAC - 24bit Lossless)-116219.t
- [ ] John Scofield - Quiet - 1996 (CD - FLAC - Lossless)-1461849.torren
- [ ] John Surman - A Biography of the Rev. Absalom Dawe - 1995 (CD - FL
- [ ] Ken Colyer's Jazzmen - Club Session With Colyer - 2001 (CD - FLAC
- [ ] Kenny Burrell - Ellington Is Forever Volume 1 - 1993 (CD - FLAC -
- [ ] Lee Konitz - Lee Konitz With Warne Marsh - 1998 (CD - FLAC - Lossl
- [ ] Lee Morgan - The Sidewinder - 1983 (CD - FLAC - Lossless)-13069.to
- [ ] Lionel Hampton - The Chronological Lionel Hampton and His Orchestr
- [ ] Louis Armstrong - Complete New York Town Hall & Boston Symphony Co
- [ ] Louis Armstrong - The Chronological Louis Armstrong (1946-1947) -
- [ ] Louis Armstrong - The Complete RCA Victor Recordings - 1997 (CD -
- [ ] Maria Schneider Orchestra - Concert in the Garden - 2004 (CD - FLA
- [ ] Marian McPartland - In My Life - 1993 (CD - FLAC - Lossless)-61260
- [ ] Max Roach - We Insist! Max Roach's Freedom Now Suite - 1986 (CD -
- [ ] McCoy Tyner - The Real McCoy - 1987 (CD - FLAC - Lossless)-1329498
- [ ] McCoy Tyner - Time for Tyner - 2005 (CD - FLAC - Lossless)-613550.
- [ ] Mel Lewis & Thad Jones - Consummation - 2002 (CD - FLAC - Lossless
- [ ] Various Artists - 1953 Vol 2 'Modern Sounds' - 1993 (CD - FLAC - L
- [ ] Freddie Hubbard - Open Sesame - 2011 (CD - FLAC - Lossless)-126235
- [ ] George Russell - The Jazz Workshop - 1998 (CD - FLAC - Lossless)-5
- [ ] Gerry Mulligan Quartet - The Original Quartet with Chet Baker - 19
- [ ] Gil Evans & His Orchestra - Out of the Cool - 1987 (CD - FLAC - Lo
- [ ] Grant Green - The Complete Quartets With Sonny Clark - 1997 (CD -
- [ ] Helen Merrill - Helen Merrill - 2016 (SACD - FLAC - 24bit Lossless
- [ ] Henry Red Allen - The Chronological Henry Red Allen and His Orches
- [ ] Horace Silver - Blowin' The Blues Away - 1987 (CD - FLAC - Lossles
- [ ] Humphrey Lyttelton - The Parlophones, 1949-1959. Volume 1. Come On
- [ ] J.J. Johnson - The Eminent Jay Jay Johnson, Volume Two - 2001 (CD
- [ ] Jackie McLean - ''Let Freedom Ring'' - 2003 (CD - MP3 - 320)-14581
- [ ] James Blood Ulmer - Odyssey - 1996 (CD - FLAC - Lossless)-1796644.
- [ ] Jan Allan - Jan Allan-70 - 1998 (CD - FLAC - Lossless)-2046690.tor
- [ ] Clifford Brown & Max Roach - Alone Together - 1995 (CD - FLAC - Lossless)-537337.torrent
- [ ] Clifford Brown - The Complete Blue Note and Pacific Jazz Recordings - 1995 (CD - FLAC - Lossless)-2481127.torrent
- [ ] Coleman Hawkins - Body and Soul - 1996 (CD - FLAC - Lossless)-20989.torrent
- [ ] Coleman Hawkins - The Stanley Dance Sessions - 2005 (CD - FLAC - Lossless)-537526.torrent
- [ ] Dave Douglas - Convergence - 1998 (CD - FLAC - Lossless)-3208447.torrent
- [ ] Dexter Gordon - Our Man in Paris - 2003 (CD - FLAC - Lossless)-323311.torrent
- [ ] Dizzy Gillespie - Birks Works - The Verve Big-Band Sessions - 1995 (CD - FLAC - Lossless)-1442726.torrent
- [ ] Duke Ellington - Ellington at Newport 1956 - 2014 (CD - FLAC - Lossless)-3418773.torrent
- [ ] Duke Ellington - New Orleans Suite - 1990 (CD - FLAC - Lossless)-546624.torrent
- [ ] Earl Hines - Earl Hines Plays Ellington - 1992 (CD - FLAC - Lossless)-546783.torrent
- [ ] Earl Hines - Earl Hines Plays Ellington Vol. 2 - 1997 (CD - FLAC - Lossless)-546837.torrent
- [ ] Eberhard Weber - Yellow Fields - 1991 (CD - FLAC - Lossless)-229120.torrent
- [ ] Eddie Condon - The Chronological Eddie Condon (1927-1938) - 1994 (CD - FLAC - Lossless)-546953.torrent
- [ ] Ennio Morricone performed by John Zorn - The Big Gundown John Zorn Plays the Music of Ennio Morricone - 1986 (CD - FLAC - Lossless)-137383.torrent
- [ ] Eric Dolphy - Out to Lunch! - 1987 (CD - FLAC - Lossless)-1036102.torrent
- [ ] Erroll Garner - Concert by the Sea - 1987 (CD - FLAC - Lossless)-348041.torrent
- [ ] Evan Parker - The Snake Decides - 2003 (CD - FLAC - Lossless)-28629.torrent
- [ ] Fats Navarro & Tadd Dameron - Complete Blue Note & Capitol Sessions - 1995 (CD - FLAC - Lossless)-3457656.torrent
- [ ] Louis Jordan & His Tympani Five - Louis Jordan and His Tympany Five - 2001 (CD - FLAC - Lossless)-3519436.torrent
- [ ] Artie Shaw - Self Portrait - 2001 (CD - FLAC - Lossless)-3519533.torrent
- [ ] Barry Harris - Magnificent! - 1999 (CD - FLAC - Lossless)-374895.torrent
- [ ] Ben Webster - Music for Loving Ben Webster With Strings - 1995 (CD - FLAC - Lossless)-393908.torrent
- [ ] Benny Carter - Further Definitions - 1986 (CD - FLAC - Lossless)-892848.torrent
- [ ] Benny Goodman - The Complete RCA-Victor Small Group Recordings - 1997 (CD - FLAC - Lossless)-1345007.torrent
- [ ] Benny Goodman - The Famous 1938 Carnegie Hall Jazz Concert - 1987 (CD - FLAC - Lossless)-70124.torrent
- [ ] Bill Frisell - Have a Little Faith - 1993 (CD - MP3 - 320)-130063.torrent
- [ ] Billie Holiday - Lady Day Swings! - 2002 (CD - FLAC - Lossless)-2340375.torrent
- [ ] Bob Brookermeyer - New Works - Celebration - 1997 (CD - FLAC - Lossless)-514665.torrent
- [ ] Booker Little - Booker Little and Friend - 2000 (CD - FLAC - Lossless)-2530426.torrent
- [ ] Brad Mehldau - The Art of the Trio, Volume 1 - 1997 (CD - FLAC - Lossless)-3498876.torrent
- [ ] Bud Powell - The Amazing Bud Powell, Vol. 2 - 1989 (CD - FLAC - Lossless)-1222278.torrent
- [ ] Cannonball Adderley - Somethin' Else - 1983 (CD - FLAC - Lossless)-94597.torrent
- [ ] Cecil Taylor - For Olim - 1987 (CD - FLAC - Lossless)-2013452.torrent
- [ ] Charles Mingus - Charles Mingus Presents Charles Mingus - 2011 (CD - FLAC - Lossless)-817257.torrent
- [ ] Charles Mingus - Pithecanthropus Erectus - 1998 (CD - FLAC - Lossless)-971702.torrent
- [ ] Charlie Parker - The Complete Dial Sessions - 1993 (CD - FLAC - Lossless)-739855.torrent
- [ ] Charlie Parker - The Complete Savoy & Dial Master Takes - 2020 (WEB - FLAC - Lossless)-3030113.torrent
- [ ] Chris Barber - The Complete Decca Sessions 1954-55 - 2000 (CD - FLAC - Lossless)-530835.torrent
- [ ] The Clark Terry Five - Memories of Duke - 1990 (CD - FLAC - Lossless)-536835.torrent
- [ ] Wes Montgomery - The Incredible Jazz Guitar of Wes Montgomery - 1987 (CD - FLAC - Lossless)-896562.torrent
- [ ] Wynton Marsalis - J Mood - 1986 (CD - FLAC - Lossless)-889993.torrent
