#+title: Gastro-entérites
#+filetags: microbio

# -	Pour Norovirus et Rotavirus :
# o	Epidémiologie/ transmission, durée d’incubation, physiopathologie, symptômes
# -	Pour Adénovirus, Astrovirus
# o	Epidémiologie/ transmission, symptômes
# -	Modalités du diagnostic virologique des GEA virales
# -	Stratégie des examens microbiologiques face à des cas groupés de GEA
# -	Principales mesures d’hygiène permettant de lutter contre une épidémie de GEA

Principale complication = déshydratation
* Virale
- Transmission : féco-orale direct (interhumaine)  ou indirecte (aliments, eaux, environnement)
- Faible nombre de particules ingéres pour entraîner une GEA
- Virus non enveloppé résistant à l’acadidé gastrique
- toutes tranches d’aĝe mais le plus souvent enfant en bas âge
- multilpication dans les entérocytes de l’intesting grêle
- infections le plus souvent courte avec diarrhé, douleur abdo, vomissement
- greffés/transplanté: peut devenir presistant/chronique
- incubation courte, excrétion virale prolongee
- Immonoenzymatique, trousses commerciales (ELISA, tests unitaire), PCR temps réel
  - immunoenzymatique: très spécifique, sensible pour rota, adéno et astrovirus mais pas pour la détection des norovirus -> technique plus sensible
** Rotavirus
- Réservoir humain (animaux pour rotavirus spécifiques)
- Transmission : féco-orale, interhumaine, par les mains ou objets contaminés par des feces/vomissure.
  NB: perte de son infectiosité en milieu humide
*** Épidémiologie
- groupe A:
  - France, enfant < 5 ans  140 000 consultations, 18 000 hospitalisaiton, décès exceptionnel
  - *1ere cause de diarrhée aigùe de l’enfant < 5 ans*
- 1ere cause d’infection nosocomiale en pédiatrie, 27-32% nosocomiales selon les pays
  - monde = 29-45% hospitalisation pour diarrhées sévères, 600 000 morts/an (pays bas/moyens revenus)
- adulte/enfant plus gế : réinfetion commune mais clinique très modérée. Surtout un vecteur de transmission

*** Physiopathologie
 Lésions des entérocytes matures de l’intesting grêle -> 3 mécanismes
- diarhée sécrétoire (sécrétion eau, électrolytique)
- diarrhée de malabsorption et osmotique (lyse cellulaire , perturbation des fonctions enzymatique)
*** Clinique
- variable : asymptomatique - diarrhées malabsorption/sécrétoire
- incubation < 48h
- symptomes de 1 à 4 jours. NB: excrétion du virus peut précèder de quelques jours et persister 8-10 jours
  - infections asymptomatique habituelle de 1 à 3 mois (immunité maternelle) (NB : immunité secondaire chez adulte)
- diarrhée
  - aqueuse non glairo-sanglante (parfois explosive), vomissement, douleur abdo, hyperthermie modérée 38°
  - intensité = variable
  - consistance variable (molle - liquide)

*** Diagnostic
- Test immo-chromatographique
- Test immuno-enzymatique (ELISA) = détection antigène dans les selles (anticorps monoclonaux)
:PROPERTIES:
:ID:       c6e06bd3-6ecb-4c03-a2eb-05f4c8c77ce0
:END:
#+title: Norovirus
#+filetags: personal medecine viro
** Norovirus
*** Transmission
- Féco-orale, vomissure, persone-personne (EHPAD+++), souillures, projection, aérosol (eau++)
- Très infectieux
- Contagion possible par sujet asymptomatique.
*** Épidémiologie
- Souvent sous forme d'épidéime.
- Surtout en hiver
- *> 85% des épidémies de GEA non bactériennes quelque soit l’âge*
- Problème de santé publique : infections nosocomiale, EHPAD
- Le virus le plus fréquemmentd responsable de TIAC (eau souillée, personne porteuse) : 10-26% des cas

  Attention: persistance excrétion virale semaine après la guérison
Probablement réplication jejunum : atrophie villositaire -> malabsorption transitoire (altération système enzymatique des entérocyte)
*** Physiopathologie
- nivation épithélium par lymphocytes T CD8+
*** Clinique
- Bénin chez adulte/enfant bonne santé (très rarement déshydratation)
- Plus problématiques dans certains pays (= aussi sévère que rotavirus)
- Incubation 4-77heures
- Nausée, vomissement, diarrhée, fièvre modérée douleur abdominale
- Diarrée liquide sans mucus/sang/leucocyte
- Infections chroniques parfois sévère chez l'immundodéprimé (perte de poids, déshydrataition...)
*** Diagnostic
- test immuno-chromatographique: spécifique, peu sensible
- standard = RT-PCR, RT-PCR en temps réels
*** Traitement, vaccination
- Pas de traitement antiviral
- Prévention = lavage des mains, désinfection surface, hygiène du voyage, hôpital = iidem
- Pas de vaccin

** Adénovirus
*** Épidémio
- toute l’année (épidémique ou sporadique)
- *3-6% GEA infectieuses du nourission*
** Astrovirus
*** Épidémio
- épidémies en ivoers, surtout nourrisson
- 1-4% GEA enfant et adulte
*** Physiopatho
Entérocytes matures , sommets des villosités
*** Diagnostic
ELISA
RT-qPCR

** Modalités du diagnostic virologique des GEA virales
- forme sévère de l’enfant: recherche rotavirus
- porteur asymptomatique en pédiatrie
- enfant/personne âgée avec symptômes en hospitalisation + symptôme (prévenir infection nosocomiale)
** Stratégie des examens microbiologiques face à des cas groupés de GEA
- immunodétection ou PCR temps réel -> noro, rota, adéno, sapovirus, adénovirus
- Origine alimentaire/hydrique = norovirus le plus souvent -> recherche norovirus
** Principales mesures d’hygiène permettant de lutter contre une épidémie de GEA
