:PROPERTIES:
:ID:       924c049e-889c-40b7-8516-334107704df7
:END:
#+title: Divers
* Candidatures ingénieur de recherche CNRS
:PROPERTIES:
:ID:       53303519-ef0d-4c44-9d68-6ee8d758892d
:END:

Regarder dates. Grilles prédéfinies mais dépendent peu du candidat.
Montrer qu'on coche toutes les cases. On a une chance face aux candidats
locaux. Ne pas contacter l'équipe (?)

** IR inria (concours externe, SED)
Examen écrit. Sur projet pendant 5 ans puis changement d'équipe.
Contacter l'équipe

** IR université
Site spécialise. Mieux payé mais pas de mobilité. Contacter l'équipe

** Ecole d'ingénieurs (supelec)
Voir ABG

** Chargé de recherche CNRS, inria

* Questions passerelle médecine
:PROPERTIES:
:ID:       2b66a647-0edd-4b72-8ffa-8c506965a466
:END:

Inscrit en P1 ? Retrait admin Qu'avez-vous retenu de votre doctorat ? Et
la bio informatique ? Qu'est-ce qui vous a intéressé dans le contact
avec le patient ? Cette "enquête" sur le patients, vous l'avez déjà eu
dans vos études ? Donc vous abandonnez les mathématiques et la rigueur
pour l'irrationalité ? Quelle spé ? Plutôt des questions pour
comprendre. Jury bienveillant, plutôt attentif. Certains souriants

* Calcul des mensualités pour un taux d'intérêt
:PROPERTIES:
:ID:       dfadd44c-5a92-41b3-acc8-2079e1128a56
:END:

Soit C_{0} le capital emprunté, $n$ le nombre de mensualités et $t$ le
taux d'intérêt annuel, $t_m$ le taux d'intérêt mensuel. Attention, la
formule se faut t_{m}, qui se calcule soit t_{m} = t/12 (taux
prortionnel) soit par t_{m} = -1 (taux actuariel)

Au final, la mensualité est M =
