:PROPERTIES:
:ID:       8217cf86-05c6-4472-83f1-aff2ef986d6b
:END:
#+title: Turbidimétrie
#+options: toc:nil
#+filetags: medecine biochimie technique
* Description
Il s'agit d'une technique de photométrie en milieu trouble. Elle mesure la diminution de l'absorbance d'un rayon lumineux de longeur d'onde connue au travers de la solution.
Les particules en solution vont diffuser le rayon lumineux et ce, en fonction de la concentration de la solution et de la taille des particules.

La turbidimétrie mesure la lumière transmise, alors que la néphélométrie mesure la lumière diffusée par l'échantillon.

En immunologie, les antigènes à doser vont être mis au contact d'anticorps créant des complexes antigènes-anticorps. Ces complexes vont être analysés de la même manière.

* Points forts
- Rapide
- Simple à mettre en oeuvre
- Non invasif pour l'échantillon
* Points faibles
- Meilleure sensibilité avec la néphélométrie
* Interférences
- Hémolyse,  ictère, lactescence
- Anticorps hétérophiles, cryoglobuline, facteur rhumatoïde
- Excès d'antigène : les complexes antigène-anticorps se dissocient (effet "crochet")
- lipoprotéine, fibrine
* Paramètres représentatifs
| Inflammation           | Dénutrition  | Immunitaire |
|------------------------+--------------+-------------|
| CRP                    | albumine     | IgG         |
| haptoglobine           | pré-albumine | IgM         |
| \alpha2-macroglobuline | RBP          | IgA         |
| complément C3          |              | C3          |
| orosomucoïde           |              |             |
| transferrine           |              |             |
| albumine               |              |             |
