:PROPERTIES:
:ID:       f9d35304-7a95-4bbd-9230-35030a692ef4
:END:
#+title: Bactériologie
#+filetags: medecine bacterio

* Culture
:PROPERTIES:
:ID:       c191b424-bbcd-4ead-a5ef-2057bd766b60
:END:
- Gélose au sang = non sélectif. Pouvoir hémolytique
- Bouilon Schaedler = bactéries anaérobie et exigeantes (incubation 10-14jours en anaérobie) -> prélèvement profonds, IO
- Chromogène urinaire = non sélectif
  - rose = activité \beta-galactosidase
  - bleue = activité \beta-glucotosidase
  - violet = les 2
  - brun = tryptophane désaminase
** Autres
- Chocolat enrichi :bactéries exigeants (prélèvmente profond)
- HAE2 :inhibie bactéries gram + -> Haemophilus spp
- VCAT : Neisseria (Vancomycine, Colistine, Amphotéricine, Triméthoprime)
- Drigalski : inhibe Gram+, lactose ->
  - jaunes = BGN fermentant lactose
  - bleu = BGN ne fermentant pas le lactose
- Cétrimide (ammoniuum)) -> P. aeruginosa (production pycyanine)
- BCSA : inhibe gram+ ->_Burkholderia
- Chappman : NaCL, mannital
  - jaune = fermente mannitol -> S. aureus
- CAP = inhibie Gram - () -> streptocoque+++, listeria, corynebcaterie, uropathogène émergents
- Granada (MTX) : inhibe Gram - -> S. agalactiae
- BCYE : Legionnella)
- Haja-Kligler : lactose en haut, glucose en bas
  - rouge en haut = pas de fermentation de lactose. Sinon jaune
  - rouge en bas = pas de fermentation du glucose. Sinon jaune
    Exemple:
    - Shigella = lactose-, glucose+
    - Pseudomonas aeruginosa = lactose-, glucose - (tout rouge)
    - Salmonella = tout noir (production H2S)
    - E.coli = tout jaune (lactose+, glucose+)
** Coproculture = Salmonelle, Shigelles, Campylobacter
- Gélose Hektoen : inhibiteur de gram+, sucres (lactose, saccharose)
  - centre noir = formation de H2S ->_Salmonelle
  - vert/bleu = pas de fermetation -> Salmonelle/Shigelle
  - jaune/orange = fermetation
- Bouillon sélénite (inhibe coliforme + entérocoqu, enrichi pour Salmonelle)
- Gélose Salmonelle-Shiguelle : inhibiteur gram+, _lactose_
  - centre noir = H2S -> Salmonelle
  - jaune = pas de fermentation -> Salmonelle/Shigelle
  - rose/rouge = fermentation lactose
- Gélose sélective Campylobacter (inhibe Gram+, Gram-, champignon)
- Yersinia: mannitol, inhibiteur GRam+ (dont Proteus), Gram- (dont Pseudomonas aeruginosa)
  - rouge = fermente mannitol -> Yersinia
* Bactéries
:PROPERTIES:
:ID:       4d393ab4-61bd-48ab-b095-03c6bc16b939
:END:
** Staphylococcus aureus
Cocci Gram+ en ama : aérobie +/- anaérobie. Immobiles

**** Facteurs de virulence
- *coagulase*
  - libre = excrétée, clive le fibrinogène -> embole septiques. Différence avec les staph. à coagulase négative (S. epidermidis)
  - liée = récepteur au fibrinègène, sur la paroi bactérienne -> diag (test d'agglutination)
- protéine A: liaison aux immunoglobuline
- hémolysine : lyse des hématies
- staphylokinase : libère bactéries des emboles
- *toxine* : leucocidine de Panton et Valentine (LPV), toxine du choc staphylococcique (TSST1-1 -> activation lymphocytes T), exfoliatines, entérotoxines thermostables

**** Habitat
- 30% porteur sain (transitoire ou non)
- Transmission intra-humaine par les mains ou indirectevement (vêtements...)
- Commensal : microbiote nasal, oropharyngé, digestif, cutané (aisselles)

**** Clinique
- Porte d'entrée = cutanée <-> site de portage/infection
- Infection communautaires, associées aux soins
- Infection toxiniques :
  - LPV : infection cutanée, pneumonie nécrosante
  - TSST1 = choc toxinique avec érythrodermie. Entrée = vaginale ou cutanée
  - exfoliatine: impétigo bulleux, syndrome d'exfoliation généralisée
  - entérotoxine = diarrée à +2h ou 4h, TIAC
- Infections suppurative
  - cutanée superficielle (furoncle, impétigo, folliculite) ou profondre (abcèse, fasciite)
  - bactériémie, endocardite
  - infections profondes : ostéo-articulaire, pneumopathie, neuroméningées (abcès)
**** Diagnostic
- Culture : non exigeante
  - gélose sang 24h: beta-hemolytique (hémolyse total)
  - Chapman (mannitol + NaCl) : rouge -> jaune avec NaCl
  - catalase +
** TODO Pseudomonas aeruginosa
Bacille Gram négatif, très mobile

Origine : environnement++
Opportuniste :
- infection nosocomiale (matériel) ou . 1ere bactérie en réa
- mucoviscidose
Facteurs de virulence : exotoxine, exoprotéines, hémolysine
Facteur d'adhésion
Forte capacité à former des biofilms

*** Diagnostic
- Pousse 24h à 37% sur milieu non sélectif.
- Milieu sélectif : cétrimide
- Oxydase positif (!= entérobactéries) -> test rapide pour différencier les 2
*** Résistance
Faible perméabilité membranaire : résistance naturelle pénicillines, C1G et C2G +/- certaines C3G
+ , Catalasoe positif - lactose négatif
** TODO Streptocoques
*** α-hémolytique : hémolyse partielle
- viridans
- Pneumocoque: résistance par chimérisme PLP (acquis)
*** β-hémolyse : hémolyse totale
- Groupe A = S. pyogenes surtout. Cause d’angine++. *Pas de résistance aux β-lactamine*
- Groupe B = S. agalactiae
 Infection materno-foetale ++ (note: l’antibioprophylaxie marche chez les nouveau-né mais seulement pour les infections avant 7 jours)
- Groupe C, D, F, G, H
* Classification
:PROPERTIES:
:ID:       73fe5cc4-08a6-402a-8237-156e21ef7bc3
:END:
Gram
- positif si paroi épaisse de peptidoglycane -> coloration persiste
- négative si paroi plus fine qui permet à l'éthanol de laver la coloration
* Maladies infectieuses
:PROPERTIES:
:ID:       d8f64639-c70a-419c-8219-4418508a76db
:END:
** TODO Infection urinaire
_Groupe 1_ : *Seuil = 10^3*. Critères majeurs de pathogénicité (e.g adhésion à l’épithelium urinaire) -> responsable si urine non contaminé, même en petite quantité
- *E. coli* (75%-80% des cystites simples)
- *S. saprophyticus* (cystites aigües communautaires chez femme de 15-30ans)
- Salmonella spp.
- mycobactéries
- leptospire

_Groupe 2_ = *Seuil = 10^3 homme, 10^4 femme*. Plutôt IU associées aux soins si facteurs anatomiques/iatrogènes
- entérobactéries (Proteus, Klebsiella, Enterobacter, Citrobacter, Morganella, Providencia)
- Pseudomonas aeruginosa
- Enterococcus
- Aerococcus urinae
- Staphylococus aureus
- Corynebacterium urealyticum

_Groupe 3_: *Seuil 10^5*. Implication discutée. Nécessite bactériurie élevée + 2 échantillons + critères clinique + inflammation
- Gram + : Streptococcus agalactiae, staph à coagulase négative autre de S. saprophyticus
- entérocoque avec E. coli
- Gram - : Actinetobacter, Oligella urethralis, Stenotrophomonas maltophilia, Burkholderia cepacia
- Candida

_Groupe 4_ : *Seuil: non*. Contaminant
- lactobacillus (sauf L. delbrueckii)
- streptococques alpha-hémolytique
- Gardnerella vaginalis
- bacilles corynéforme (sauf C. urealyticum et C. seminale)

Uropathogènes exigeants : Aerococcus, A. shaalii, A. omnicolens et L. delbrueckii
/ chez > 65 ans, < 3 ans et patho urologie (sauf cancer vessie et prostate) -> à chercher dans ce contexte
* Antibiotiques
:PROPERTIES:
:ID:       2fe3ff58-a4ef-41f0-9d77-b8e895d5474d
:END:
** Généralités
- Actifs sur les bactéries en phase de multiplications
- Cibles
  - inhibition synthèse de la paroi bactérienne = \beta-lactamine, glycopeptides, fosfomycine
  - synthèse ADN bactérien : quinolone, sulfamide
  - synthène ARN : rifampicine
  - synthèse protéines bactéirenne : aminoside, macrolides, cyclines

Donc :
- \beta-lactamine inefficaces sur les mycoplasme car pas de paroi !
- glycopeptides inefficaces sur bactérie Gram négatif car elles ont une membrane externe qui ne laisse pas passer les grosses molécules
- synergie \beta-lactamine - aminoside sur strepto et entérocoque : destruction de la paroi par les \beta-lactamine pour que l'aminoside accède au ribosome
- seules les antibio pénétrant dans les cellules (macrolides, fluoroquinolones, rifampicine, cycline ) sont actives contre les bactéries "intracellulaires " (Chlamydia, Coxiella burnetti, Rickettsia, Legionella pneumophilia, Brucella meltiensi, Bartonella )

Résistances :
- naturelles
  - Listereia monocytogene et entérocoques résistant C3G
  - anaérobie résistant aminosides
  - Gram négatig résistant glycopeptides
  - Entérobactérie
    - groupe 1 (E. coli, Proteus mirabilis) = sensible amoxKlebsiella résistant amoxicilline
    - groupe 2 (Klebsiella) résistant amox mais sensible amox+acide clavulanique
    - groupe 3 (entérobacter, Morganella, SErratia, Providencia): résistant amox, amox+acide clavulinaque, C1G et C2G (mais sensible C3G)
- acquises :
  - Streptococcus pneumoniae : sensibilité diminuée pénicilline G, résistant macrolide
  - E. col : amox souvent
  - Staphylocoques peut être résistant pénicilline M
  - S . aureus :
    - < 20% ont une modification de la cible des \beta-lactamine (protéine de liason à la pénicilline = PLP2a) -> résistance à toutes les \beta-lactamine = meti-R
    - 90% résistance acquise à pénicilline G (sécrétion pénicilinase) mais restent sensiblie pénicilline M = méti-S
      - entérobacteries = réistance \beta-lactamine par production de \beta-lactamase
** Aminosides
Action = bactéridice, concentration dépendantes. Perturbe la synthèse des protéine (fixation sous unité 30s des ribosomes)
Résistances
- naturelle: anaérobie strictes et préférentielle (streptocoques, entérocoques) par défaut de pénnétration car le système de transport nécessite la force produite par les chaînes respiratoire aérobies
  /NB: penicilline + amoniside passe car agit sur la paroi bactérienne/
** Sulfmaide
Bactériostatique (inhibe croissance) mais en synérgie devient bactéricide
Ex: sulfamethoxazole + trimethoprime (Bactrmie)

Mécanisme : inhibe synthèse microbionne d'acide folique
** Fluoroquinolone
- 4 générations: initialement répartition extra-cellulaire -> large et homogène (intracellulaire) avec les dernières générations
- Élimination rénale et bile
- Effets indésriable nombreux : digestif, phototoxique, trouble nerveur, inhibe cytochrme P450 (! interactions)
- Contre-indication : déficit G6PI, grossesse
- Action : inhibe réplication et transcription ADN
- Bactéricide, concentration dépendantes
- Indication :
  - quinolones = cystite aigùe simple non compliquée, récidivantes chez l'adulte
  - 2e génération : infetions sévères à bacille Gram négatif
  - 3e et 4e génération : sinusite aigüe bactériennes, exacerpbation pneumopathie communutaire, infection compliquée peau + tissus mous

    Résistante : en augmentatino chez entérobactéries (E. coli, Klebsiella)
* Divers
** Résistances
** Staph aureus
Sensibile aux pénicillines mais 90% sont résistantes à la pénicilline G  (sécrétion d'une pénicillisanes).
Ils restent sensibles à la pénicilline M = /méti-S/
Attention: < 20% ont résistance à toutes les beta-lactamines ! (modification de la cible = protéine de liaison à la pénicilline PLP2A) ->
/meti-R/ (SARM)
** Entérobactéries
Résistantes aux beta-lactamine par production de beta-lactamase
** Technique
*** PCR 16s
