:PROPERTIES:
:ID:       8b651cd6-01a9-48d2-bc89-c9340affe2d9
:END:
#+title: Coxymétrie
#+filetags: biochimie,gds

Hémogolbine : 4 hèmes dans les α et β-globine. 1 hème contient des atomes de fer

Réaction d'oxydoréduction :
désoxyhémoglobine + O2 -> oxyhémoglobine (dans les poumons, sino réaction inversie. c.à-d de réduction dans les vaisseux)
H
désoxyhémoglobine = Hb réduite -> plus important en prélèvement veineux

* Dyshémoglobine
** Monoxyde de carbone
- endogène = catabolisme de l'hème
- exogène : combustion bio, gaz d'échappement, incendie, tabagisme
 Le CO se fixant sur le fer de l'hème -> carboxyhémoglobine. Il est en compétition avec l'O_2
 Taux physiologique < 1.5-2%

*** Intoxication CO
*Urgence*
Clinique
- aspécifique = céphalées, anusée, asthénie...
- puis vomissement, dysonée
- enfin convulsion, coma hypertonique
Bio: acidose métabolique, hyperglycémie
Ttt = oxygénothérapie
** Méthémoglobine
Oxydation Fe2+ -> Fe3+
Incapable de transporter oxygene
Physiologique 1-1.5%
Voie : NADH cytochrome β5 déductase

Clinique: rapide (<1h)
- cyanose extrémités
- dysponée, vertiges
- trouble conscience, convulsio, coma

Oxygénothérapie de résout as l'hypoxe.
Sang brun foncé

Origine
- héréditaire
- acquise (alimentaire, profession, fumées...)

Traitement : éviciton cause, beul de méthylène (réduit le Methhb)

*Urgence*
** Sulfhémoglobine
+groupement thiol sur hème
Hb couleur verdâtre
O2 peut se fixer mais affinité très diminuée
Médicament ou toxique+++
détecté mais non quantité par les automates

* TODO Mesure
 Spectrophotométrique: optique -> une valeur d'absorbance pour 128 λ
 loi de Beer-lambert donne relation entre absorbance et concentration

 L'absorbance totale est mesure mais les coefficients de contribution de chaque Hb est connue
 Sont rendus
|                             | Valeurs (%)  |
|-----------------------------+---------|
| oxyhémoglobine (O2Hb)       | 95-98   |
| désoxyhémoglobine (HHb) 0-5 | 0-5     |
| carboxyhémoglobine (cCOHb)  | < 1.5%  |
| methémoglobine (MetHb)      | <1.5    |

*Une méthémglobine significative est une urgence*
 Sont *calculé* : fraction oxyHb, sat O2, Hématocrite

 Correction interférence : Hb foetale (spetrect différent), sulfhémoglobine

** Piège
 *La sat ne prend pas en compte un dyshémoglobine* sO = cO2HB / (cOHb + cHHb)
 Donc faussement normale si intoxication
