#+title:      Staphylocoque aureus
#+date:       [2024-08-28 mer. 19:21]
#+filetags:   :bactério:
#+identifier: 20240828T192156


Cocci Gram+ en amas : aérobie +/- anaérobie. Immobiles. non capsulé, non sporulé

* Facteurs de virulence
Associé à la paroi:
 - *coagulase* liée = sert récepteur au fibrinogène, sur la paroi bactérienne -> diag (test d'agglutination)
 - protéine A: liaison aux immunoglobuline, protection contre la phagocytose

Excrété
 - hémolysine : lyse des hématies (β-complète)
 - coagulase libre = clive le fibrinogène -> embole septiques. Différence avec les staph. à coagulase négative (S. epidermidis)
 - staphylokinase : libère bactéries des emboles
 - *toxine* :
   - leucocidine de Panton et Valentine (LPV) -> leucotoxique dermonécrotique
   - toxine du choc staphylococcique (TSST1-1 -> activation lymphocytes T
   - exfoliatines -> érythrodermie bulleuses
   - entérotoxines thermostables -> TIAC

* Habitat
- 30% porteur sain (transitoire ou non)
- Transmission intra-humaine par les mains ou indirectement (vêtements+++)
- Commensal : microbiote nasal, oropharyngé, digestif, cutané (aisselles)

* Clinique
- Porte d'entrée = cutanée <-> site de portage/infection
- Infection communautaires, associées aux soins
- Infection toxiniques :
  - LPV : infection cutanée, pneumonie nécrosante
  - TSST1 = choc toxinique avec érythrodermie. Entrée = vaginale ou cutanée
  - exfoliatine: impétigo bulleux, syndrome d'exfoliation généralisée
  - entérotoxine = diarrée à +2h ou 4h, TIAC
- Infections suppurative
  - cutanée superficielle (furoncle, impétigo, folliculite) ou profonde (abcès, fasciite)
  - bactériémie, endocardite
  - infections profondes : ostéo-articulaire, pneumopathie,
    neuroméningées (abcès)

* Diagnostic
- Culture : non exigeante
  - gélose sang 24h:
    - *beta-hemolytique* (hémolyse total)
    - coloration dorée (d'où le nom)
  - Chapman (mannitol + NaCl) : rouge -> jaune avec NaCl par fermentation du mannitol
  - catalase +, oxydase-, DNAse + (à la différence des strepto à coagulase négative)
  - NB: test d'agglutination pour différencier des staph coag négative théoriquement possible (alternative MALDI TOF)

* Sensibilité et résistance
Résistance fréquente à l'hôpital
- β-lactamines :
  - phénotype sauvage sensible
  - pénicilinase > 90% des souches (disque FOX de pénicilline g): résistance pénicilline G, V, A par hydrolyse -> restauré par un inhibiteur de β-lactamase
  - SARM = gène mecA : code pour PLP2 additionnelle -> résistance à toutes les β-lactamines *et imipénème*. Souvent multirésistance aminoside, macrolide, fluoroquinolonie
    - vancomycine en 1ere intention
    - C4G possible mais pas en france
- Aminoside : sauvage sensible, résistance acquise par inactivation enzymatique
- Glycopeptide : sauvage sensible, phénotype GIA/hétéroGISA (I = intermediate) avec sensibilité diminuée, phénotype gRSA (résistance)
- Fluoroquinolones : sauvage sensible, résistance possible par modification de la cible
- MLSK (macrolides, lincosamide, streptogramines, kétolides) : sensible, résistance par méthylation ARN ribosomique 23S

* Traitement habituellement actifs
 oxacilline, gentamicine (aminoside), vancomycine (glycopeptide)
