#+title:      Gaz du sang
#+date:       [2024-08-02 Fri 23:41]
#+filetags:   :biochimie:
#+identifier: 20240802T234159


* pH
Le pH représente l'activité de l'ion hydrogène, qui reflète l'équilibre
acide-base dans le sang. Il doit être régulé dans des marges étroites
car des variations importantes peuvent rapidement avoir des conséquences
délétères pour le métabolisme cellulaire, notamment sur le plan
vasculaire.

- Production: nombreuxs métabolismes (acides aminées, protéines...) ou
  issus de substances toxiques (méthanole, acide oxalique, acide
  formique)
- Élimination: principalement par les poumons +/- reins, estomacs
  (vomissements...), intestin (diarrhée)

Valeurs de référence (adulte) - artériel : 7.38 - 7.42 - veineux :
7.32 - 7.38

* pO2
Dans les poumons, l'oxygène diffuse au niveau des alvéoles via le sang.
Il y est combiné à l'hémoglobine des globules rouges et transporté vers
les cellules dans les artères. Il est ensuite libéré dans les tissus.
L'oxygène est consommé pour la respiration cellulaires par les
mitochondries afin de générer de l'énergie sous forme d'ATP

Valeurs de référence (adulte) - pO2 artériel : 70 - 100 mmHg (9.5 - 13.3
kPa)

* CO2
Le CO2 transporté dans le sang est sous 2 formes : dissous dans le
plasma et le cytoplasme des globules rouges et combinés sous forme de
bicarbonate, ainsi que lié à l'hémoglobine.

Le CO2 est produit lors du métabolisme cellulaire normal de manière
continue et libéré dans le sang. Il est ensuite transporté dans les
poumons, où aura lieu une diffusion des capillaires pulmonaires dans les
alvéoles. Il sera ensuite expiré.

Valeurs - artériel : 35 - 46 mmHg (4.7 - 6.1 kPa)

* Principe analytique de mesure
Ampérométrie par mesure du courant généré entre 2 électrodes suite à la
réaction d'oxydation du CO2

* Principales interactions analytiques
- Dilution si prélèvement sur cathéter
- Tube EDTA, citrate, fluorure *proscrits*

* Vigilance pré-analytiques et analytiques
- Vérifier que la température est renseignée
- Absence de caillot ou de bulle
- Seringue/capillaire hépariné
- 1mL minimum pour une seringue (si < 0.5, choisir une analyse), 100μL
  pour un capillaire

* Augmentation et diminution
La pO2 reflète l'état respiratoire général.

- Une pCO2 faible traduit une hyperventilation
- Une pCO2 élevée révèle une hypoventilation ou insuffisance
  respiratoire
  - soit d'origine pulmonaire
    - BPCO sévère
    - Emphysème pulmonaire sévère
    - Résection chirurgical
    - Pneumopathie inflammatoires
  - soit d'origine non pulmonaire
    - défalliance du Contrôle ventilatoire
      - origine cérébrale : infections, traumatismes, tumeurs, AVC
      - centres respiratoire :
        - perte de contrôle (sédatifs, Parkinson, tétanos...)
        - lésions voies afférentes/éfférente (traumatisme médullaire
          cervical, sclérose en plaque)
        - récepteurs périphériques : syryngomyiélie, neuropathie
          diabétique
      - Pompe ventilatoire
        - neuromusculaire : SLA, Guillairn-Barré, toxique, myasthénie
          hypokalémiée, hypophosphatémie
        - cage thoracique : Cyphoscolioase, fibrose, obésité...
Voir aussi [[denote:20240802T160025::#h:b3c55bbf-cbba-4ba2-972f-6bd77abe8801][Grossesse::Gaz du sang]]
