:PROPERTIES:
:ID:       c085bebe-fe0c-4a2d-958e-64a8b0aec5eb
:END:
#+title: Infections urinaires
#+filetags: ​bacterio

- Tractus urinaire stérile, extrémité distale de l'urètre colonisé
- Pénétration des bactéries : à partir de l'urètre (ascendant), plus rarement sur sonde, endoscopie, chirurgie
- Facteurs prédisposants : calcul (obstactle), hypertrophie prostate, malformation voie urinaire, grossesse, diabète+++

* Démarche
- cystite simple : bandelette urinaire : leucocyte, nitrite. VPN chez la famme, VPP chez l'homme
- sinon: risque de complication, PNA; dépistage pour grossesse, chir ; échec traitement; > 4 épisodes par an -> EBCU (bactérie + antibiogramme)
* ECBA
** Préanalytique
- Prélèvement
  - Naturel : lavage main + toilette, urine 2eme jet
  - jeune enfant : collecteur d'urine +/- cathéter/ponctio sus-pubienne
  - Sonde: jamais dans le sac préleveur, recueillir après désinfection sur site dédié. Ne pas envoyer sonde
- Conservation:
  - tube stérile 2h à température ambiante, 12h cyto, 24h à 4° pour culture
  - tube borate: 48h si /bien rempli/

** Analytique
  - cytologie : manuel/automatique
  - Gram : non obligatoire, peu sensible mais permet d'identifier une contamination, d'orienter les milieux d'ensemencement
  - ensemencement : chromogène + /- sélectif pour Gram positif, levures+++. 16-24h à 35°, 48h si croissance lente, discordante.

* Groupes :
** Groupe 1 = pathogène. Seuil = $10^3$
Critères majeurs de pathogénicité (e.g adhésion à l'épithelium urinaire) -> responsable si urine non contaminé, même en petite quantité

- *E. coli* (75%-80% des cystites simples)
- *S. saprophyticus* (cystites aigües communautaires chez femme de 15-30ans)
- Salmonella spp.
- mycobactéries
- leptospire

** Groupe 2 = si facteurs.  Seuil = 10^3 homme, 10^4 femme
Plutôt IU associées aux soins si facteurs anatomiques/iatrogènes

- entérobactéries (Proteus, Klebsiella, Enterobacter, Citrobacter, Morganella, Providencia)
- Pseudomonas aeruginosa
- Enterococcus
- Aerococcus urinae
- Staphylococus aureus
- Corynebacterium urealyticum

** Groupe 3 = discuté. Seuil 10^{5}
Implication discutée. Nécessite bactériurie élevée + 2 échantillons + critères clinique + inflammation

- Gram + : Streptococcus agalactiae, staph à coagulase négative autre de S. saprophyticus
- entérocoque avec E. coli
- Gram - : Acinetobacter, Oligella urethralis, Stenotrophomonas
  maltophilia, Burkholderia cepacia
- Candida

** Groupe 4 = contaminant. Pas de seuil
- lactobacillus (sauf L. delbrueckii)
- streptococques alpha-hémolytique
- Gardnerella vaginalis
- bacilles corynéforme (sauf C. urealyticum et C. seminale)

* Étiologie
- E. coli = 50 à 95% (communautaire ou associé au soin)
- S. saphrophycitus : 5-20% IU communtaire, surtout chez la femme jeune

* Virulence
- Capacité de colonisation + invasion des cellules urothéliale
- Biofilm

* Interprération
| Dispositif | Clinique | Leucotyurie | Bactéurie  | IU                   | Antibiogramme |
|------------+----------+-------------+------------+----------------------+---------------|
| Non        | oui      | oui         | cf seuils  | oui                  | oui           |
|            | non      | oui/non     | >= 10^{3}  | colonisation         | non           |
|            | oui      | non         | cf tableau | débutant/neutropénie | oui           |
|------------+----------+-------------+------------+----------------------+---------------|
| Oui        | oui      | NC          | >= 10^{5}  | oui                  | oui           |
|            | non      | NC          | >= 10^{3}  | colonisation         | non           |

- *colonisation* femme *enceinte* avec bactérurie >= 10^{5} groupes 1 à 3* : antibiogramme !!
- si invasif : significatif si > seuil

Clinique > biologique (décapité par antibio, croissance lente)

* Uropathogènes emergents
- (Gram+): Aerococcus spp, Actinotignum shaalii, A. omnicolens et L. delbrueckii
- chez > 65 ans, < 3 ans et patho urologie (sauf cancer vessie et prostate) -> à chercher dans ce contexte
