#+title: Biochimie

* Albumine
** Naissance
Synthèse par les hépatocytes
** Vie
60% secteur interstitiel, 40% vasculaire (=2/3 protéines circulantes)
** Mort
Demi-vie 20 jours
** Effet
Maintien de la pression oncotique vascualire
Protéine de transport pour des substances inactives mais rapidement mobilisables : homornes, acides aminés, acide gras, vitamine, médicament
** Indication
Syndrome inflammatoire chronique
Fuites protéiques (entééropathies exsudatives, syndrome néphrotique)
Dénutrition chronique
** Dosage

* Vitamine D
** Naissance
La vitamine D est apportée par
- synthèse à partir des rayonnements UV sur la peau
- l'alimentation (vitamine D2 [végétal] et D3 [animal])

** Vie
Elle s'accumule dans le foie puis une première hydroxylation conduit à 25-OH-vitamine D (calcidiol).
Après transport via le sang dans le rein, une seconde hydroxylation rein conduit à 1,25-di-OH vitamine D (calcitriol = forme active de la vitamine D)

La première est peu controléee mais la seconde est régulée par la PHT et phosphatémie :
- PTH, hypophosphatémie, hypocalcémie (via PTH) stimulent la synthèse du calcitriol
- hyperphosphatémie, hypercalcémie l'inhibent
** Mort
** Effet
Calcitriol:
- stimule l'absorbtion interstinale du calcium et phosphose
- os: favorise la minéralisation (en augemntant la calcémie)
- rein : stimule la réabsorption tubulaire du phosphore et calcium
- diminue PTH
** Indication
- 25-hydroxy-D = forme circulante prépondérante. Reflète les réserve -> dosé si possibilité de carenc
- 1,25-dihydroxy-vitamine D (calcitriol) = ne reflète *pas* les stock : réservé à une anomalie de 1-\alpha hydroxylation
** Dosage

* Natrémie
- Perte de sodium : perte d'eau pour conserver l'osmolalité -> déshydratation extracellulaire pure (natrémie normale)
- Excès de sodium : rétention d'eau pour conserver l'osmolalité -> hyperhydratation extracellulaire pure (natrémie normale)
- Perte d'eau : hyperosmolarité -> déshydratation intracellulaire
  - hypernatrémie
  - natrémie normale mais avec une substance osmotiquement active (mannitol)
- Rétention d'eau : hyperhydratation intracellulaire par osmose -> *hyponatrémie*
  - ingestion d'eau trop importante
  - ADH se déclenche trop tôt
  - excrétion d'eau diminuée

Hyponatrémie =
- soit erreur de mesure : osmolalité normale mais hyperprotidémie et hyperlipidémie entraînent une fausse mesure d'hyponatrémie (dilution)
- soit hyperosmolalité par glycémie ou méthanel
- soit hypoosmolalité (hyponatrémie vraie) = hyperhydratation *intracellulaire*
* BNP (Brain natriuretic peptide)
** Naissance
synthétisé par myocyte du ventricule gauche (et droit) en réponse à une surcharge volémique
** Vie
- Form de réserve = pré-proBNP, clivé en pro-BPN, clivé en NPT-proBPN (inactif) et BNP (actif).
Se fixe sur les récepteurs de type A sur endothélium vasculaire
- Stockage : non
** Mort:
- BNP: demi-vie de 20min puis dégradé endothéliium
- Nt-proBNP = éliminé dans tous les tissus où le débit est élevé. Demi-vie : 1-2h pour NT-proBNP
  : 20min pour BPN,
** Effet
compense la surcharge volémique par
- vasodilatation périphérique
  natriurétique
- augmentation filtration glomérulaire (*diurétique*)
- diminution réabsorption du sodium (*natriurétique)
- inhibition du système Rénine-Angiotensive-Aldostérone
** Indication
marqueur global de l’issufisance cardiaque (diagnostic, pronostic, suivi)
** Dosage
* CPK (créatine-phosphokinase)
** Naissance
Enzyme dans le cytosole ou mitochondrie des cellule : muscles squelettiques++ et cardiaque, cerveau, rein, gastrointestinal
- CK-MM (95%) = muscle strié squelettique
- CK-MB = muscle cardiaque
- CK-BB (= cerveau, gastro-interdsstinal
** Vie
Catalyse la phosphorylation de la créatine en créatine phosphate par l'ATP (avec production ADP)
** Mort
** Effet
contraction musculaire :
** Indication
- Infarctus du myocarde, myopathie, myosite
- Certains cancers, affection du système nerveux central
** Dosage
* DFG
La clairance de la créatinine est estimée par le Débit de Filtration Glomérulaire.
Évaluation DFG à partir de la créatininémie
  - Cockroft et Gault: mauvaises performances si obèse, > 75 ans. Prend le poids en compte (contrairement aux 2 autres)
  - MDRD : plus précise que Cockroft
  - CKD-EPI: plus précises que MDRD si valeur basse de la créatitinémie
  - Schwartz : enfant
  - recos HAS: CKD-EPI si dosage enzymatique, MDRD si colorimétrique

Attention : formules non utilisable chez l’enfant (formale du Schwartz), variation aigüe de la fonction rénale, cirrhose hépatique décompoensée, gabarit hors norme, amyotrophie important, grossese

dans ce cas, utiliser clairrance urinaire sur urines de 24h = créat urinaire*débit/créat sanguine
* Créatinine
** Naissance
Créatine = synthétisée dans le foie par la méthylation de glycocyamine (lui-même synthétisé dans le foie à partir d’arginine et glycine)
Elle est transportée par le sang aux muscles, cerveau, organe. Par phosphorylation devient la phosphocréatine à l’aide de créatine kinase (voir [[*CPK (créatine-phosphokinase)][CPK (créatine-phosphokinase)]] )
La créatinine est un produit de cette transformation.

La créatinine est aussi sécrétée par le rein
** Vie
Libérée par le muscle
** Mort
Éliminée par le rein
** Effet
 Pas de rôle physiologique
** Indication
Pas de réabsorption par le rein, donc marqueur de fonction rénale
** Dosage

* Foie
** Physiologie
Énergie:
- stocke glucose
- libère le glucose stocké, le produit par néoglucogenèse
- synthèse des corps cétonique:  oxydé pour être utilisé comme énergie par muscle squelettique, cardaque, cortex rénal

Synthèse majeure partie des protéines sauf immunoglobulines
- albumine
- transport (transferrine...)
- coagulation
- inflammation (CRP, partie du complément)
Synthèse du cholestéral
Épuration : 
- déchet du métabolisme = amoniaque sous forme d’urée (catabolisme azotée), bilirubine ,
- hormones (stéroïdes)

  Transforme médicaments, toxique.... par modification (ex: cytochrome P450) puis conjugaison
*** Bilirubine
Production
- 20% catabolisme dans le foie des autres composants de l’hème ou destruction érythroblastes moelle
- 80% hémoglobine par destruction des hématies
Cycle:
- Bilirubine libre/non conjuguée = circule dans le plasma liée à l’albumine
- conjugée dans le foie
- bilirubine conjugée secrétée dans le duodenom par voies biliaires
- oxydation qui va donner la couleurs aux selles. Une partie passe dans les urines

Patho:
- excès des capacité de transport de la bilirubine libre (exemple = préma) on a alors bilirubine libre non liée à l’albumine
- bilirubine conjugée dans le plasma -> urines foncées (diag d’ictère)
*** Fonction biliaire
- élimination métabolite
- absorption lipides

Patho: sursaturation du cholestérol -> cristaux -> calcul
** Marqueurs
*** Cytolyse
- ALAT > 40 U/L = cytosol (foie +/- muscles)
- ASAT > 35 U/L = cytosol + mitochondrie (foie, muscles, coeurs, rein, pancréas, cerveau)
Attention :
  - hémolyse = ininterprétable (aminotransferase globules rouges> plasma )
  - ASAT < ALAT (sauf alcool chronique car grosses mitochrondrie)
  - Aigü : normalisation en 6 mois
  - seulement souffrance cellulaire et non état fonctionnel du foie
NB: LDH (lyse cellulaire) non spécifique mais très marqué pour métastase hépatique
*** Synthèse
- Coagulation : complexe prothrombinique diminué
  - non spécifique des insuffisance hépatocellulaire (cholestase avec défaut absorption vitamine K)
  - si < 60%, doser facteur V pour confirmer IHC
  - attention: fibrose dès <90% dans patho chronique
- Albumine : produit par l’hépatocyte
  - important mais non spécifique de l’IHC (malnutrition, malabsorption, rénal)
*** Épuration
- Urée = diminué si IHC (genèse hépatique)
- Ammoniac = augmenté si ICH -> suivi des IHC et foie (toxicité système nerveux central)
*** Sécrétion bilaire
Surtout défaut d’excrétion bilirubine conjugée + augmentation bilirbuine totale
*** Cholestase
Diminution/arrêt sécrétion biliaire. 3 atteintes :
1. synthèse
2. Sécrétion intrahépatique
3. extrahépatique

Marqueurs
- bilirubine : augmentation totale + conjuguée (attention, ictère retardé : conjonctive si > 50µmol/L)
- enzyme :
  - phosphatase alcaline (PAL) augmentée mais non spécifique (patho. osseuses, cancers)
    [Attention âge, grossesse]
  - gamma-glutamyl transférase (γGT): origine hépatique pour l’enzyme circuante. Augmenté sensible mais peu spécifique (alcool, contraceptiuqe, phénoparbital)
    [Attention population africaine]

Coagulation: Diminution du TP avec facteur V normal

Autres
- Augmentation acides biliaire totaux = cholestase
- Pigments
  - biliaire dans urines (+produits transformations)
  - Selles décolorées = cholestase
- IgM = cirrhose biliaire primitive
*** Inflammation
CRP, vitesse sédimentatino érythrocytaire, électrophorèse ptoténies sériques
*** Fibrose hépatique
- ponction biopsie, Fibroscan (non invasif)
- acide hyaluronique = surtout valeur prédictive négative
- scores : Fibrotest, Fibromètre, Hépascore
** Interprétation
Augmentation ALAT/ASAT
- aigiue > 10N: hépatite virale aigüe A, B, médicaments (IMAO, méthyldopa...), toxique (paracétamol, champignon), lithiase de la voie biliaire prinicpale, ischémie hépatique aigue
- aigüe modérée 3-10N: hépatite virale A, B, autre infections (EBV, cmv, HSV, toxoplasmose), alcool, surcharge pondérale, atteinte hépatobiliaire chronique
- chronique < 3: VHC, VHB chronique, stéatose hépatique du diabote/dyslipidémie,/obésite, alcoolisme (rappport inversé), autres médicaments (isoniazide...), autto-immun, surcharge (hméocromatose, Wilson)
  NB: élimiier une nécrose musculaire/myocardique, pancréate
  NB: cherche un risque d’hépatite fulminante : TP, facteur v, ammionémie

  Bilan enzymatique anormal
  | \gamma GT | PAL      | ALAT,ASAT | Étiologies                                              |
  |-----------+----------+-----------+---------------------------------------------------------|
  | augmenté  | augmenté | augmenté  | hépatopatihe cytolytique                                |
  |           |          |           | hépatite virale, alcool, médicaments                    |
  | augmenté  | augmenté | N         | hépatopathie cholestatique                              |
  |           |          |           | médicaments (antidépresseurs), biliaire, pancréas, foie |
  | augmenté  | N        | N         | alcool, médicaments inducteurs                          |
  |           |          |           | enzymatique, stéaotose, sucharge pondérale              |
  |           |          |           | +/- hyperthyoroïdies, parasite                          |

    Ictère : augmentation bilirubine
    | non conjuguée : | - extra-hépatique | hémolyse  (nouveau-né, constit, acquis)                                   |
    |                 | - hépatique       | : Gilbert, Criggler-Najjar, ictère transitoire du nouveau-né              |
    | conjuguée       | - intra-hépatique | : médicaments, hépatite virale/parasitaire, autoimmun,                    |
    |                 |                   | carcinome, cirrhose biliaire primitive, septicémie, cholestase gravidique |
    |                 | - extra-hépatique | lithiase cholédoque, cancer pancréas, pancréatite chronique               |
    |                 |                   | , cholangite sclérosante, sténose/carcinome des voies biliaires           |
** Cirrhose
- IHC: TP, facteur V, dosage albumine (ou EPS)
- inflammatoire : bloc β-γ, augmentation α2 globuline
- score Child-Pugh (ascite, encéphaloapatihe, albuminméue, bilirubinémie, TP)
** Dépistage carcinome hépatocellulaire
αfoetoproténie = suivi et non iagnostic. régérénration des hépatocyttes
** Grossesse
- Physiologique : diminution albuminémie possible, augmenation PAL
- cholestase gravidique : prurit, augmenation acide biliarie sérique : 10-40 modéré,, sérève si > 40
  - ALAT = 2-10N >> ictère 10%, bili augmentée et γGt No/augmentée: 30%, stéatorrhéie (déficit en vitamine K visible sur TP)
* Phosphatales alcalines
** Naissance
Très répandues dans les tissus.
** Vie
Libérées dans le sang lors de l'altération de la membrane cellulaire
** Mort
** Effet
Permet le passage de métabolite à travers les membranes cellulaires (catalyse l'hydrolyse d'esters monophosphorique en libérant du phosphate)
** Indication
- Maladies hépato-biliaire cholestatiques
- Malades osseuses avec régénération ostéoblastiques
- Grossesse avec cholestase gravidique
- Certaines pathologise intestinales, suivi de certains cancers
** Dosage
