#+title: Gentoo
#+filetags: cs gentoo

* Install
:PROPERTIES:
:ID:       590b7a4c-3bed-4d9d-93db-78ef1f673f96
:END:
=sys-kernel/gentoo-kernel-bin= contient un noyau pré-compilé avec la plupart des choses nécessaires
** Difficulté
Si la clé USB ne démarre pas en UEFI, installer jusqu'à GRUB puis mettre [[https://www.system-rescue.org/][system rescues]] sur la clé USB et inrstaller grub.
* Config
See github repo portag-config
** X
Sans bureau, il faut ajouter pulseaudio dans .xinitrc !

#+begin_src sh
setxkbmap fr bepo
feh --bg-scale ~/pictures/gentoo.jpg &
exec pulseaudio &
exec xmonad

#+end_src

* TBW-108UB
** Version naive
#+begin_src sh
git clone https://github.com/lwfinger/rtl8723bu.git /usr/local
cd /usr/local/rtl8723
# Comment concurrent mode (enable connection + access point by default)
sed '/EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE/s/^/#/' Makefile
make
make install
modprobe 8723u
# Enable for future boot
echo 8723bu > /etc/modprobe.d/networking.conf
#+end_src

* Difficultés
** ZFS
Difficulté avec pool partagée avec Freebsd.
1. data n'est pas montée proprement
    Cela est du à zfs-import-cache
    #+begin_src  sh
    systemctl status zfs-import-cache
    #+end_src
    Il trouve que /etc/zpool/cache n'est pas vide. En resettant le cache, cela semble marcher
    #+begin_src sh
zpool export data
zpool import data
zpool set cachefile=none data
zpool set cachefile=/etc/zfs/zpool.cache  data
    #+end_src

2. zroot devrait être montée dans un endroit spécifique
   On ne monte que data
Changer ExecStart dans /lib/systemd/system/zfs-mount.service pour monter seulement data
#+begin_src sh
ExecStart=/sbin/zfs mount data
#+end_src

* TODO Désinstaller un package qui n'est pas dans @world
emerge -vcp $PACKAGE
et on descend dans les dépendences jusqu'à trouver celle qui pèche
* Synchronisation iphone
pour la musique, installer OPlayerHD Lite sur l'iphone et suivre les instructions https://wiki.gentoo.org/wiki/Apple_iPod,_iPad,_iPhone
#+begin_src  sh
ifuse --documents  com.olimsoft.oplayer.lite /mnt/iphone-oplayer
#+end_src
* Écrire un ebuild
:PROPERTIES:
:ID:       a02f8422-149b-4bba-8042-664d7699a7d9
:END:
Attention, le package doit être installé dans /usr et non /usr/local ! Sinon avertissement
Étapes
- ebuild manifest
- ebuild compile
- ebuild install : localement
- ebuild merge : dans le système
Pour les pacquets Go
https://wiki.gentoo.org/wiki/Writing_go_Ebuilds
Il faut héberger une archive avec les dépendences. On peut faire un dépot Git avec juste une LICENSE et créer une "release" manuellement contenant cette archive.
** [[id:83b9193c-8bb2-413f-9371-fa2baf8b333a][Haskell package pour Gentoo]]
* Erreurs
** Missing keyword
!!! All ebuilds that could satisfy "=dev-lang/julia-1.9.0" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-lang/julia-1.9.0::gentoo (masked by: missing keyword)

Utiliser emerge --autounmask
** Haskell: packages masked or missing
Dependences compliquées à gérer : utiliser --backtrack=30
** Suppression de /usr/share/texmf* par erreur
Réinstaller texlive-core
