​#emacs # Bibliographie annotée

3 possibilités d'avoir une bibliographie annotée

** Avec citar:
:PROPERTIES:
:CUSTOM_ID: avec-citar
:END:
Il faut un fichier bibtex contenant les citations. Lorsqu'on insère une
citation, on peut créer une note (dans citar-notes-paths) pour cet
article avec "entrée" S'il y a un asticle correspondant dans
citar-library-paths, on peut également l'ouvrir. Exemple

#+begin_src org
\* Research1
- [cite:@saffari2001] Best review
- [cite:@adang200] First review
#+end_src

Inconvénient: pour chercher les notes, il faut un fichier org qui
regroupe les citations par catégories.

Configuration

#+begin_src lisp
(after! citar
  (setq! citar-bibliography '("~/roam/research/biblio.bib" "~/roam/research/bisonex/thesis/biblio.bib")
         citar-library-paths '("~/papers/bisonex")
         citar-notes-paths '("~/roam/research/references")
         citar-org-roam-subdir "~/roam/research/references/")))
#+end_src

Dans le fichier, il faut

#+begin_src org
,#+bibliography: memoire.bib
#+end_src

** Org-mode tangle
:PROPERTIES:
:CUSTOM_ID: org-mode-tangle
:END:
Voir
[[https://cachestocaches.com/2020/3/org-mode-annotated-bibliography/]]

** Org-mode directement avec org-bibtex
:PROPERTIES:
:CUSTOM_ID: org-mode-directement-avec-org-bibtex
:END:
On récupère le bibtex avec notre function. Puis il faut couper le bloc
bibtex (d% avec evil) et le transformer en entrée "org-mode" avec
org-bibtex-yank Il faut exporter le tout en bibtex avec org-bibtex

+: formattage org-mode

* Dired
:PROPERTIES:
:CUSTOM_ID: dired
:END:
( pour voir les détails ) pour voir les infos git

* Latex export
:PROPERTIES:
:CUSTOM_ID: latex-export
:END:
Utiliser :booktabs t pour avoir des jolies tableaux. Apparement, il
suffit de rajouter le package dans les header

#+begin_src org
,#+latex_header: \usepackage{booktabs}

,#+ATTR_LATEX: :booktabs t
| Disease | Gene | Onset | Symptoms | MRI |
|---------+------+-------+----------+-----|
| lol     |      |       |          |     |
#+end_src

[[id:ed20c9d9-423f-4430-8eb8-d22b3ba14980][Org-mode]]
