#+TITLE: Maladies
* Pendred
- Clinique : surdité congénitale neurosensorielle sévère/profonde, atteinte vestibulaire, anomalies os temporal
- Diagnostic : clinique = surdité neurosensorielle + anomalies scan rochers + goître euthyroïdien
- Gènes : SLC26A4
- Traitement : sympto
- Transmission : AR

* TODO Leigh et NARP
  https://www.ncbi.nlm.nih.gov/books/NBK1173/
* Incontentia pigmenti
- génodermatose affectant la peau, les dents, les yeux et le système nerveux central
- «incontinence pigmentaire» = dépôts dermique de mélanine
- atteinte dermatologiuqe typique
- diagnostic clinique dans la majorité
- létale chez foetus masculin en général

** Clinique : stades
1. vésiculo-pustuleux, acral et linéaire = première sesmaines de vie -> 18 mois
2. Verruqeux : premiers mois
3. Hyperpigmentation
4. Hypopigmentation, alopécie
** Pathophysiology (2002)/histologie
1. Inflammation, infiltration éosinophile -> bulles spongiotique éosinophiles
2. -> épiderme acanthosiuqe, hyperkératosique
3. ? -> dépôts dermiques de mélanine
4. cicatrisation dermique post-inflammatoire

** Clinique : phanère, oculaire
Phanères :
- alopécie, cheveux fins, épars, parfois laineuse sourcis fins, épairs.
- ongles striés
Oculaire
- vasculaire rétinine périphérique  (**risque de cécité**) décollement possible
- vasculaire maculaire
- cornea verticillata (évocatrice)
- hyper/hypopigmentation de l’epithelium pigmentaire rétinien(évocatrice)

** Clinique : dentaire
Critère majeur
- anomalise de la couronne (70%)
- agénésies multiples (90% en denture permanente)
- fente labio-palatineo
  img santamaria2016
** Clinique : SNC
Néonatal : **convulsion** avec complications
- risque épilepsie partielle
- cognitif
- déficit moteur (hémi/para/tétraparésie) 15-30%
- parfois **létales**

Cognitif : variable : DI sévère -> troubles des apprentissages
** Génétique : pronostic
Atteinte neuro, ophtalmo précoce = le conditiennent.
Sinon, développement physique et cognitif normal dans la majorité
** Génétique : diagnostic

IMG
https://onlinelibrary.wiley.com/doi/full/10.1111/ddg.14638

- mutation familiale 10-25%, > 50% de novo
- gène  IKBG (Inhibitor Of Nuclear Factor Kappa B Kinase Subunit Gamma)
- hommes : plusieurs cas décrit
  - X supplémentaire
  - mosaïcisme somatique
  - mutation particulière IKBKG
** IKBG

** Source
- PNDS
- Genereviews
- Santa-Maria FD, Mariath LM, Poziomczyk CS, et al. Dental anomalies in 14 patients with IP: clinical and radiological analysis and review. Clin Oral Investig. 2017;21(5):1845-1852. doi:10.1007/s00784-016-1977-y
* Syndrome de West
In about 35% of cases, the etiologic event is (still) unknown:
others = structural, infectious, metabolic and immunologic defects and genetic abnormalities
 may be prenatal, perinatal, and post-natal period.
 ischemic encephalopathy is reported as one of the most common causes of ISs.
 “United Kingdom Infantile Spasms Study” (UKISS) [14],  hypoxic-ischemic encephalopathy was reported in 10%, followed by chromosomal abnormalities, complex malformation syndromes and perinatal stroke (8%), tuberous sclerosis (7%), and periventricular leukomalacia or hemorrhage (respectively, in 5%)
Source https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7655587/

* Syndrome d’Alagille
Suspected on :
- histologic = bile duct paucity (an increased portal tract-to-bile duct ratio)
- 3/5 major clinical features (in addition to bile duct paucity):
  - Cholestasis
  - Cardiac defect (most commonly stenosis of the peripheral pulmonary artery and its branches)
  - Skeletal abnormalities (most commonly butterfly vertebrae identified in AP chest radiographs)
  - Ophthalmologic abnormalities (most commonly posterior embryotoxon
  - Characteristic facial features (most commonly, triangular-shaped face with a broad forehead and a pointed chin, bulbous tip of the nose, deeply set eyes, and hypertelorism; see Figure 1)
Genes = JAG1, NOTCH2
AR
Pronostic: renal transplant, cardiac... but not lethal

* Hémochromatose

** Physiopathologie
Circuit quasi-fermé : la destruction des globus rouges par les macrophages recycle le fer. Peu de pertes, peu d’apport
Régulation au niveau de l’intestin car pas de mécanisme d’excrétion (hormis desquamation ) !
Hepcidine = peptite synthésé dans le foie qui est le régulateur principale pour fer
- bloque absorption intestinale
- bloque relargage du stockage du fer (foie)
  -> peu d’hepicidine = surcharge en fer
** Clinique
Accumulation fer dans cellules parenchymateuses :
- foie+++ -> cirrhose
  , coe)
- coeur -> cardiomyopathie
- glandes endocrine -> diabète
- peau -> mélanodermie
- articulations -> arthralgie

  Évolution : phase biologique -> clinique
  Ttt: saignée tôt -> espérance de vie normale
** Génétique
Multigénique
*** HFE
- Homozygotie p.[Cys282Tyr] prédominant mais expression variable
- p.[Cys282Tyr] [His63Asp] = facteur de risque
** Autres
|      | Juvénile | intermédiaire | adulte       |
| Diag | précoce  |               | tardif       |
|      | sévère   | moins sévère  | modéré       |
|      | HJV/HAMP | TRF2          | HFE, SLC40A1 |
|      | AR       | AR            | AR ou AD     |
NB: SLC40A1 : 2 phénotype selon le mécanisme (perte de fonction = ferroportini disease, gain = hémochromatose type 4)
** Avertisemente
Multifactoriel:
- protecteur = variant fréquents, CYBRD1
- agravant = homme (testostérone), alcool, variant rare, HAMP/HJV, fréquents
