​#biochimie # Localisation, rôle physiologique

C'est le produit final de la glycolyse anaérobie dans le cytoplasme
cellulaire. Il s'agit d'une impasse métabolique et peut s'accumule de
manière importante lors de la dégradation anaérobie du glucose.

* Tissus/organes de production et d'élimination
:PROPERTIES:
:CUSTOM_ID: tissusorganes-de-production-et-délimination
:END:
L'acide l'actique résultat de la transformation du pyruvate catalysé par
la lacticodéshydrogénase dans le muscle, cerveau, érytrocyte, intestin
et peau. Le foie et le rein sont les principaux organes consommateurs :
à jeun, il est transformé en glucose (rein foie). Après un repas, il est
oxydé au niveau des mitochondries.

* Valeurs de référence (adulte)
:PROPERTIES:
:CUSTOM_ID: valeurs-de-référence-adulte
:END:
0-2mmol/L

* Principe analytique de mesure
:PROPERTIES:
:CUSTOM_ID: principe-analytique-de-mesure
:END:
Ampérométrie (mesure de l'oxydation d'hydrogène en oxygène)

​****c503 (roche)**** : test colorimétique avec la peroxydase

* Principales interactions analytiques
:PROPERTIES:
:CUSTOM_ID: principales-interactions-analytiques
:END:
​****c503 (roche)**** :

- diminué si N-acétylcystéine, métabolite du *paracétamol*
- dobésitale de calcium, interféresnce si métamizole, glycolate

* Vigilance pré-analytiques et analytiques
:PROPERTIES:
:CUSTOM_ID: vigilance-pré-analytiques-et-analytiques
:END:
- Acheminement rapide : agumentation du lactates au cours du temps et
  selon la température : 0,1 mM/heure à 4°C et de 1,0 mM/heure à 37°C

* Augmentation et diminution
:PROPERTIES:
:CUSTOM_ID: augmentation-et-diminution
:END:
- Pathologique :
  - anoxie par hypoperfusion tissulaire : choc (endotoxine,
    cardiogénique, hémorragique), anémie sévère, insuffisance
    vetriculaire gauche, état de mal convulsif, asthmie sévère,
    insuffisance respiratoire sévère, méthémoglobinémie, intoxicaito au
    CO ou cyanure
  - systémique : diabète, insuffisance rénale/hépatocellulaire,
    hémopathie, cancer
  - toxique et médicamenteux (éthanol, méthanol....)
  - déficits enzymatiques
- Physiologique : effort physique, post-prandial, alcoolisme, nutrition
  parentérale, jeune
