#+title: Trou anionique (cobas)
#+author: Alexis Praga
#+setupfile: ./fiche.setup


* Localisation, rôle physiologique
Sérum.
* Valeurs de référence (adulte)
Normalement, il y a autant d’anions que de cations. En pratique, tous les électrolytes ne sont pas mesurés donc le TA (trou anionique) est de 16 \pm 4 mmol/L
* Principe analytique de mesure
C’est un paramètre calculé selon
$[Na]^+ [K]^+ - [Cl]^- - [HCO_3]^-$
NA, K et Cl sont mesuré par une électrode sélective d’ion.
* Principales interactions analytiques
- hémolyse sur le potassium
- pseudohyponatrémie si lipidémie
- pseudo hypo/hyper-natrémie selon le taux de protides
- chlore augmenté pour patients sous perchlorate
* Vigilance pré-analytiques et analytiques
* Augmentation et diminution
Le trou anionique permet d’orienter les étiologies d’acidose métabolique. La perte en bicarbonates est compensée soit par
- l’augmentation du chlore (TA normal)
  - accumulation aigüe d’acide : intoxication (chlorure d’ammonium, HCL)
  - perte de bicarbonate : diarrhées, anastomose urétéro-intestinales, acidose tubulaire proximale
  - diminution de l’excrétion rénale d’acide : acidose tubulaire distale
- l’augmentation d’un autre anion indosé (protéines plasmatiques, phosphase, sulfates...) donc TA augmenté > 20mmol/L)
  - accumulation aigüe d’acide : acidose lactique, acidocétose, intoxication au méthonal, éthylène glycole
  - diminution de l’excrétion rénale d’acide : insuffisance rénale
