:PROPERTIES:
:ID:       b5971189-6e5e-4a59-89bd-5f21e303f378
:END:
#+title: Croisades et Orient latin - XIe-XIVe siècle
#+filetags: books history

- TODO Introduction

- TODO 1. Orient et Occident à la fin du XIe siècle

- DONE 2. L'appel de Clermont et les origines de la croisade 1095 : le
  pape Urbain II lance son appel Contexte :

  - réforme de l'Église avec souverainete "universelle" (Querelle des
    Investitures)
  - reconnaissance de la violence chez les laïcs pour protéger l'Église
  - demande du basileus pour aide militaire via des mercenaires
    Seulement une petite partie du concile. Thèmes :
  - secourir chrétiens d'Orients victimes de l'invasion turque
  - libérer Jérusalem
  - Attention: pas de lutte chrétienté-islam
  - pelerinage Diffusion via les voyages du pape, prédication populaire
    (Pierre l'Ermite), clergé séculiers, moines Définition de la
    croisade = pélerinage en armes pour libérer Saint-Sépulcre

  Voeu de croisade : contraignant (excommunication si non fait) avec
  passe-droits possible, privilèges

  - rémission des péchés et des fautes
  - protection personnelle et des familles, mise en gage/hypothèque
    possible

- DONE 3. La Première Croisade 1096-1100 Recrutement

  - Contigent par Pierre l'Ermite : paysans principalement
  - liens familaux, vassaliques
  - femmes : épouses, prostituées... Difficulté pour les chefs de
    restreindre l'activité sexuelle
  - effectifs : 1 200 chevaliers, 12 000 fantassins arrivent à
    destination Financement = importsant !!
  - butin, pillage
  - famille du croisé, cesions, prêts sur gage
  - certains finissent endettés, enrichissement des communes italiennes,
    églises Chefs :

- Pierre l'Ermite : charismatique, extrêment populaire

- Godefroy de Bouillon

  - militaire: rôle dans la prise de Jérusalem (1099), contribue à
    l'expansion franque
  - élu en 1099 face à Raymond de Saint-Gille
  - réécriture de l'histoire après sn élection: origine divine,
    conquérant...

- Bohémond: chef de l'armée normande, forte personnalité

  - s'empare d'ANtioche et demaire maître de la ville mais fait
    prisonnier
  - en 1104 organise une nouvelle croisade
  - diplomate, ambitieux, démarre le thème de la haine des grecs

- Baudoin de Boulogne: créateur du comté d'édesse (1098), dur, violent

- Raymond de Saint-Gilles

  - chef provencal et languedoc, comte de Toulouse
  - participe à la prise de Jérusalem, en confilt avec Godefroy de
    Boullon
  - modèle pour les contemporaines, orgueilleux, ambitieux mais
    difficulté à réalisé ses ambitions Itinéraires

1. Plaine du Danube -> Balkan -> franchissement par Constantinople/Les
   Darnallesse -> Anatolie -> plaine cilicienn -> Antioche
2. Côte albanaise -> côte égéenne -> Constantinople Puis on longe la
   côte

** 1096 -> 1097 marche jusque Constantinople - Troupes par Pierre
l'Hermite : incontrôlables, pilles et massacres, exterminées par les
Turcs devant nicées - Convergence à Constatinople des 3 armées: - Armée
lorraine (Godefroy de Bouillon et Baudoin de Boulogne) - Armée normande
(Italie du Sud) - ARmée provencale Cour byzantine : armée inattendue,
cherche à s'en débarasser => défiance et hostilité avec Occidentaux

** 1097 -> 1099 succès quasi-miraculeux Prise de nicée 1097, défaite des
Turcs mais marche difficile en Anatolie - Les troupes conduites par
Bédouins se dirigent à l'ouest et fondent le comté d'Édesse - Le gros
des troupes - prend Antioche après 7 mois (1098) et défaitee l'armée
turque, route de Jérusam ouverte - prise de Jérusalem en 1099, pillée et
massacrées (juifs, musulmans). Baudoin Ier couronné roi de Jérusalem -
division du monde musulman mais beaucoup de croisés retournent en
Occident - Autre croisade en "0101 qui échoue lamentablement
(destruction par les turcs)

- DONE 4. Les États francs de Syrie-Palestine au XIIe siècle : Édesse,
  Antioche, Tripoli ** Comté d'Édesse 1098 - 1150 Ville d'Édesse =
  arménienne, tribut au Turcs mais autonome Conquête par Baudoin de
  Boulogne, qui le remet à son cousin Baudouin du Bourcq Veut consolider
  son pouvoir mais est fait prisonner. Tancrède prend la régence et
  conflit entre les 2 hommes quand Baudouin du Bourcq est libéré (avec
  alliance avec les musulmans !) Arbitrage par Baudoin Ier en faveur de
  son cousin Attaques musulmanes, prétentions byzantines. Édesse est
  prise en 1144, chute de la ville en 1150 ** Principauté d'Antioche
  Après la prise par Bohémond, doit laisser la régence à son neveu
  Tancrède, régence pour Bohémond II. Troubles graves après la mort de
  ce dernier face à

  - Zengì, qui essaie de créer un grand état musulman
  - Byzantins qui intervienne pour rétablir leurs droits sur la ville Le
    Basileus fait reconnaître sa souveraineté de force mais chassé par
    une révolte La principauté est sauvée par la mort du basileus Le
    nouveau régent doit reconnaître la suzeraineté de manière humiliante
    auprès du nouveau basileuse Sauvée par le protectorat byzantin,
    réduit à un petit royaume par Saladin ** Comté de Tripoli Assiègé
    par Raymond IV de Saint-Gilles, Tripoli tombe aux mains de ses
    successeurs en 1109 Comté encore intact en 1187 Originalité :
    suzerainité du basileus nominale, hommage à Jérusalem mais grande
    liberté Caractère héréditaire du pouvoir Affaibilé par les luttes
    des Italiens et indépendance des ordres militaires

- TODO 5. Le royaume latin de Jérusalem au XIIe siècle
- TODO 6. Le film des croisades
- TODO 7. L'Islam et les croisades
- TODO 8. L'Italie et les croisades
- TODO 9. Les États latins au XIIIe siècle
- TODO 10. Déviations et critique de la croisade
